
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.stmwr.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.stmwr.block.ZombieChompBlock;
import net.mcreator.stmwr.block.WarpBrickBlock;
import net.mcreator.stmwr.block.UraniumProcessingPlantBlock;
import net.mcreator.stmwr.block.UraniumOreBlock;
import net.mcreator.stmwr.block.UraniumHydroponicsUtilityHatchBlock;
import net.mcreator.stmwr.block.UraniumHydroponicsBlock;
import net.mcreator.stmwr.block.UraniumCasingBlock;
import net.mcreator.stmwr.block.UraniumBlockBlock;
import net.mcreator.stmwr.block.UntouchedSoilBlock;
import net.mcreator.stmwr.block.TrialBrickBlock;
import net.mcreator.stmwr.block.TotemFusionStationBlock;
import net.mcreator.stmwr.block.TomatoPlantBlock;
import net.mcreator.stmwr.block.TARDISWindowsBlock;
import net.mcreator.stmwr.block.TARDISTopTextBlock;
import net.mcreator.stmwr.block.TARDISPlatingBlock;
import net.mcreator.stmwr.block.TARDISPhoneBlock;
import net.mcreator.stmwr.block.TARDISHandleBlock;
import net.mcreator.stmwr.block.SwarmBlock;
import net.mcreator.stmwr.block.SurvivorsMarketBlock;
import net.mcreator.stmwr.block.StorumOreBlock;
import net.mcreator.stmwr.block.StorumBlockBlock;
import net.mcreator.stmwr.block.StopstoneBlock;
import net.mcreator.stmwr.block.StevumOreBlock;
import net.mcreator.stmwr.block.StevumBlockBlock;
import net.mcreator.stmwr.block.SteveCowLandPortalBlock;
import net.mcreator.stmwr.block.SporBlock;
import net.mcreator.stmwr.block.SpellforgeBlock;
import net.mcreator.stmwr.block.SpeedstoneBlock;
import net.mcreator.stmwr.block.SoulManipulatorAccessPointBlock;
import net.mcreator.stmwr.block.SnowrockBlock;
import net.mcreator.stmwr.block.SnowdirtBlock;
import net.mcreator.stmwr.block.SnapstoneSlabBlock;
import net.mcreator.stmwr.block.SnapstoneBlock;
import net.mcreator.stmwr.block.SmoothSnapstoneBlock;
import net.mcreator.stmwr.block.SmoothIrradiatedStoneBlock;
import net.mcreator.stmwr.block.SigmariBlock;
import net.mcreator.stmwr.block.RitualStoneBlock;
import net.mcreator.stmwr.block.RepairPlantBlock;
import net.mcreator.stmwr.block.RadioactiveRoyalBlock;
import net.mcreator.stmwr.block.RadiationRemovalPlantAccessPointBlock;
import net.mcreator.stmwr.block.PurifierMK2Block;
import net.mcreator.stmwr.block.PoinkBlock;
import net.mcreator.stmwr.block.PlasticBlock;
import net.mcreator.stmwr.block.PeanutPlantBlock;
import net.mcreator.stmwr.block.OrePurifierBlock;
import net.mcreator.stmwr.block.MilitariaPortalBlock;
import net.mcreator.stmwr.block.MemoryFlowerBlock;
import net.mcreator.stmwr.block.ManufacturingPlantAccessPointBlock;
import net.mcreator.stmwr.block.MagiciteOreBlock;
import net.mcreator.stmwr.block.MagiciteClumpBlock;
import net.mcreator.stmwr.block.MagiciteBlockBlock;
import net.mcreator.stmwr.block.MagiciansWorkbenchBlock;
import net.mcreator.stmwr.block.MagicalCasingBlock;
import net.mcreator.stmwr.block.KitchenBlock;
import net.mcreator.stmwr.block.KeyAnvilBlock;
import net.mcreator.stmwr.block.ItemReseacherAccessPointBlock;
import net.mcreator.stmwr.block.IrradiatedWaterBlock;
import net.mcreator.stmwr.block.IrradiatedStoneSlabBlock;
import net.mcreator.stmwr.block.IrradiatedStoneBlock;
import net.mcreator.stmwr.block.IrradiatedCobblestoneBlock;
import net.mcreator.stmwr.block.ImpureCopperBlock;
import net.mcreator.stmwr.block.ImprovedCellBlock;
import net.mcreator.stmwr.block.IcicleBlock;
import net.mcreator.stmwr.block.IcemiteBlock;
import net.mcreator.stmwr.block.IceflameBlock;
import net.mcreator.stmwr.block.IcedaisyBlock;
import net.mcreator.stmwr.block.HypercellBlock;
import net.mcreator.stmwr.block.HeartstoneOreBlock;
import net.mcreator.stmwr.block.HeartstoneBlockBlock;
import net.mcreator.stmwr.block.GoldRocksBlock;
import net.mcreator.stmwr.block.GodliumOreBlock;
import net.mcreator.stmwr.block.GodliumBlockBlock;
import net.mcreator.stmwr.block.FrozenGrassBlock;
import net.mcreator.stmwr.block.FrozenForgeBlock;
import net.mcreator.stmwr.block.FrostyWoodBlock;
import net.mcreator.stmwr.block.FrostyStairsBlock;
import net.mcreator.stmwr.block.FrostySlabBlock;
import net.mcreator.stmwr.block.FrostySaplingBlock;
import net.mcreator.stmwr.block.FrostyPressurePlateBlock;
import net.mcreator.stmwr.block.FrostyPlanksBlock;
import net.mcreator.stmwr.block.FrostyLogBlock;
import net.mcreator.stmwr.block.FrostyLeavesBlock;
import net.mcreator.stmwr.block.FrostyFenceGateBlock;
import net.mcreator.stmwr.block.FrostyFenceBlock;
import net.mcreator.stmwr.block.FrostyButtonBlock;
import net.mcreator.stmwr.block.FrosticeBlock;
import net.mcreator.stmwr.block.ForgeBlock;
import net.mcreator.stmwr.block.FirewoodWoodBlock;
import net.mcreator.stmwr.block.FirewoodStairsBlock;
import net.mcreator.stmwr.block.FirewoodSlabBlock;
import net.mcreator.stmwr.block.FirewoodSaplingBlock;
import net.mcreator.stmwr.block.FirewoodPressurePlateBlock;
import net.mcreator.stmwr.block.FirewoodPlanksBlock;
import net.mcreator.stmwr.block.FirewoodLogBlock;
import net.mcreator.stmwr.block.FirewoodLeavesBlock;
import net.mcreator.stmwr.block.FirewoodFenceGateBlock;
import net.mcreator.stmwr.block.FirewoodFenceBlock;
import net.mcreator.stmwr.block.FirewoodButtonBlock;
import net.mcreator.stmwr.block.FirelilyBlock;
import net.mcreator.stmwr.block.DupestoneBlock;
import net.mcreator.stmwr.block.DoomsandBlock;
import net.mcreator.stmwr.block.DoomglassBlock;
import net.mcreator.stmwr.block.DoomforgeAccessPointBlock;
import net.mcreator.stmwr.block.DesignerAccessPointBlock;
import net.mcreator.stmwr.block.DeadironOreBlock;
import net.mcreator.stmwr.block.DeadironCasingBlock;
import net.mcreator.stmwr.block.DeadironBlockBlock;
import net.mcreator.stmwr.block.DeadWoodBlock;
import net.mcreator.stmwr.block.DeadStairsBlock;
import net.mcreator.stmwr.block.DeadSlabBlock;
import net.mcreator.stmwr.block.DeadPressurePlateBlock;
import net.mcreator.stmwr.block.DeadPlantsBlock;
import net.mcreator.stmwr.block.DeadPlanksBlock;
import net.mcreator.stmwr.block.DeadLogBlock;
import net.mcreator.stmwr.block.DeadGrassBlock;
import net.mcreator.stmwr.block.DeadFlowerBlock;
import net.mcreator.stmwr.block.DeadFenceGateBlock;
import net.mcreator.stmwr.block.DeadFenceBlock;
import net.mcreator.stmwr.block.DeadButtonBlock;
import net.mcreator.stmwr.block.CorpserockBlock;
import net.mcreator.stmwr.block.ConsumerBlock;
import net.mcreator.stmwr.block.ConcreteMixerBlock;
import net.mcreator.stmwr.block.CompressorBlock;
import net.mcreator.stmwr.block.ColdsteelOreBlock;
import net.mcreator.stmwr.block.ColdsteelBlockBlock;
import net.mcreator.stmwr.block.ColdGrassBlock;
import net.mcreator.stmwr.block.CoffinBlock;
import net.mcreator.stmwr.block.CobblesnowBlock;
import net.mcreator.stmwr.block.CellCasingBlock;
import net.mcreator.stmwr.block.CellBlock;
import net.mcreator.stmwr.block.BlockOfScrapBlock;
import net.mcreator.stmwr.block.BlazingPlasticBlock;
import net.mcreator.stmwr.block.BlazedOreBlock;
import net.mcreator.stmwr.block.BlazedBlockBlock;
import net.mcreator.stmwr.block.AshBlock;
import net.mcreator.stmwr.block.ApplevineBlock;
import net.mcreator.stmwr.block.AlloyFuseBlock;
import net.mcreator.stmwr.StmwrMod;

public class StmwrModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, StmwrMod.MODID);
	public static final RegistryObject<Block> PEANUT_PLANT = REGISTRY.register("peanut_plant", () -> new PeanutPlantBlock());
	public static final RegistryObject<Block> TOMATO_PLANT = REGISTRY.register("tomato_plant", () -> new TomatoPlantBlock());
	public static final RegistryObject<Block> MAGICITE_ORE = REGISTRY.register("magicite_ore", () -> new MagiciteOreBlock());
	public static final RegistryObject<Block> MAGICITE_BLOCK = REGISTRY.register("magicite_block", () -> new MagiciteBlockBlock());
	public static final RegistryObject<Block> MAGICIANS_WORKBENCH = REGISTRY.register("magicians_workbench", () -> new MagiciansWorkbenchBlock());
	public static final RegistryObject<Block> STORUM_ORE = REGISTRY.register("storum_ore", () -> new StorumOreBlock());
	public static final RegistryObject<Block> STORUM_BLOCK = REGISTRY.register("storum_block", () -> new StorumBlockBlock());
	public static final RegistryObject<Block> PLASTIC = REGISTRY.register("plastic", () -> new PlasticBlock());
	public static final RegistryObject<Block> FORGE = REGISTRY.register("forge", () -> new ForgeBlock());
	public static final RegistryObject<Block> SPELLFORGE = REGISTRY.register("spellforge", () -> new SpellforgeBlock());
	public static final RegistryObject<Block> BLAZED_ORE = REGISTRY.register("blazed_ore", () -> new BlazedOreBlock());
	public static final RegistryObject<Block> BLAZED_BLOCK = REGISTRY.register("blazed_block", () -> new BlazedBlockBlock());
	public static final RegistryObject<Block> BLAZING_PLASTIC = REGISTRY.register("blazing_plastic", () -> new BlazingPlasticBlock());
	public static final RegistryObject<Block> ORE_PURIFIER = REGISTRY.register("ore_purifier", () -> new OrePurifierBlock());
	public static final RegistryObject<Block> GODLIUM_ORE = REGISTRY.register("godlium_ore", () -> new GodliumOreBlock());
	public static final RegistryObject<Block> GODLIUM_BLOCK = REGISTRY.register("godlium_block", () -> new GodliumBlockBlock());
	public static final RegistryObject<Block> STOPSTONE = REGISTRY.register("stopstone", () -> new StopstoneBlock());
	public static final RegistryObject<Block> SPEEDSTONE = REGISTRY.register("speedstone", () -> new SpeedstoneBlock());
	public static final RegistryObject<Block> DUPESTONE = REGISTRY.register("dupestone", () -> new DupestoneBlock());
	public static final RegistryObject<Block> ALLOY_FUSE = REGISTRY.register("alloy_fuse", () -> new AlloyFuseBlock());
	public static final RegistryObject<Block> TOTEM_FUSION_STATION = REGISTRY.register("totem_fusion_station", () -> new TotemFusionStationBlock());
	public static final RegistryObject<Block> CONSUMER = REGISTRY.register("consumer", () -> new ConsumerBlock());
	public static final RegistryObject<Block> COMPRESSOR = REGISTRY.register("compressor", () -> new CompressorBlock());
	public static final RegistryObject<Block> TRIAL_BRICK = REGISTRY.register("trial_brick", () -> new TrialBrickBlock());
	public static final RegistryObject<Block> KEY_ANVIL = REGISTRY.register("key_anvil", () -> new KeyAnvilBlock());
	public static final RegistryObject<Block> HEARTSTONE_ORE = REGISTRY.register("heartstone_ore", () -> new HeartstoneOreBlock());
	public static final RegistryObject<Block> HEARTSTONE_BLOCK = REGISTRY.register("heartstone_block", () -> new HeartstoneBlockBlock());
	public static final RegistryObject<Block> STEVE_COW_LAND_PORTAL = REGISTRY.register("steve_cow_land_portal", () -> new SteveCowLandPortalBlock());
	public static final RegistryObject<Block> SNAPSTONE = REGISTRY.register("snapstone", () -> new SnapstoneBlock());
	public static final RegistryObject<Block> SNOWDIRT = REGISTRY.register("snowdirt", () -> new SnowdirtBlock());
	public static final RegistryObject<Block> COBBLESNOW = REGISTRY.register("cobblesnow", () -> new CobblesnowBlock());
	public static final RegistryObject<Block> FROSTICE = REGISTRY.register("frostice", () -> new FrosticeBlock());
	public static final RegistryObject<Block> COLD_GRASS = REGISTRY.register("cold_grass", () -> new ColdGrassBlock());
	public static final RegistryObject<Block> FROSTY_WOOD = REGISTRY.register("frosty_wood", () -> new FrostyWoodBlock());
	public static final RegistryObject<Block> FROSTY_LOG = REGISTRY.register("frosty_log", () -> new FrostyLogBlock());
	public static final RegistryObject<Block> FROSTY_PLANKS = REGISTRY.register("frosty_planks", () -> new FrostyPlanksBlock());
	public static final RegistryObject<Block> FROSTY_LEAVES = REGISTRY.register("frosty_leaves", () -> new FrostyLeavesBlock());
	public static final RegistryObject<Block> FROSTY_STAIRS = REGISTRY.register("frosty_stairs", () -> new FrostyStairsBlock());
	public static final RegistryObject<Block> FROSTY_SLAB = REGISTRY.register("frosty_slab", () -> new FrostySlabBlock());
	public static final RegistryObject<Block> FROSTY_FENCE = REGISTRY.register("frosty_fence", () -> new FrostyFenceBlock());
	public static final RegistryObject<Block> FROSTY_FENCE_GATE = REGISTRY.register("frosty_fence_gate", () -> new FrostyFenceGateBlock());
	public static final RegistryObject<Block> FROSTY_PRESSURE_PLATE = REGISTRY.register("frosty_pressure_plate", () -> new FrostyPressurePlateBlock());
	public static final RegistryObject<Block> FROSTY_BUTTON = REGISTRY.register("frosty_button", () -> new FrostyButtonBlock());
	public static final RegistryObject<Block> STEVUM_ORE = REGISTRY.register("stevum_ore", () -> new StevumOreBlock());
	public static final RegistryObject<Block> STEVUM_BLOCK = REGISTRY.register("stevum_block", () -> new StevumBlockBlock());
	public static final RegistryObject<Block> APPLEVINE = REGISTRY.register("applevine", () -> new ApplevineBlock());
	public static final RegistryObject<Block> FROSTY_SAPLING = REGISTRY.register("frosty_sapling", () -> new FrostySaplingBlock());
	public static final RegistryObject<Block> MAGICITE_CLUMP = REGISTRY.register("magicite_clump", () -> new MagiciteClumpBlock());
	public static final RegistryObject<Block> COLDSTEEL_ORE = REGISTRY.register("coldsteel_ore", () -> new ColdsteelOreBlock());
	public static final RegistryObject<Block> COLDSTEEL_BLOCK = REGISTRY.register("coldsteel_block", () -> new ColdsteelBlockBlock());
	public static final RegistryObject<Block> FROZEN_FORGE = REGISTRY.register("frozen_forge", () -> new FrozenForgeBlock());
	public static final RegistryObject<Block> ICICLE = REGISTRY.register("icicle", () -> new IcicleBlock());
	public static final RegistryObject<Block> SMOOTH_SNAPSTONE = REGISTRY.register("smooth_snapstone", () -> new SmoothSnapstoneBlock());
	public static final RegistryObject<Block> SNAPSTONE_SLAB = REGISTRY.register("snapstone_slab", () -> new SnapstoneSlabBlock());
	public static final RegistryObject<Block> UNTOUCHED_SOIL = REGISTRY.register("untouched_soil", () -> new UntouchedSoilBlock());
	public static final RegistryObject<Block> DEAD_GRASS = REGISTRY.register("dead_grass", () -> new DeadGrassBlock());
	public static final RegistryObject<Block> IRRADIATED_COBBLESTONE = REGISTRY.register("irradiated_cobblestone", () -> new IrradiatedCobblestoneBlock());
	public static final RegistryObject<Block> IRRADIATED_STONE = REGISTRY.register("irradiated_stone", () -> new IrradiatedStoneBlock());
	public static final RegistryObject<Block> DEADIRON_ORE = REGISTRY.register("deadiron_ore", () -> new DeadironOreBlock());
	public static final RegistryObject<Block> DEADIRON_BLOCK = REGISTRY.register("deadiron_block", () -> new DeadironBlockBlock());
	public static final RegistryObject<Block> IRRADIATED_STONE_SLAB = REGISTRY.register("irradiated_stone_slab", () -> new IrradiatedStoneSlabBlock());
	public static final RegistryObject<Block> DEAD_WOOD = REGISTRY.register("dead_wood", () -> new DeadWoodBlock());
	public static final RegistryObject<Block> DEAD_LOG = REGISTRY.register("dead_log", () -> new DeadLogBlock());
	public static final RegistryObject<Block> DEAD_PLANKS = REGISTRY.register("dead_planks", () -> new DeadPlanksBlock());
	public static final RegistryObject<Block> DEAD_STAIRS = REGISTRY.register("dead_stairs", () -> new DeadStairsBlock());
	public static final RegistryObject<Block> DEAD_SLAB = REGISTRY.register("dead_slab", () -> new DeadSlabBlock());
	public static final RegistryObject<Block> DEAD_FENCE = REGISTRY.register("dead_fence", () -> new DeadFenceBlock());
	public static final RegistryObject<Block> DEAD_FENCE_GATE = REGISTRY.register("dead_fence_gate", () -> new DeadFenceGateBlock());
	public static final RegistryObject<Block> DEAD_PRESSURE_PLATE = REGISTRY.register("dead_pressure_plate", () -> new DeadPressurePlateBlock());
	public static final RegistryObject<Block> DEAD_BUTTON = REGISTRY.register("dead_button", () -> new DeadButtonBlock());
	public static final RegistryObject<Block> SMOOTH_IRRADIATED_STONE = REGISTRY.register("smooth_irradiated_stone", () -> new SmoothIrradiatedStoneBlock());
	public static final RegistryObject<Block> DOOMSAND = REGISTRY.register("doomsand", () -> new DoomsandBlock());
	public static final RegistryObject<Block> DOOMGLASS = REGISTRY.register("doomglass", () -> new DoomglassBlock());
	public static final RegistryObject<Block> IRRADIATED_WATER = REGISTRY.register("irradiated_water", () -> new IrradiatedWaterBlock());
	public static final RegistryObject<Block> ASH = REGISTRY.register("ash", () -> new AshBlock());
	public static final RegistryObject<Block> MILITARIA_PORTAL = REGISTRY.register("militaria_portal", () -> new MilitariaPortalBlock());
	public static final RegistryObject<Block> URANIUM_ORE = REGISTRY.register("uranium_ore", () -> new UraniumOreBlock());
	public static final RegistryObject<Block> URANIUM_BLOCK = REGISTRY.register("uranium_block", () -> new UraniumBlockBlock());
	public static final RegistryObject<Block> GOLD_ROCKS = REGISTRY.register("gold_rocks", () -> new GoldRocksBlock());
	public static final RegistryObject<Block> IMPURE_COPPER = REGISTRY.register("impure_copper", () -> new ImpureCopperBlock());
	public static final RegistryObject<Block> BLOCK_OF_SCRAP = REGISTRY.register("block_of_scrap", () -> new BlockOfScrapBlock());
	public static final RegistryObject<Block> DEADIRON_CASING = REGISTRY.register("deadiron_casing", () -> new DeadironCasingBlock());
	public static final RegistryObject<Block> PURIFIER_MK_2 = REGISTRY.register("purifier_mk_2", () -> new PurifierMK2Block());
	public static final RegistryObject<Block> DOOMFORGE_ACCESS_POINT = REGISTRY.register("doomforge_access_point", () -> new DoomforgeAccessPointBlock());
	public static final RegistryObject<Block> RADIATION_REMOVAL_PLANT_ACCESS_POINT = REGISTRY.register("radiation_removal_plant_access_point", () -> new RadiationRemovalPlantAccessPointBlock());
	public static final RegistryObject<Block> SURVIVORS_MARKET = REGISTRY.register("survivors_market", () -> new SurvivorsMarketBlock());
	public static final RegistryObject<Block> MANUFACTURING_PLANT_ACCESS_POINT = REGISTRY.register("manufacturing_plant_access_point", () -> new ManufacturingPlantAccessPointBlock());
	public static final RegistryObject<Block> COFFIN = REGISTRY.register("coffin", () -> new CoffinBlock());
	public static final RegistryObject<Block> MAGICAL_CASING = REGISTRY.register("magical_casing", () -> new MagicalCasingBlock());
	public static final RegistryObject<Block> SOUL_MANIPULATOR_ACCESS_POINT = REGISTRY.register("soul_manipulator_access_point", () -> new SoulManipulatorAccessPointBlock());
	public static final RegistryObject<Block> RITUAL_STONE = REGISTRY.register("ritual_stone", () -> new RitualStoneBlock());
	public static final RegistryObject<Block> DESIGNER_ACCESS_POINT = REGISTRY.register("designer_access_point", () -> new DesignerAccessPointBlock());
	public static final RegistryObject<Block> ITEM_RESEACHER_ACCESS_POINT = REGISTRY.register("item_reseacher_access_point", () -> new ItemReseacherAccessPointBlock());
	public static final RegistryObject<Block> CONCRETE_MIXER = REGISTRY.register("concrete_mixer", () -> new ConcreteMixerBlock());
	public static final RegistryObject<Block> URANIUM_HYDROPONICS = REGISTRY.register("uranium_hydroponics", () -> new UraniumHydroponicsBlock());
	public static final RegistryObject<Block> URANIUM_HYDROPONICS_UTILITY_HATCH = REGISTRY.register("uranium_hydroponics_utility_hatch", () -> new UraniumHydroponicsUtilityHatchBlock());
	public static final RegistryObject<Block> REPAIR_PLANT = REGISTRY.register("repair_plant", () -> new RepairPlantBlock());
	public static final RegistryObject<Block> WARP_BRICK = REGISTRY.register("warp_brick", () -> new WarpBrickBlock());
	public static final RegistryObject<Block> TARDIS_WINDOWS = REGISTRY.register("tardis_windows", () -> new TARDISWindowsBlock());
	public static final RegistryObject<Block> TARDIS_PLATING = REGISTRY.register("tardis_plating", () -> new TARDISPlatingBlock());
	public static final RegistryObject<Block> TARDIS_PHONE = REGISTRY.register("tardis_phone", () -> new TARDISPhoneBlock());
	public static final RegistryObject<Block> TARDIS_HANDLE = REGISTRY.register("tardis_handle", () -> new TARDISHandleBlock());
	public static final RegistryObject<Block> TARDIS_TOP_TEXT = REGISTRY.register("tardis_top_text", () -> new TARDISTopTextBlock());
	public static final RegistryObject<Block> URANIUM_CASING = REGISTRY.register("uranium_casing", () -> new UraniumCasingBlock());
	public static final RegistryObject<Block> URANIUM_PROCESSING_PLANT = REGISTRY.register("uranium_processing_plant", () -> new UraniumProcessingPlantBlock());
	public static final RegistryObject<Block> KITCHEN = REGISTRY.register("kitchen", () -> new KitchenBlock());
	public static final RegistryObject<Block> CELL = REGISTRY.register("cell", () -> new CellBlock());
	public static final RegistryObject<Block> IMPROVED_CELL = REGISTRY.register("improved_cell", () -> new ImprovedCellBlock());
	public static final RegistryObject<Block> CELL_CASING = REGISTRY.register("cell_casing", () -> new CellCasingBlock());
	public static final RegistryObject<Block> HYPERCELL = REGISTRY.register("hypercell", () -> new HypercellBlock());
	public static final RegistryObject<Block> FIREWOOD_WOOD = REGISTRY.register("firewood_wood", () -> new FirewoodWoodBlock());
	public static final RegistryObject<Block> FIREWOOD_LOG = REGISTRY.register("firewood_log", () -> new FirewoodLogBlock());
	public static final RegistryObject<Block> FIREWOOD_PLANKS = REGISTRY.register("firewood_planks", () -> new FirewoodPlanksBlock());
	public static final RegistryObject<Block> FIREWOOD_LEAVES = REGISTRY.register("firewood_leaves", () -> new FirewoodLeavesBlock());
	public static final RegistryObject<Block> FIREWOOD_STAIRS = REGISTRY.register("firewood_stairs", () -> new FirewoodStairsBlock());
	public static final RegistryObject<Block> FIREWOOD_SLAB = REGISTRY.register("firewood_slab", () -> new FirewoodSlabBlock());
	public static final RegistryObject<Block> FIREWOOD_FENCE = REGISTRY.register("firewood_fence", () -> new FirewoodFenceBlock());
	public static final RegistryObject<Block> FIREWOOD_FENCE_GATE = REGISTRY.register("firewood_fence_gate", () -> new FirewoodFenceGateBlock());
	public static final RegistryObject<Block> FIREWOOD_PRESSURE_PLATE = REGISTRY.register("firewood_pressure_plate", () -> new FirewoodPressurePlateBlock());
	public static final RegistryObject<Block> FIREWOOD_BUTTON = REGISTRY.register("firewood_button", () -> new FirewoodButtonBlock());
	public static final RegistryObject<Block> FIREWOOD_SAPLING = REGISTRY.register("firewood_sapling", () -> new FirewoodSaplingBlock());
	public static final RegistryObject<Block> ICEDAISY = REGISTRY.register("icedaisy", () -> new IcedaisyBlock());
	public static final RegistryObject<Block> FROZEN_GRASS = REGISTRY.register("frozen_grass", () -> new FrozenGrassBlock());
	public static final RegistryObject<Block> ICEFLAME = REGISTRY.register("iceflame", () -> new IceflameBlock());
	public static final RegistryObject<Block> FIRELILY = REGISTRY.register("firelily", () -> new FirelilyBlock());
	public static final RegistryObject<Block> SIGMARI = REGISTRY.register("sigmari", () -> new SigmariBlock());
	public static final RegistryObject<Block> POINK = REGISTRY.register("poink", () -> new PoinkBlock());
	public static final RegistryObject<Block> ICEMITE = REGISTRY.register("icemite", () -> new IcemiteBlock());
	public static final RegistryObject<Block> SNOWROCK = REGISTRY.register("snowrock", () -> new SnowrockBlock());
	public static final RegistryObject<Block> SPOR = REGISTRY.register("spor", () -> new SporBlock());
	public static final RegistryObject<Block> CORPSEROCK = REGISTRY.register("corpserock", () -> new CorpserockBlock());
	public static final RegistryObject<Block> DEAD_PLANTS = REGISTRY.register("dead_plants", () -> new DeadPlantsBlock());
	public static final RegistryObject<Block> RADIOACTIVE_ROYAL = REGISTRY.register("radioactive_royal", () -> new RadioactiveRoyalBlock());
	public static final RegistryObject<Block> DEAD_FLOWER = REGISTRY.register("dead_flower", () -> new DeadFlowerBlock());
	public static final RegistryObject<Block> ZOMBIE_CHOMP = REGISTRY.register("zombie_chomp", () -> new ZombieChompBlock());
	public static final RegistryObject<Block> SWARM = REGISTRY.register("swarm", () -> new SwarmBlock());
	public static final RegistryObject<Block> MEMORY_FLOWER = REGISTRY.register("memory_flower", () -> new MemoryFlowerBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
