
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.stmwr.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.extensions.IForgeMenuType;

import net.minecraft.world.inventory.MenuType;

import net.mcreator.stmwr.world.inventory.WizardsSeaRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemFusionStationGUIMenu;
import net.mcreator.stmwr.world.inventory.TortillaRecipeMenu;
import net.mcreator.stmwr.world.inventory.ToolsAndArmorMenu;
import net.mcreator.stmwr.world.inventory.TacoShellRecipeMenu;
import net.mcreator.stmwr.world.inventory.TacoRecipeMenu;
import net.mcreator.stmwr.world.inventory.StorageCubeGUIMenu;
import net.mcreator.stmwr.world.inventory.StopstoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.SpellsP1Menu;
import net.mcreator.stmwr.world.inventory.SpellforgeGUIMenu;
import net.mcreator.stmwr.world.inventory.SpeedstoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.SausageRecipeMenu;
import net.mcreator.stmwr.world.inventory.PotatoChipsRecipeMenu;
import net.mcreator.stmwr.world.inventory.PizzaSliceRecipeMenu;
import net.mcreator.stmwr.world.inventory.PizzaRecipeMenu;
import net.mcreator.stmwr.world.inventory.PepperoniRecipeMenu;
import net.mcreator.stmwr.world.inventory.OrePurifierGUIMenu;
import net.mcreator.stmwr.world.inventory.MagiciansWorkbenchGUIMenu;
import net.mcreator.stmwr.world.inventory.KitchenGUIMenu;
import net.mcreator.stmwr.world.inventory.HomePageMenu;
import net.mcreator.stmwr.world.inventory.GroundBeefRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumSwordRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumShovelRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumPickaxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumHoeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumHelmetRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumGearRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumChestplateRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumAxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.ForgeGUIMenu;
import net.mcreator.stmwr.world.inventory.FlamingStorageCubeRecipeMenu;
import net.mcreator.stmwr.world.inventory.FlamingStorageCubeGUIMenu;
import net.mcreator.stmwr.world.inventory.DupestoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.CookBookHomePageMenu;
import net.mcreator.stmwr.world.inventory.CodexHomePageMenu;
import net.mcreator.stmwr.world.inventory.ChocolateRecipeMenu;
import net.mcreator.stmwr.world.inventory.ChickenNuggetRecipeMenu;
import net.mcreator.stmwr.world.inventory.CheeseStickRecipeMenu;
import net.mcreator.stmwr.world.inventory.CategoriesMenu;
import net.mcreator.stmwr.world.inventory.BlocksPageMenu;
import net.mcreator.stmwr.world.inventory.BlazingPlasticRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedSwordRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedShovelRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedPickaxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedHoeRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedHelmetRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedGearRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedChestplateRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedAxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.AlloyFuseGUIMenu;
import net.mcreator.stmwr.world.inventory.AlligatorKnifeRecipeMenu;
import net.mcreator.stmwr.world.inventory.AOTTotemsP1Menu;
import net.mcreator.stmwr.world.inventory.AOTHomePageMenu;
import net.mcreator.stmwr.StmwrMod;

public class StmwrModMenus {
	public static final DeferredRegister<MenuType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.MENU_TYPES, StmwrMod.MODID);
	public static final RegistryObject<MenuType<KitchenGUIMenu>> KITCHEN_GUI = REGISTRY.register("kitchen_gui", () -> IForgeMenuType.create(KitchenGUIMenu::new));
	public static final RegistryObject<MenuType<CookBookHomePageMenu>> COOK_BOOK_HOME_PAGE = REGISTRY.register("cook_book_home_page", () -> IForgeMenuType.create(CookBookHomePageMenu::new));
	public static final RegistryObject<MenuType<ChickenNuggetRecipeMenu>> CHICKEN_NUGGET_RECIPE = REGISTRY.register("chicken_nugget_recipe", () -> IForgeMenuType.create(ChickenNuggetRecipeMenu::new));
	public static final RegistryObject<MenuType<PotatoChipsRecipeMenu>> POTATO_CHIPS_RECIPE = REGISTRY.register("potato_chips_recipe", () -> IForgeMenuType.create(PotatoChipsRecipeMenu::new));
	public static final RegistryObject<MenuType<TacoRecipeMenu>> TACO_RECIPE = REGISTRY.register("taco_recipe", () -> IForgeMenuType.create(TacoRecipeMenu::new));
	public static final RegistryObject<MenuType<TacoShellRecipeMenu>> TACO_SHELL_RECIPE = REGISTRY.register("taco_shell_recipe", () -> IForgeMenuType.create(TacoShellRecipeMenu::new));
	public static final RegistryObject<MenuType<ChocolateRecipeMenu>> CHOCOLATE_RECIPE = REGISTRY.register("chocolate_recipe", () -> IForgeMenuType.create(ChocolateRecipeMenu::new));
	public static final RegistryObject<MenuType<SausageRecipeMenu>> SAUSAGE_RECIPE = REGISTRY.register("sausage_recipe", () -> IForgeMenuType.create(SausageRecipeMenu::new));
	public static final RegistryObject<MenuType<GroundBeefRecipeMenu>> GROUND_BEEF_RECIPE = REGISTRY.register("ground_beef_recipe", () -> IForgeMenuType.create(GroundBeefRecipeMenu::new));
	public static final RegistryObject<MenuType<PizzaSliceRecipeMenu>> PIZZA_SLICE_RECIPE = REGISTRY.register("pizza_slice_recipe", () -> IForgeMenuType.create(PizzaSliceRecipeMenu::new));
	public static final RegistryObject<MenuType<TortillaRecipeMenu>> TORTILLA_RECIPE = REGISTRY.register("tortilla_recipe", () -> IForgeMenuType.create(TortillaRecipeMenu::new));
	public static final RegistryObject<MenuType<PizzaRecipeMenu>> PIZZA_RECIPE = REGISTRY.register("pizza_recipe", () -> IForgeMenuType.create(PizzaRecipeMenu::new));
	public static final RegistryObject<MenuType<PepperoniRecipeMenu>> PEPPERONI_RECIPE = REGISTRY.register("pepperoni_recipe", () -> IForgeMenuType.create(PepperoniRecipeMenu::new));
	public static final RegistryObject<MenuType<CheeseStickRecipeMenu>> CHEESE_STICK_RECIPE = REGISTRY.register("cheese_stick_recipe", () -> IForgeMenuType.create(CheeseStickRecipeMenu::new));
	public static final RegistryObject<MenuType<MagiciansWorkbenchGUIMenu>> MAGICIANS_WORKBENCH_GUI = REGISTRY.register("magicians_workbench_gui", () -> IForgeMenuType.create(MagiciansWorkbenchGUIMenu::new));
	public static final RegistryObject<MenuType<StorageCubeGUIMenu>> STORAGE_CUBE_GUI = REGISTRY.register("storage_cube_gui", () -> IForgeMenuType.create(StorageCubeGUIMenu::new));
	public static final RegistryObject<MenuType<ForgeGUIMenu>> FORGE_GUI = REGISTRY.register("forge_gui", () -> IForgeMenuType.create(ForgeGUIMenu::new));
	public static final RegistryObject<MenuType<HomePageMenu>> HOME_PAGE = REGISTRY.register("home_page", () -> IForgeMenuType.create(HomePageMenu::new));
	public static final RegistryObject<MenuType<CategoriesMenu>> CATEGORIES = REGISTRY.register("categories", () -> IForgeMenuType.create(CategoriesMenu::new));
	public static final RegistryObject<MenuType<ToolsAndArmorMenu>> TOOLS_AND_ARMOR = REGISTRY.register("tools_and_armor", () -> IForgeMenuType.create(ToolsAndArmorMenu::new));
	public static final RegistryObject<MenuType<BlocksPageMenu>> BLOCKS_PAGE = REGISTRY.register("blocks_page", () -> IForgeMenuType.create(BlocksPageMenu::new));
	public static final RegistryObject<MenuType<AlligatorKnifeRecipeMenu>> ALLIGATOR_KNIFE_RECIPE = REGISTRY.register("alligator_knife_recipe", () -> IForgeMenuType.create(AlligatorKnifeRecipeMenu::new));
	public static final RegistryObject<MenuType<SpellforgeGUIMenu>> SPELLFORGE_GUI = REGISTRY.register("spellforge_gui", () -> IForgeMenuType.create(SpellforgeGUIMenu::new));
	public static final RegistryObject<MenuType<CodexHomePageMenu>> CODEX_HOME_PAGE = REGISTRY.register("codex_home_page", () -> IForgeMenuType.create(CodexHomePageMenu::new));
	public static final RegistryObject<MenuType<SpellsP1Menu>> SPELLS_P_1 = REGISTRY.register("spells_p_1", () -> IForgeMenuType.create(SpellsP1Menu::new));
	public static final RegistryObject<MenuType<WizardsSeaRecipeMenu>> WIZARDS_SEA_RECIPE = REGISTRY.register("wizards_sea_recipe", () -> IForgeMenuType.create(WizardsSeaRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedGearRecipeMenu>> BLAZED_GEAR_RECIPE = REGISTRY.register("blazed_gear_recipe", () -> IForgeMenuType.create(BlazedGearRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedHelmetRecipeMenu>> BLAZED_HELMET_RECIPE = REGISTRY.register("blazed_helmet_recipe", () -> IForgeMenuType.create(BlazedHelmetRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedChestplateRecipeMenu>> BLAZED_CHESTPLATE_RECIPE = REGISTRY.register("blazed_chestplate_recipe", () -> IForgeMenuType.create(BlazedChestplateRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedLeggingsRecipeMenu>> BLAZED_LEGGINGS_RECIPE = REGISTRY.register("blazed_leggings_recipe", () -> IForgeMenuType.create(BlazedLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedBootsRecipeMenu>> BLAZED_BOOTS_RECIPE = REGISTRY.register("blazed_boots_recipe", () -> IForgeMenuType.create(BlazedBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedSwordRecipeMenu>> BLAZED_SWORD_RECIPE = REGISTRY.register("blazed_sword_recipe", () -> IForgeMenuType.create(BlazedSwordRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedAxeRecipeMenu>> BLAZED_AXE_RECIPE = REGISTRY.register("blazed_axe_recipe", () -> IForgeMenuType.create(BlazedAxeRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedPickaxeRecipeMenu>> BLAZED_PICKAXE_RECIPE = REGISTRY.register("blazed_pickaxe_recipe", () -> IForgeMenuType.create(BlazedPickaxeRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedShovelRecipeMenu>> BLAZED_SHOVEL_RECIPE = REGISTRY.register("blazed_shovel_recipe", () -> IForgeMenuType.create(BlazedShovelRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedHoeRecipeMenu>> BLAZED_HOE_RECIPE = REGISTRY.register("blazed_hoe_recipe", () -> IForgeMenuType.create(BlazedHoeRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazingPlasticRecipeMenu>> BLAZING_PLASTIC_RECIPE = REGISTRY.register("blazing_plastic_recipe", () -> IForgeMenuType.create(BlazingPlasticRecipeMenu::new));
	public static final RegistryObject<MenuType<FlamingStorageCubeGUIMenu>> FLAMING_STORAGE_CUBE_GUI = REGISTRY.register("flaming_storage_cube_gui", () -> IForgeMenuType.create(FlamingStorageCubeGUIMenu::new));
	public static final RegistryObject<MenuType<FlamingStorageCubeRecipeMenu>> FLAMING_STORAGE_CUBE_RECIPE = REGISTRY.register("flaming_storage_cube_recipe", () -> IForgeMenuType.create(FlamingStorageCubeRecipeMenu::new));
	public static final RegistryObject<MenuType<OrePurifierGUIMenu>> ORE_PURIFIER_GUI = REGISTRY.register("ore_purifier_gui", () -> IForgeMenuType.create(OrePurifierGUIMenu::new));
	public static final RegistryObject<MenuType<GodliumGearRecipeMenu>> GODLIUM_GEAR_RECIPE = REGISTRY.register("godlium_gear_recipe", () -> IForgeMenuType.create(GodliumGearRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumHelmetRecipeMenu>> GODLIUM_HELMET_RECIPE = REGISTRY.register("godlium_helmet_recipe", () -> IForgeMenuType.create(GodliumHelmetRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumChestplateRecipeMenu>> GODLIUM_CHESTPLATE_RECIPE = REGISTRY.register("godlium_chestplate_recipe", () -> IForgeMenuType.create(GodliumChestplateRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumLeggingsRecipeMenu>> GODLIUM_LEGGINGS_RECIPE = REGISTRY.register("godlium_leggings_recipe", () -> IForgeMenuType.create(GodliumLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumBootsRecipeMenu>> GODLIUM_BOOTS_RECIPE = REGISTRY.register("godlium_boots_recipe", () -> IForgeMenuType.create(GodliumBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumSwordRecipeMenu>> GODLIUM_SWORD_RECIPE = REGISTRY.register("godlium_sword_recipe", () -> IForgeMenuType.create(GodliumSwordRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumPickaxeRecipeMenu>> GODLIUM_PICKAXE_RECIPE = REGISTRY.register("godlium_pickaxe_recipe", () -> IForgeMenuType.create(GodliumPickaxeRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumAxeRecipeMenu>> GODLIUM_AXE_RECIPE = REGISTRY.register("godlium_axe_recipe", () -> IForgeMenuType.create(GodliumAxeRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumShovelRecipeMenu>> GODLIUM_SHOVEL_RECIPE = REGISTRY.register("godlium_shovel_recipe", () -> IForgeMenuType.create(GodliumShovelRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumHoeRecipeMenu>> GODLIUM_HOE_RECIPE = REGISTRY.register("godlium_hoe_recipe", () -> IForgeMenuType.create(GodliumHoeRecipeMenu::new));
	public static final RegistryObject<MenuType<StopstoneRecipeMenu>> STOPSTONE_RECIPE = REGISTRY.register("stopstone_recipe", () -> IForgeMenuType.create(StopstoneRecipeMenu::new));
	public static final RegistryObject<MenuType<SpeedstoneRecipeMenu>> SPEEDSTONE_RECIPE = REGISTRY.register("speedstone_recipe", () -> IForgeMenuType.create(SpeedstoneRecipeMenu::new));
	public static final RegistryObject<MenuType<DupestoneRecipeMenu>> DUPESTONE_RECIPE = REGISTRY.register("dupestone_recipe", () -> IForgeMenuType.create(DupestoneRecipeMenu::new));
	public static final RegistryObject<MenuType<AlloyFuseGUIMenu>> ALLOY_FUSE_GUI = REGISTRY.register("alloy_fuse_gui", () -> IForgeMenuType.create(AlloyFuseGUIMenu::new));
	public static final RegistryObject<MenuType<TotemFusionStationGUIMenu>> TOTEM_FUSION_STATION_GUI = REGISTRY.register("totem_fusion_station_gui", () -> IForgeMenuType.create(TotemFusionStationGUIMenu::new));
	public static final RegistryObject<MenuType<AOTHomePageMenu>> AOT_HOME_PAGE = REGISTRY.register("aot_home_page", () -> IForgeMenuType.create(AOTHomePageMenu::new));
	public static final RegistryObject<MenuType<AOTTotemsP1Menu>> AOT_TOTEMS_P_1 = REGISTRY.register("aot_totems_p_1", () -> IForgeMenuType.create(AOTTotemsP1Menu::new));
}
