
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.stmwr.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.extensions.IForgeMenuType;

import net.minecraft.world.inventory.MenuType;

import net.mcreator.stmwr.world.inventory.WizardsSeaRecipeMenu;
import net.mcreator.stmwr.world.inventory.WarpBrickRecipeMenu;
import net.mcreator.stmwr.world.inventory.VortexManipulatorRecipeMenu;
import net.mcreator.stmwr.world.inventory.UraniumProcessingPlantMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.UraniumProcessingPlantGUIMenu;
import net.mcreator.stmwr.world.inventory.UraniumHydroponicsUtilityHatchRecipeMenu;
import net.mcreator.stmwr.world.inventory.UraniumHydroponicsRecipeMenu;
import net.mcreator.stmwr.world.inventory.UraniumHydroponicsMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.UraniumHydroponicsGUIMenu;
import net.mcreator.stmwr.world.inventory.UraniumFuelRodRecipeMenu;
import net.mcreator.stmwr.world.inventory.TrialBricksRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfWaterBreathingRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfTheCowRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfStrengthRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfStrengthIIRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfSpeedRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfSpeedIIRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfRegenerationRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfRegenerationIIRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfNightVisionRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfLevitationRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfJumpBoostRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfJumpBoostIIRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfHealthBoostRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfHealthBoostIIRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfHasteRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfHasteIIRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfGamblingRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfFireResistanceRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfDolphinsGraceRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemFusionStationGUIMenu;
import net.mcreator.stmwr.world.inventory.TortillaRecipeMenu;
import net.mcreator.stmwr.world.inventory.ToolsAndArmorMenu;
import net.mcreator.stmwr.world.inventory.TacoShellRecipeMenu;
import net.mcreator.stmwr.world.inventory.TacoRecipeMenu;
import net.mcreator.stmwr.world.inventory.TARDISMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.StorageCubeGUIMenu;
import net.mcreator.stmwr.world.inventory.StopstoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.SpringsRecipeMenu;
import net.mcreator.stmwr.world.inventory.SpellsP1Menu;
import net.mcreator.stmwr.world.inventory.SpellforgeGUIMenu;
import net.mcreator.stmwr.world.inventory.SpeedstoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.SoulShardRecipeMenu;
import net.mcreator.stmwr.world.inventory.SoulManipulatorMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.SoulManipulatorGUIMenu;
import net.mcreator.stmwr.world.inventory.SnowyShrapnelRecipeMenu;
import net.mcreator.stmwr.world.inventory.SmallStoragePackGUIMenu;
import net.mcreator.stmwr.world.inventory.SausageRecipeMenu;
import net.mcreator.stmwr.world.inventory.RodsRecipeMenu;
import net.mcreator.stmwr.world.inventory.RitualStoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.RitualStoneGUIMenu;
import net.mcreator.stmwr.world.inventory.RitualCircleMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.RepairPlantRecipeMenu;
import net.mcreator.stmwr.world.inventory.RepairPlantGUIMenu;
import net.mcreator.stmwr.world.inventory.ReinforcedArmsRecipeMenu;
import net.mcreator.stmwr.world.inventory.RadiationRemovalPlantMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.RadiationRemovalPlantGUIMenu;
import net.mcreator.stmwr.world.inventory.PurifierMK2GUIMenu;
import net.mcreator.stmwr.world.inventory.PoweredLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.PowercellRecipeMenu;
import net.mcreator.stmwr.world.inventory.PotatoChipsRecipeMenu;
import net.mcreator.stmwr.world.inventory.PortableOvenRecipeMenu;
import net.mcreator.stmwr.world.inventory.PortableCrucibleRecipeMenu;
import net.mcreator.stmwr.world.inventory.PlatesRecipeMenu;
import net.mcreator.stmwr.world.inventory.PizzaSliceRecipeMenu;
import net.mcreator.stmwr.world.inventory.PizzaRecipeMenu;
import net.mcreator.stmwr.world.inventory.PepperoniRecipeMenu;
import net.mcreator.stmwr.world.inventory.OrePurifierGUIMenu;
import net.mcreator.stmwr.world.inventory.NightVisionGogglesRecipeMenu;
import net.mcreator.stmwr.world.inventory.NailsRecipeMenu;
import net.mcreator.stmwr.world.inventory.ModularLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.ModularHelmetRecipeMenu;
import net.mcreator.stmwr.world.inventory.ModularGearRecipesMenu;
import net.mcreator.stmwr.world.inventory.ModularChestplateRecipeMenu;
import net.mcreator.stmwr.world.inventory.ModularBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.ManupediaRecipesMenu;
import net.mcreator.stmwr.world.inventory.ManupediaHomeMenu;
import net.mcreator.stmwr.world.inventory.ManufacturingPlantMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.ManufacturingPlantGUIMenu;
import net.mcreator.stmwr.world.inventory.MagiciansWorkbenchGUIMenu;
import net.mcreator.stmwr.world.inventory.MMMultiblocksP1Menu;
import net.mcreator.stmwr.world.inventory.MMHomePageMenu;
import net.mcreator.stmwr.world.inventory.LongFallBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.LightningStaffRecipeMenu;
import net.mcreator.stmwr.world.inventory.LaboratoryMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.KitchenGUIMenu;
import net.mcreator.stmwr.world.inventory.KeyAnvilGUIMenu;
import net.mcreator.stmwr.world.inventory.ItemsPageMenu;
import net.mcreator.stmwr.world.inventory.ItemResearcherGUIMenu;
import net.mcreator.stmwr.world.inventory.HomePageMenu;
import net.mcreator.stmwr.world.inventory.HODTheWitherMenu;
import net.mcreator.stmwr.world.inventory.HODTheTimelessMenu;
import net.mcreator.stmwr.world.inventory.HODSteveCowMenu;
import net.mcreator.stmwr.world.inventory.HODSteveCowLandMenu;
import net.mcreator.stmwr.world.inventory.HODPikachuMenu;
import net.mcreator.stmwr.world.inventory.HODOverworldMenu;
import net.mcreator.stmwr.world.inventory.HODMilitariaMenu;
import net.mcreator.stmwr.world.inventory.HODLightningWizardMenu;
import net.mcreator.stmwr.world.inventory.HODLightningCultistMenu;
import net.mcreator.stmwr.world.inventory.HODLesserWizardMenu;
import net.mcreator.stmwr.world.inventory.HODIrradiatedPigMenu;
import net.mcreator.stmwr.world.inventory.HODIrradiatedCowMenu;
import net.mcreator.stmwr.world.inventory.HODIrradiatedChickenMenu;
import net.mcreator.stmwr.world.inventory.HODHomePageMenu;
import net.mcreator.stmwr.world.inventory.HODGoolingMenu;
import net.mcreator.stmwr.world.inventory.HODGiantSteveCowMenu;
import net.mcreator.stmwr.world.inventory.HODFrombieMenu;
import net.mcreator.stmwr.world.inventory.HODCrusherMenu;
import net.mcreator.stmwr.world.inventory.HODCategoriesMenu;
import net.mcreator.stmwr.world.inventory.HODAncientWizardMenu;
import net.mcreator.stmwr.world.inventory.GroundBeefRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodlyStorageCubeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodlyStorageCubeGUIMenu;
import net.mcreator.stmwr.world.inventory.GodliumSwordRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumShovelRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumPickaxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumKnifeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumHoeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumHelmetRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumGearRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumChestplateRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumAxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.FrozenForgeGUIMenu;
import net.mcreator.stmwr.world.inventory.FrostwatchRecipeMenu;
import net.mcreator.stmwr.world.inventory.ForgeGUIMenu;
import net.mcreator.stmwr.world.inventory.FlamingStorageCubeRecipeMenu;
import net.mcreator.stmwr.world.inventory.FlamingStorageCubeGUIMenu;
import net.mcreator.stmwr.world.inventory.EyeOfTimeRecipeMenu;
import net.mcreator.stmwr.world.inventory.EyeOfTheSteveCowRecipeMenu;
import net.mcreator.stmwr.world.inventory.DupestoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.DoomforgeMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.DoomforgeGUIMenu;
import net.mcreator.stmwr.world.inventory.DesignerGUIMenu;
import net.mcreator.stmwr.world.inventory.CreationOrbRecipeMenu;
import net.mcreator.stmwr.world.inventory.CookBookHomePageMenu;
import net.mcreator.stmwr.world.inventory.ConsumerGUIMenu;
import net.mcreator.stmwr.world.inventory.ConcreteMixerRecipeMenu;
import net.mcreator.stmwr.world.inventory.ConcreteMixerMultiblockRecipeMenu;
import net.mcreator.stmwr.world.inventory.ConcreteMixerGUIMenu;
import net.mcreator.stmwr.world.inventory.CompressorGUIMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelSwordRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelShovelRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelPickaxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelHoeRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelHelmetRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelGearRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelChestplateRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelAxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.CogsRecipeMenu;
import net.mcreator.stmwr.world.inventory.CodexHomePageMenu;
import net.mcreator.stmwr.world.inventory.ChocolateRecipeMenu;
import net.mcreator.stmwr.world.inventory.ChickenNuggetRecipeMenu;
import net.mcreator.stmwr.world.inventory.ChickenGunRecipeMenu;
import net.mcreator.stmwr.world.inventory.CheeseStickRecipeMenu;
import net.mcreator.stmwr.world.inventory.CategoriesMenu;
import net.mcreator.stmwr.world.inventory.BubbleRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlueprintBookP1Menu;
import net.mcreator.stmwr.world.inventory.BlueprintBookHomePageMenu;
import net.mcreator.stmwr.world.inventory.BlocksPageMenu;
import net.mcreator.stmwr.world.inventory.BlocksPage2Menu;
import net.mcreator.stmwr.world.inventory.BlazingPlasticRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedSwordRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedShovelRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedPickaxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedHoeRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedHelmetRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedGearRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedChestplateRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedAxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.BPVortexManipulationRecipeMenu;
import net.mcreator.stmwr.world.inventory.BPUraniumHydroponicsRecipeMenu;
import net.mcreator.stmwr.world.inventory.BPRepairPlantRecipeMenu;
import net.mcreator.stmwr.world.inventory.BPPowercellRecipeMenu;
import net.mcreator.stmwr.world.inventory.BPPortableCrucibleOvenRecipeMenu;
import net.mcreator.stmwr.world.inventory.BPModularArmorUpgradesRecipeMenu;
import net.mcreator.stmwr.world.inventory.BPModularArmorRecipeMenu;
import net.mcreator.stmwr.world.inventory.BPConcreteMixerRecipeMenu;
import net.mcreator.stmwr.world.inventory.BOLPage1Menu;
import net.mcreator.stmwr.world.inventory.BOLHomePageMenu;
import net.mcreator.stmwr.world.inventory.AlloyFuseGUIMenu;
import net.mcreator.stmwr.world.inventory.AlligatorKnifeRecipeMenu;
import net.mcreator.stmwr.world.inventory.ActivatingT2TotemsMenu;
import net.mcreator.stmwr.world.inventory.AOTTotemsP2Menu;
import net.mcreator.stmwr.world.inventory.AOTTotemsP1Menu;
import net.mcreator.stmwr.world.inventory.AOTHomePageMenu;
import net.mcreator.stmwr.StmwrMod;

public class StmwrModMenus {
	public static final DeferredRegister<MenuType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.MENU_TYPES, StmwrMod.MODID);
	public static final RegistryObject<MenuType<KitchenGUIMenu>> KITCHEN_GUI = REGISTRY.register("kitchen_gui", () -> IForgeMenuType.create(KitchenGUIMenu::new));
	public static final RegistryObject<MenuType<CookBookHomePageMenu>> COOK_BOOK_HOME_PAGE = REGISTRY.register("cook_book_home_page", () -> IForgeMenuType.create(CookBookHomePageMenu::new));
	public static final RegistryObject<MenuType<ChickenNuggetRecipeMenu>> CHICKEN_NUGGET_RECIPE = REGISTRY.register("chicken_nugget_recipe", () -> IForgeMenuType.create(ChickenNuggetRecipeMenu::new));
	public static final RegistryObject<MenuType<PotatoChipsRecipeMenu>> POTATO_CHIPS_RECIPE = REGISTRY.register("potato_chips_recipe", () -> IForgeMenuType.create(PotatoChipsRecipeMenu::new));
	public static final RegistryObject<MenuType<TacoRecipeMenu>> TACO_RECIPE = REGISTRY.register("taco_recipe", () -> IForgeMenuType.create(TacoRecipeMenu::new));
	public static final RegistryObject<MenuType<TacoShellRecipeMenu>> TACO_SHELL_RECIPE = REGISTRY.register("taco_shell_recipe", () -> IForgeMenuType.create(TacoShellRecipeMenu::new));
	public static final RegistryObject<MenuType<ChocolateRecipeMenu>> CHOCOLATE_RECIPE = REGISTRY.register("chocolate_recipe", () -> IForgeMenuType.create(ChocolateRecipeMenu::new));
	public static final RegistryObject<MenuType<SausageRecipeMenu>> SAUSAGE_RECIPE = REGISTRY.register("sausage_recipe", () -> IForgeMenuType.create(SausageRecipeMenu::new));
	public static final RegistryObject<MenuType<GroundBeefRecipeMenu>> GROUND_BEEF_RECIPE = REGISTRY.register("ground_beef_recipe", () -> IForgeMenuType.create(GroundBeefRecipeMenu::new));
	public static final RegistryObject<MenuType<PizzaSliceRecipeMenu>> PIZZA_SLICE_RECIPE = REGISTRY.register("pizza_slice_recipe", () -> IForgeMenuType.create(PizzaSliceRecipeMenu::new));
	public static final RegistryObject<MenuType<TortillaRecipeMenu>> TORTILLA_RECIPE = REGISTRY.register("tortilla_recipe", () -> IForgeMenuType.create(TortillaRecipeMenu::new));
	public static final RegistryObject<MenuType<PizzaRecipeMenu>> PIZZA_RECIPE = REGISTRY.register("pizza_recipe", () -> IForgeMenuType.create(PizzaRecipeMenu::new));
	public static final RegistryObject<MenuType<PepperoniRecipeMenu>> PEPPERONI_RECIPE = REGISTRY.register("pepperoni_recipe", () -> IForgeMenuType.create(PepperoniRecipeMenu::new));
	public static final RegistryObject<MenuType<CheeseStickRecipeMenu>> CHEESE_STICK_RECIPE = REGISTRY.register("cheese_stick_recipe", () -> IForgeMenuType.create(CheeseStickRecipeMenu::new));
	public static final RegistryObject<MenuType<MagiciansWorkbenchGUIMenu>> MAGICIANS_WORKBENCH_GUI = REGISTRY.register("magicians_workbench_gui", () -> IForgeMenuType.create(MagiciansWorkbenchGUIMenu::new));
	public static final RegistryObject<MenuType<StorageCubeGUIMenu>> STORAGE_CUBE_GUI = REGISTRY.register("storage_cube_gui", () -> IForgeMenuType.create(StorageCubeGUIMenu::new));
	public static final RegistryObject<MenuType<ForgeGUIMenu>> FORGE_GUI = REGISTRY.register("forge_gui", () -> IForgeMenuType.create(ForgeGUIMenu::new));
	public static final RegistryObject<MenuType<HomePageMenu>> HOME_PAGE = REGISTRY.register("home_page", () -> IForgeMenuType.create(HomePageMenu::new));
	public static final RegistryObject<MenuType<CategoriesMenu>> CATEGORIES = REGISTRY.register("categories", () -> IForgeMenuType.create(CategoriesMenu::new));
	public static final RegistryObject<MenuType<ToolsAndArmorMenu>> TOOLS_AND_ARMOR = REGISTRY.register("tools_and_armor", () -> IForgeMenuType.create(ToolsAndArmorMenu::new));
	public static final RegistryObject<MenuType<BlocksPageMenu>> BLOCKS_PAGE = REGISTRY.register("blocks_page", () -> IForgeMenuType.create(BlocksPageMenu::new));
	public static final RegistryObject<MenuType<AlligatorKnifeRecipeMenu>> ALLIGATOR_KNIFE_RECIPE = REGISTRY.register("alligator_knife_recipe", () -> IForgeMenuType.create(AlligatorKnifeRecipeMenu::new));
	public static final RegistryObject<MenuType<SpellforgeGUIMenu>> SPELLFORGE_GUI = REGISTRY.register("spellforge_gui", () -> IForgeMenuType.create(SpellforgeGUIMenu::new));
	public static final RegistryObject<MenuType<CodexHomePageMenu>> CODEX_HOME_PAGE = REGISTRY.register("codex_home_page", () -> IForgeMenuType.create(CodexHomePageMenu::new));
	public static final RegistryObject<MenuType<SpellsP1Menu>> SPELLS_P_1 = REGISTRY.register("spells_p_1", () -> IForgeMenuType.create(SpellsP1Menu::new));
	public static final RegistryObject<MenuType<WizardsSeaRecipeMenu>> WIZARDS_SEA_RECIPE = REGISTRY.register("wizards_sea_recipe", () -> IForgeMenuType.create(WizardsSeaRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedGearRecipeMenu>> BLAZED_GEAR_RECIPE = REGISTRY.register("blazed_gear_recipe", () -> IForgeMenuType.create(BlazedGearRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedHelmetRecipeMenu>> BLAZED_HELMET_RECIPE = REGISTRY.register("blazed_helmet_recipe", () -> IForgeMenuType.create(BlazedHelmetRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedChestplateRecipeMenu>> BLAZED_CHESTPLATE_RECIPE = REGISTRY.register("blazed_chestplate_recipe", () -> IForgeMenuType.create(BlazedChestplateRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedLeggingsRecipeMenu>> BLAZED_LEGGINGS_RECIPE = REGISTRY.register("blazed_leggings_recipe", () -> IForgeMenuType.create(BlazedLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedBootsRecipeMenu>> BLAZED_BOOTS_RECIPE = REGISTRY.register("blazed_boots_recipe", () -> IForgeMenuType.create(BlazedBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedSwordRecipeMenu>> BLAZED_SWORD_RECIPE = REGISTRY.register("blazed_sword_recipe", () -> IForgeMenuType.create(BlazedSwordRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedAxeRecipeMenu>> BLAZED_AXE_RECIPE = REGISTRY.register("blazed_axe_recipe", () -> IForgeMenuType.create(BlazedAxeRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedPickaxeRecipeMenu>> BLAZED_PICKAXE_RECIPE = REGISTRY.register("blazed_pickaxe_recipe", () -> IForgeMenuType.create(BlazedPickaxeRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedShovelRecipeMenu>> BLAZED_SHOVEL_RECIPE = REGISTRY.register("blazed_shovel_recipe", () -> IForgeMenuType.create(BlazedShovelRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedHoeRecipeMenu>> BLAZED_HOE_RECIPE = REGISTRY.register("blazed_hoe_recipe", () -> IForgeMenuType.create(BlazedHoeRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazingPlasticRecipeMenu>> BLAZING_PLASTIC_RECIPE = REGISTRY.register("blazing_plastic_recipe", () -> IForgeMenuType.create(BlazingPlasticRecipeMenu::new));
	public static final RegistryObject<MenuType<FlamingStorageCubeGUIMenu>> FLAMING_STORAGE_CUBE_GUI = REGISTRY.register("flaming_storage_cube_gui", () -> IForgeMenuType.create(FlamingStorageCubeGUIMenu::new));
	public static final RegistryObject<MenuType<FlamingStorageCubeRecipeMenu>> FLAMING_STORAGE_CUBE_RECIPE = REGISTRY.register("flaming_storage_cube_recipe", () -> IForgeMenuType.create(FlamingStorageCubeRecipeMenu::new));
	public static final RegistryObject<MenuType<OrePurifierGUIMenu>> ORE_PURIFIER_GUI = REGISTRY.register("ore_purifier_gui", () -> IForgeMenuType.create(OrePurifierGUIMenu::new));
	public static final RegistryObject<MenuType<GodliumGearRecipeMenu>> GODLIUM_GEAR_RECIPE = REGISTRY.register("godlium_gear_recipe", () -> IForgeMenuType.create(GodliumGearRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumHelmetRecipeMenu>> GODLIUM_HELMET_RECIPE = REGISTRY.register("godlium_helmet_recipe", () -> IForgeMenuType.create(GodliumHelmetRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumChestplateRecipeMenu>> GODLIUM_CHESTPLATE_RECIPE = REGISTRY.register("godlium_chestplate_recipe", () -> IForgeMenuType.create(GodliumChestplateRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumLeggingsRecipeMenu>> GODLIUM_LEGGINGS_RECIPE = REGISTRY.register("godlium_leggings_recipe", () -> IForgeMenuType.create(GodliumLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumBootsRecipeMenu>> GODLIUM_BOOTS_RECIPE = REGISTRY.register("godlium_boots_recipe", () -> IForgeMenuType.create(GodliumBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumSwordRecipeMenu>> GODLIUM_SWORD_RECIPE = REGISTRY.register("godlium_sword_recipe", () -> IForgeMenuType.create(GodliumSwordRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumPickaxeRecipeMenu>> GODLIUM_PICKAXE_RECIPE = REGISTRY.register("godlium_pickaxe_recipe", () -> IForgeMenuType.create(GodliumPickaxeRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumAxeRecipeMenu>> GODLIUM_AXE_RECIPE = REGISTRY.register("godlium_axe_recipe", () -> IForgeMenuType.create(GodliumAxeRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumShovelRecipeMenu>> GODLIUM_SHOVEL_RECIPE = REGISTRY.register("godlium_shovel_recipe", () -> IForgeMenuType.create(GodliumShovelRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumHoeRecipeMenu>> GODLIUM_HOE_RECIPE = REGISTRY.register("godlium_hoe_recipe", () -> IForgeMenuType.create(GodliumHoeRecipeMenu::new));
	public static final RegistryObject<MenuType<StopstoneRecipeMenu>> STOPSTONE_RECIPE = REGISTRY.register("stopstone_recipe", () -> IForgeMenuType.create(StopstoneRecipeMenu::new));
	public static final RegistryObject<MenuType<SpeedstoneRecipeMenu>> SPEEDSTONE_RECIPE = REGISTRY.register("speedstone_recipe", () -> IForgeMenuType.create(SpeedstoneRecipeMenu::new));
	public static final RegistryObject<MenuType<DupestoneRecipeMenu>> DUPESTONE_RECIPE = REGISTRY.register("dupestone_recipe", () -> IForgeMenuType.create(DupestoneRecipeMenu::new));
	public static final RegistryObject<MenuType<AlloyFuseGUIMenu>> ALLOY_FUSE_GUI = REGISTRY.register("alloy_fuse_gui", () -> IForgeMenuType.create(AlloyFuseGUIMenu::new));
	public static final RegistryObject<MenuType<TotemFusionStationGUIMenu>> TOTEM_FUSION_STATION_GUI = REGISTRY.register("totem_fusion_station_gui", () -> IForgeMenuType.create(TotemFusionStationGUIMenu::new));
	public static final RegistryObject<MenuType<AOTHomePageMenu>> AOT_HOME_PAGE = REGISTRY.register("aot_home_page", () -> IForgeMenuType.create(AOTHomePageMenu::new));
	public static final RegistryObject<MenuType<AOTTotemsP1Menu>> AOT_TOTEMS_P_1 = REGISTRY.register("aot_totems_p_1", () -> IForgeMenuType.create(AOTTotemsP1Menu::new));
	public static final RegistryObject<MenuType<TotemOfFireResistanceRecipeMenu>> TOTEM_OF_FIRE_RESISTANCE_RECIPE = REGISTRY.register("totem_of_fire_resistance_recipe", () -> IForgeMenuType.create(TotemOfFireResistanceRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfSpeedRecipeMenu>> TOTEM_OF_SPEED_RECIPE = REGISTRY.register("totem_of_speed_recipe", () -> IForgeMenuType.create(TotemOfSpeedRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfWaterBreathingRecipeMenu>> TOTEM_OF_WATER_BREATHING_RECIPE = REGISTRY.register("totem_of_water_breathing_recipe", () -> IForgeMenuType.create(TotemOfWaterBreathingRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfHasteRecipeMenu>> TOTEM_OF_HASTE_RECIPE = REGISTRY.register("totem_of_haste_recipe", () -> IForgeMenuType.create(TotemOfHasteRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfHealthBoostRecipeMenu>> TOTEM_OF_HEALTH_BOOST_RECIPE = REGISTRY.register("totem_of_health_boost_recipe", () -> IForgeMenuType.create(TotemOfHealthBoostRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfJumpBoostRecipeMenu>> TOTEM_OF_JUMP_BOOST_RECIPE = REGISTRY.register("totem_of_jump_boost_recipe", () -> IForgeMenuType.create(TotemOfJumpBoostRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfNightVisionRecipeMenu>> TOTEM_OF_NIGHT_VISION_RECIPE = REGISTRY.register("totem_of_night_vision_recipe", () -> IForgeMenuType.create(TotemOfNightVisionRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfStrengthRecipeMenu>> TOTEM_OF_STRENGTH_RECIPE = REGISTRY.register("totem_of_strength_recipe", () -> IForgeMenuType.create(TotemOfStrengthRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfDolphinsGraceRecipeMenu>> TOTEM_OF_DOLPHINS_GRACE_RECIPE = REGISTRY.register("totem_of_dolphins_grace_recipe", () -> IForgeMenuType.create(TotemOfDolphinsGraceRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfLevitationRecipeMenu>> TOTEM_OF_LEVITATION_RECIPE = REGISTRY.register("totem_of_levitation_recipe", () -> IForgeMenuType.create(TotemOfLevitationRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfRegenerationRecipeMenu>> TOTEM_OF_REGENERATION_RECIPE = REGISTRY.register("totem_of_regeneration_recipe", () -> IForgeMenuType.create(TotemOfRegenerationRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfGamblingRecipeMenu>> TOTEM_OF_GAMBLING_RECIPE = REGISTRY.register("totem_of_gambling_recipe", () -> IForgeMenuType.create(TotemOfGamblingRecipeMenu::new));
	public static final RegistryObject<MenuType<ConsumerGUIMenu>> CONSUMER_GUI = REGISTRY.register("consumer_gui", () -> IForgeMenuType.create(ConsumerGUIMenu::new));
	public static final RegistryObject<MenuType<HODHomePageMenu>> HOD_HOME_PAGE = REGISTRY.register("hod_home_page", () -> IForgeMenuType.create(HODHomePageMenu::new));
	public static final RegistryObject<MenuType<HODCategoriesMenu>> HOD_CATEGORIES = REGISTRY.register("hod_categories", () -> IForgeMenuType.create(HODCategoriesMenu::new));
	public static final RegistryObject<MenuType<HODOverworldMenu>> HOD_OVERWORLD = REGISTRY.register("hod_overworld", () -> IForgeMenuType.create(HODOverworldMenu::new));
	public static final RegistryObject<MenuType<HODTheWitherMenu>> HOD_THE_WITHER = REGISTRY.register("hod_the_wither", () -> IForgeMenuType.create(HODTheWitherMenu::new));
	public static final RegistryObject<MenuType<CompressorGUIMenu>> COMPRESSOR_GUI = REGISTRY.register("compressor_gui", () -> IForgeMenuType.create(CompressorGUIMenu::new));
	public static final RegistryObject<MenuType<GodliumKnifeRecipeMenu>> GODLIUM_KNIFE_RECIPE = REGISTRY.register("godlium_knife_recipe", () -> IForgeMenuType.create(GodliumKnifeRecipeMenu::new));
	public static final RegistryObject<MenuType<GodlyStorageCubeGUIMenu>> GODLY_STORAGE_CUBE_GUI = REGISTRY.register("godly_storage_cube_gui", () -> IForgeMenuType.create(GodlyStorageCubeGUIMenu::new));
	public static final RegistryObject<MenuType<GodlyStorageCubeRecipeMenu>> GODLY_STORAGE_CUBE_RECIPE = REGISTRY.register("godly_storage_cube_recipe", () -> IForgeMenuType.create(GodlyStorageCubeRecipeMenu::new));
	public static final RegistryObject<MenuType<TrialBricksRecipeMenu>> TRIAL_BRICKS_RECIPE = REGISTRY.register("trial_bricks_recipe", () -> IForgeMenuType.create(TrialBricksRecipeMenu::new));
	public static final RegistryObject<MenuType<KeyAnvilGUIMenu>> KEY_ANVIL_GUI = REGISTRY.register("key_anvil_gui", () -> IForgeMenuType.create(KeyAnvilGUIMenu::new));
	public static final RegistryObject<MenuType<ColdsteelGearRecipeMenu>> COLDSTEEL_GEAR_RECIPE = REGISTRY.register("coldsteel_gear_recipe", () -> IForgeMenuType.create(ColdsteelGearRecipeMenu::new));
	public static final RegistryObject<MenuType<FrozenForgeGUIMenu>> FROZEN_FORGE_GUI = REGISTRY.register("frozen_forge_gui", () -> IForgeMenuType.create(FrozenForgeGUIMenu::new));
	public static final RegistryObject<MenuType<ColdsteelHelmetRecipeMenu>> COLDSTEEL_HELMET_RECIPE = REGISTRY.register("coldsteel_helmet_recipe", () -> IForgeMenuType.create(ColdsteelHelmetRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelChestplateRecipeMenu>> COLDSTEEL_CHESTPLATE_RECIPE = REGISTRY.register("coldsteel_chestplate_recipe", () -> IForgeMenuType.create(ColdsteelChestplateRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelLeggingsRecipeMenu>> COLDSTEEL_LEGGINGS_RECIPE = REGISTRY.register("coldsteel_leggings_recipe", () -> IForgeMenuType.create(ColdsteelLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelBootsRecipeMenu>> COLDSTEEL_BOOTS_RECIPE = REGISTRY.register("coldsteel_boots_recipe", () -> IForgeMenuType.create(ColdsteelBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelSwordRecipeMenu>> COLDSTEEL_SWORD_RECIPE = REGISTRY.register("coldsteel_sword_recipe", () -> IForgeMenuType.create(ColdsteelSwordRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelPickaxeRecipeMenu>> COLDSTEEL_PICKAXE_RECIPE = REGISTRY.register("coldsteel_pickaxe_recipe", () -> IForgeMenuType.create(ColdsteelPickaxeRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelAxeRecipeMenu>> COLDSTEEL_AXE_RECIPE = REGISTRY.register("coldsteel_axe_recipe", () -> IForgeMenuType.create(ColdsteelAxeRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelShovelRecipeMenu>> COLDSTEEL_SHOVEL_RECIPE = REGISTRY.register("coldsteel_shovel_recipe", () -> IForgeMenuType.create(ColdsteelShovelRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelHoeRecipeMenu>> COLDSTEEL_HOE_RECIPE = REGISTRY.register("coldsteel_hoe_recipe", () -> IForgeMenuType.create(ColdsteelHoeRecipeMenu::new));
	public static final RegistryObject<MenuType<SoulShardRecipeMenu>> SOUL_SHARD_RECIPE = REGISTRY.register("soul_shard_recipe", () -> IForgeMenuType.create(SoulShardRecipeMenu::new));
	public static final RegistryObject<MenuType<FrostwatchRecipeMenu>> FROSTWATCH_RECIPE = REGISTRY.register("frostwatch_recipe", () -> IForgeMenuType.create(FrostwatchRecipeMenu::new));
	public static final RegistryObject<MenuType<SnowyShrapnelRecipeMenu>> SNOWY_SHRAPNEL_RECIPE = REGISTRY.register("snowy_shrapnel_recipe", () -> IForgeMenuType.create(SnowyShrapnelRecipeMenu::new));
	public static final RegistryObject<MenuType<LightningStaffRecipeMenu>> LIGHTNING_STAFF_RECIPE = REGISTRY.register("lightning_staff_recipe", () -> IForgeMenuType.create(LightningStaffRecipeMenu::new));
	public static final RegistryObject<MenuType<SmallStoragePackGUIMenu>> SMALL_STORAGE_PACK_GUI = REGISTRY.register("small_storage_pack_gui", () -> IForgeMenuType.create(SmallStoragePackGUIMenu::new));
	public static final RegistryObject<MenuType<TotemOfTheCowRecipeMenu>> TOTEM_OF_THE_COW_RECIPE = REGISTRY.register("totem_of_the_cow_recipe", () -> IForgeMenuType.create(TotemOfTheCowRecipeMenu::new));
	public static final RegistryObject<MenuType<HODSteveCowLandMenu>> HOD_STEVE_COW_LAND = REGISTRY.register("hod_steve_cow_land", () -> IForgeMenuType.create(HODSteveCowLandMenu::new));
	public static final RegistryObject<MenuType<HODSteveCowMenu>> HOD_STEVE_COW = REGISTRY.register("hod_steve_cow", () -> IForgeMenuType.create(HODSteveCowMenu::new));
	public static final RegistryObject<MenuType<HODFrombieMenu>> HOD_FROMBIE = REGISTRY.register("hod_frombie", () -> IForgeMenuType.create(HODFrombieMenu::new));
	public static final RegistryObject<MenuType<HODPikachuMenu>> HOD_PIKACHU = REGISTRY.register("hod_pikachu", () -> IForgeMenuType.create(HODPikachuMenu::new));
	public static final RegistryObject<MenuType<HODLesserWizardMenu>> HOD_LESSER_WIZARD = REGISTRY.register("hod_lesser_wizard", () -> IForgeMenuType.create(HODLesserWizardMenu::new));
	public static final RegistryObject<MenuType<HODCrusherMenu>> HOD_CRUSHER = REGISTRY.register("hod_crusher", () -> IForgeMenuType.create(HODCrusherMenu::new));
	public static final RegistryObject<MenuType<HODGiantSteveCowMenu>> HOD_GIANT_STEVE_COW = REGISTRY.register("hod_giant_steve_cow", () -> IForgeMenuType.create(HODGiantSteveCowMenu::new));
	public static final RegistryObject<MenuType<HODLightningWizardMenu>> HOD_LIGHTNING_WIZARD = REGISTRY.register("hod_lightning_wizard", () -> IForgeMenuType.create(HODLightningWizardMenu::new));
	public static final RegistryObject<MenuType<HODLightningCultistMenu>> HOD_LIGHTNING_CULTIST = REGISTRY.register("hod_lightning_cultist", () -> IForgeMenuType.create(HODLightningCultistMenu::new));
	public static final RegistryObject<MenuType<PurifierMK2GUIMenu>> PURIFIER_MK_2_GUI = REGISTRY.register("purifier_mk_2_gui", () -> IForgeMenuType.create(PurifierMK2GUIMenu::new));
	public static final RegistryObject<MenuType<DoomforgeGUIMenu>> DOOMFORGE_GUI = REGISTRY.register("doomforge_gui", () -> IForgeMenuType.create(DoomforgeGUIMenu::new));
	public static final RegistryObject<MenuType<UraniumFuelRodRecipeMenu>> URANIUM_FUEL_ROD_RECIPE = REGISTRY.register("uranium_fuel_rod_recipe", () -> IForgeMenuType.create(UraniumFuelRodRecipeMenu::new));
	public static final RegistryObject<MenuType<ItemsPageMenu>> ITEMS_PAGE = REGISTRY.register("items_page", () -> IForgeMenuType.create(ItemsPageMenu::new));
	public static final RegistryObject<MenuType<RadiationRemovalPlantGUIMenu>> RADIATION_REMOVAL_PLANT_GUI = REGISTRY.register("radiation_removal_plant_gui", () -> IForgeMenuType.create(RadiationRemovalPlantGUIMenu::new));
	public static final RegistryObject<MenuType<BubbleRecipeMenu>> BUBBLE_RECIPE = REGISTRY.register("bubble_recipe", () -> IForgeMenuType.create(BubbleRecipeMenu::new));
	public static final RegistryObject<MenuType<ManufacturingPlantGUIMenu>> MANUFACTURING_PLANT_GUI = REGISTRY.register("manufacturing_plant_gui", () -> IForgeMenuType.create(ManufacturingPlantGUIMenu::new));
	public static final RegistryObject<MenuType<ManupediaHomeMenu>> MANUPEDIA_HOME = REGISTRY.register("manupedia_home", () -> IForgeMenuType.create(ManupediaHomeMenu::new));
	public static final RegistryObject<MenuType<ManupediaRecipesMenu>> MANUPEDIA_RECIPES = REGISTRY.register("manupedia_recipes", () -> IForgeMenuType.create(ManupediaRecipesMenu::new));
	public static final RegistryObject<MenuType<NailsRecipeMenu>> NAILS_RECIPE = REGISTRY.register("nails_recipe", () -> IForgeMenuType.create(NailsRecipeMenu::new));
	public static final RegistryObject<MenuType<RodsRecipeMenu>> RODS_RECIPE = REGISTRY.register("rods_recipe", () -> IForgeMenuType.create(RodsRecipeMenu::new));
	public static final RegistryObject<MenuType<PlatesRecipeMenu>> PLATES_RECIPE = REGISTRY.register("plates_recipe", () -> IForgeMenuType.create(PlatesRecipeMenu::new));
	public static final RegistryObject<MenuType<CogsRecipeMenu>> COGS_RECIPE = REGISTRY.register("cogs_recipe", () -> IForgeMenuType.create(CogsRecipeMenu::new));
	public static final RegistryObject<MenuType<SpringsRecipeMenu>> SPRINGS_RECIPE = REGISTRY.register("springs_recipe", () -> IForgeMenuType.create(SpringsRecipeMenu::new));
	public static final RegistryObject<MenuType<ChickenGunRecipeMenu>> CHICKEN_GUN_RECIPE = REGISTRY.register("chicken_gun_recipe", () -> IForgeMenuType.create(ChickenGunRecipeMenu::new));
	public static final RegistryObject<MenuType<SoulManipulatorGUIMenu>> SOUL_MANIPULATOR_GUI = REGISTRY.register("soul_manipulator_gui", () -> IForgeMenuType.create(SoulManipulatorGUIMenu::new));
	public static final RegistryObject<MenuType<AOTTotemsP2Menu>> AOT_TOTEMS_P_2 = REGISTRY.register("aot_totems_p_2", () -> IForgeMenuType.create(AOTTotemsP2Menu::new));
	public static final RegistryObject<MenuType<TotemOfSpeedIIRecipeMenu>> TOTEM_OF_SPEED_II_RECIPE = REGISTRY.register("totem_of_speed_ii_recipe", () -> IForgeMenuType.create(TotemOfSpeedIIRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfHealthBoostIIRecipeMenu>> TOTEM_OF_HEALTH_BOOST_II_RECIPE = REGISTRY.register("totem_of_health_boost_ii_recipe", () -> IForgeMenuType.create(TotemOfHealthBoostIIRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfJumpBoostIIRecipeMenu>> TOTEM_OF_JUMP_BOOST_II_RECIPE = REGISTRY.register("totem_of_jump_boost_ii_recipe", () -> IForgeMenuType.create(TotemOfJumpBoostIIRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfHasteIIRecipeMenu>> TOTEM_OF_HASTE_II_RECIPE = REGISTRY.register("totem_of_haste_ii_recipe", () -> IForgeMenuType.create(TotemOfHasteIIRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfStrengthIIRecipeMenu>> TOTEM_OF_STRENGTH_II_RECIPE = REGISTRY.register("totem_of_strength_ii_recipe", () -> IForgeMenuType.create(TotemOfStrengthIIRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfRegenerationIIRecipeMenu>> TOTEM_OF_REGENERATION_II_RECIPE = REGISTRY.register("totem_of_regeneration_ii_recipe", () -> IForgeMenuType.create(TotemOfRegenerationIIRecipeMenu::new));
	public static final RegistryObject<MenuType<RitualStoneGUIMenu>> RITUAL_STONE_GUI = REGISTRY.register("ritual_stone_gui", () -> IForgeMenuType.create(RitualStoneGUIMenu::new));
	public static final RegistryObject<MenuType<RitualStoneRecipeMenu>> RITUAL_STONE_RECIPE = REGISTRY.register("ritual_stone_recipe", () -> IForgeMenuType.create(RitualStoneRecipeMenu::new));
	public static final RegistryObject<MenuType<BOLHomePageMenu>> BOL_HOME_PAGE = REGISTRY.register("bol_home_page", () -> IForgeMenuType.create(BOLHomePageMenu::new));
	public static final RegistryObject<MenuType<BOLPage1Menu>> BOL_PAGE_1 = REGISTRY.register("bol_page_1", () -> IForgeMenuType.create(BOLPage1Menu::new));
	public static final RegistryObject<MenuType<ActivatingT2TotemsMenu>> ACTIVATING_T_2_TOTEMS = REGISTRY.register("activating_t_2_totems", () -> IForgeMenuType.create(ActivatingT2TotemsMenu::new));
	public static final RegistryObject<MenuType<CreationOrbRecipeMenu>> CREATION_ORB_RECIPE = REGISTRY.register("creation_orb_recipe", () -> IForgeMenuType.create(CreationOrbRecipeMenu::new));
	public static final RegistryObject<MenuType<DesignerGUIMenu>> DESIGNER_GUI = REGISTRY.register("designer_gui", () -> IForgeMenuType.create(DesignerGUIMenu::new));
	public static final RegistryObject<MenuType<ItemResearcherGUIMenu>> ITEM_RESEARCHER_GUI = REGISTRY.register("item_researcher_gui", () -> IForgeMenuType.create(ItemResearcherGUIMenu::new));
	public static final RegistryObject<MenuType<BlueprintBookHomePageMenu>> BLUEPRINT_BOOK_HOME_PAGE = REGISTRY.register("blueprint_book_home_page", () -> IForgeMenuType.create(BlueprintBookHomePageMenu::new));
	public static final RegistryObject<MenuType<BlueprintBookP1Menu>> BLUEPRINT_BOOK_P_1 = REGISTRY.register("blueprint_book_p_1", () -> IForgeMenuType.create(BlueprintBookP1Menu::new));
	public static final RegistryObject<MenuType<BPConcreteMixerRecipeMenu>> BP_CONCRETE_MIXER_RECIPE = REGISTRY.register("bp_concrete_mixer_recipe", () -> IForgeMenuType.create(BPConcreteMixerRecipeMenu::new));
	public static final RegistryObject<MenuType<BPUraniumHydroponicsRecipeMenu>> BP_URANIUM_HYDROPONICS_RECIPE = REGISTRY.register("bp_uranium_hydroponics_recipe", () -> IForgeMenuType.create(BPUraniumHydroponicsRecipeMenu::new));
	public static final RegistryObject<MenuType<BPPowercellRecipeMenu>> BP_POWERCELL_RECIPE = REGISTRY.register("bp_powercell_recipe", () -> IForgeMenuType.create(BPPowercellRecipeMenu::new));
	public static final RegistryObject<MenuType<BPModularArmorRecipeMenu>> BP_MODULAR_ARMOR_RECIPE = REGISTRY.register("bp_modular_armor_recipe", () -> IForgeMenuType.create(BPModularArmorRecipeMenu::new));
	public static final RegistryObject<MenuType<BPModularArmorUpgradesRecipeMenu>> BP_MODULAR_ARMOR_UPGRADES_RECIPE = REGISTRY.register("bp_modular_armor_upgrades_recipe", () -> IForgeMenuType.create(BPModularArmorUpgradesRecipeMenu::new));
	public static final RegistryObject<MenuType<BPRepairPlantRecipeMenu>> BP_REPAIR_PLANT_RECIPE = REGISTRY.register("bp_repair_plant_recipe", () -> IForgeMenuType.create(BPRepairPlantRecipeMenu::new));
	public static final RegistryObject<MenuType<BPVortexManipulationRecipeMenu>> BP_VORTEX_MANIPULATION_RECIPE = REGISTRY.register("bp_vortex_manipulation_recipe", () -> IForgeMenuType.create(BPVortexManipulationRecipeMenu::new));
	public static final RegistryObject<MenuType<BPPortableCrucibleOvenRecipeMenu>> BP_PORTABLE_CRUCIBLE_OVEN_RECIPE = REGISTRY.register("bp_portable_crucible_oven_recipe", () -> IForgeMenuType.create(BPPortableCrucibleOvenRecipeMenu::new));
	public static final RegistryObject<MenuType<ConcreteMixerGUIMenu>> CONCRETE_MIXER_GUI = REGISTRY.register("concrete_mixer_gui", () -> IForgeMenuType.create(ConcreteMixerGUIMenu::new));
	public static final RegistryObject<MenuType<ConcreteMixerRecipeMenu>> CONCRETE_MIXER_RECIPE = REGISTRY.register("concrete_mixer_recipe", () -> IForgeMenuType.create(ConcreteMixerRecipeMenu::new));
	public static final RegistryObject<MenuType<UraniumHydroponicsGUIMenu>> URANIUM_HYDROPONICS_GUI = REGISTRY.register("uranium_hydroponics_gui", () -> IForgeMenuType.create(UraniumHydroponicsGUIMenu::new));
	public static final RegistryObject<MenuType<BlocksPage2Menu>> BLOCKS_PAGE_2 = REGISTRY.register("blocks_page_2", () -> IForgeMenuType.create(BlocksPage2Menu::new));
	public static final RegistryObject<MenuType<UraniumHydroponicsRecipeMenu>> URANIUM_HYDROPONICS_RECIPE = REGISTRY.register("uranium_hydroponics_recipe", () -> IForgeMenuType.create(UraniumHydroponicsRecipeMenu::new));
	public static final RegistryObject<MenuType<UraniumHydroponicsUtilityHatchRecipeMenu>> URANIUM_HYDROPONICS_UTILITY_HATCH_RECIPE = REGISTRY.register("uranium_hydroponics_utility_hatch_recipe",
			() -> IForgeMenuType.create(UraniumHydroponicsUtilityHatchRecipeMenu::new));
	public static final RegistryObject<MenuType<PowercellRecipeMenu>> POWERCELL_RECIPE = REGISTRY.register("powercell_recipe", () -> IForgeMenuType.create(PowercellRecipeMenu::new));
	public static final RegistryObject<MenuType<ModularGearRecipesMenu>> MODULAR_GEAR_RECIPES = REGISTRY.register("modular_gear_recipes", () -> IForgeMenuType.create(ModularGearRecipesMenu::new));
	public static final RegistryObject<MenuType<ModularHelmetRecipeMenu>> MODULAR_HELMET_RECIPE = REGISTRY.register("modular_helmet_recipe", () -> IForgeMenuType.create(ModularHelmetRecipeMenu::new));
	public static final RegistryObject<MenuType<ModularChestplateRecipeMenu>> MODULAR_CHESTPLATE_RECIPE = REGISTRY.register("modular_chestplate_recipe", () -> IForgeMenuType.create(ModularChestplateRecipeMenu::new));
	public static final RegistryObject<MenuType<ModularLeggingsRecipeMenu>> MODULAR_LEGGINGS_RECIPE = REGISTRY.register("modular_leggings_recipe", () -> IForgeMenuType.create(ModularLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<ModularBootsRecipeMenu>> MODULAR_BOOTS_RECIPE = REGISTRY.register("modular_boots_recipe", () -> IForgeMenuType.create(ModularBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<NightVisionGogglesRecipeMenu>> NIGHT_VISION_GOGGLES_RECIPE = REGISTRY.register("night_vision_goggles_recipe", () -> IForgeMenuType.create(NightVisionGogglesRecipeMenu::new));
	public static final RegistryObject<MenuType<ReinforcedArmsRecipeMenu>> REINFORCED_ARMS_RECIPE = REGISTRY.register("reinforced_arms_recipe", () -> IForgeMenuType.create(ReinforcedArmsRecipeMenu::new));
	public static final RegistryObject<MenuType<PoweredLeggingsRecipeMenu>> POWERED_LEGGINGS_RECIPE = REGISTRY.register("powered_leggings_recipe", () -> IForgeMenuType.create(PoweredLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<LongFallBootsRecipeMenu>> LONG_FALL_BOOTS_RECIPE = REGISTRY.register("long_fall_boots_recipe", () -> IForgeMenuType.create(LongFallBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<RepairPlantGUIMenu>> REPAIR_PLANT_GUI = REGISTRY.register("repair_plant_gui", () -> IForgeMenuType.create(RepairPlantGUIMenu::new));
	public static final RegistryObject<MenuType<RepairPlantRecipeMenu>> REPAIR_PLANT_RECIPE = REGISTRY.register("repair_plant_recipe", () -> IForgeMenuType.create(RepairPlantRecipeMenu::new));
	public static final RegistryObject<MenuType<WarpBrickRecipeMenu>> WARP_BRICK_RECIPE = REGISTRY.register("warp_brick_recipe", () -> IForgeMenuType.create(WarpBrickRecipeMenu::new));
	public static final RegistryObject<MenuType<VortexManipulatorRecipeMenu>> VORTEX_MANIPULATOR_RECIPE = REGISTRY.register("vortex_manipulator_recipe", () -> IForgeMenuType.create(VortexManipulatorRecipeMenu::new));
	public static final RegistryObject<MenuType<PortableCrucibleRecipeMenu>> PORTABLE_CRUCIBLE_RECIPE = REGISTRY.register("portable_crucible_recipe", () -> IForgeMenuType.create(PortableCrucibleRecipeMenu::new));
	public static final RegistryObject<MenuType<PortableOvenRecipeMenu>> PORTABLE_OVEN_RECIPE = REGISTRY.register("portable_oven_recipe", () -> IForgeMenuType.create(PortableOvenRecipeMenu::new));
	public static final RegistryObject<MenuType<EyeOfTheSteveCowRecipeMenu>> EYE_OF_THE_STEVE_COW_RECIPE = REGISTRY.register("eye_of_the_steve_cow_recipe", () -> IForgeMenuType.create(EyeOfTheSteveCowRecipeMenu::new));
	public static final RegistryObject<MenuType<EyeOfTimeRecipeMenu>> EYE_OF_TIME_RECIPE = REGISTRY.register("eye_of_time_recipe", () -> IForgeMenuType.create(EyeOfTimeRecipeMenu::new));
	public static final RegistryObject<MenuType<HODMilitariaMenu>> HOD_MILITARIA = REGISTRY.register("hod_militaria", () -> IForgeMenuType.create(HODMilitariaMenu::new));
	public static final RegistryObject<MenuType<HODIrradiatedPigMenu>> HOD_IRRADIATED_PIG = REGISTRY.register("hod_irradiated_pig", () -> IForgeMenuType.create(HODIrradiatedPigMenu::new));
	public static final RegistryObject<MenuType<HODIrradiatedChickenMenu>> HOD_IRRADIATED_CHICKEN = REGISTRY.register("hod_irradiated_chicken", () -> IForgeMenuType.create(HODIrradiatedChickenMenu::new));
	public static final RegistryObject<MenuType<HODIrradiatedCowMenu>> HOD_IRRADIATED_COW = REGISTRY.register("hod_irradiated_cow", () -> IForgeMenuType.create(HODIrradiatedCowMenu::new));
	public static final RegistryObject<MenuType<HODTheTimelessMenu>> HOD_THE_TIMELESS = REGISTRY.register("hod_the_timeless", () -> IForgeMenuType.create(HODTheTimelessMenu::new));
	public static final RegistryObject<MenuType<HODAncientWizardMenu>> HOD_ANCIENT_WIZARD = REGISTRY.register("hod_ancient_wizard", () -> IForgeMenuType.create(HODAncientWizardMenu::new));
	public static final RegistryObject<MenuType<HODGoolingMenu>> HOD_GOOLING = REGISTRY.register("hod_gooling", () -> IForgeMenuType.create(HODGoolingMenu::new));
	public static final RegistryObject<MenuType<UraniumProcessingPlantGUIMenu>> URANIUM_PROCESSING_PLANT_GUI = REGISTRY.register("uranium_processing_plant_gui", () -> IForgeMenuType.create(UraniumProcessingPlantGUIMenu::new));
	public static final RegistryObject<MenuType<MMHomePageMenu>> MM_HOME_PAGE = REGISTRY.register("mm_home_page", () -> IForgeMenuType.create(MMHomePageMenu::new));
	public static final RegistryObject<MenuType<MMMultiblocksP1Menu>> MM_MULTIBLOCKS_P_1 = REGISTRY.register("mm_multiblocks_p_1", () -> IForgeMenuType.create(MMMultiblocksP1Menu::new));
	public static final RegistryObject<MenuType<ConcreteMixerMultiblockRecipeMenu>> CONCRETE_MIXER_MULTIBLOCK_RECIPE = REGISTRY.register("concrete_mixer_multiblock_recipe", () -> IForgeMenuType.create(ConcreteMixerMultiblockRecipeMenu::new));
	public static final RegistryObject<MenuType<UraniumHydroponicsMultiblockRecipeMenu>> URANIUM_HYDROPONICS_MULTIBLOCK_RECIPE = REGISTRY.register("uranium_hydroponics_multiblock_recipe",
			() -> IForgeMenuType.create(UraniumHydroponicsMultiblockRecipeMenu::new));
	public static final RegistryObject<MenuType<LaboratoryMultiblockRecipeMenu>> LABORATORY_MULTIBLOCK_RECIPE = REGISTRY.register("laboratory_multiblock_recipe", () -> IForgeMenuType.create(LaboratoryMultiblockRecipeMenu::new));
	public static final RegistryObject<MenuType<RitualCircleMultiblockRecipeMenu>> RITUAL_CIRCLE_MULTIBLOCK_RECIPE = REGISTRY.register("ritual_circle_multiblock_recipe", () -> IForgeMenuType.create(RitualCircleMultiblockRecipeMenu::new));
	public static final RegistryObject<MenuType<SoulManipulatorMultiblockRecipeMenu>> SOUL_MANIPULATOR_MULTIBLOCK_RECIPE = REGISTRY.register("soul_manipulator_multiblock_recipe", () -> IForgeMenuType.create(SoulManipulatorMultiblockRecipeMenu::new));
	public static final RegistryObject<MenuType<TARDISMultiblockRecipeMenu>> TARDIS_MULTIBLOCK_RECIPE = REGISTRY.register("tardis_multiblock_recipe", () -> IForgeMenuType.create(TARDISMultiblockRecipeMenu::new));
	public static final RegistryObject<MenuType<DoomforgeMultiblockRecipeMenu>> DOOMFORGE_MULTIBLOCK_RECIPE = REGISTRY.register("doomforge_multiblock_recipe", () -> IForgeMenuType.create(DoomforgeMultiblockRecipeMenu::new));
	public static final RegistryObject<MenuType<RadiationRemovalPlantMultiblockRecipeMenu>> RADIATION_REMOVAL_PLANT_MULTIBLOCK_RECIPE = REGISTRY.register("radiation_removal_plant_multiblock_recipe",
			() -> IForgeMenuType.create(RadiationRemovalPlantMultiblockRecipeMenu::new));
	public static final RegistryObject<MenuType<ManufacturingPlantMultiblockRecipeMenu>> MANUFACTURING_PLANT_MULTIBLOCK_RECIPE = REGISTRY.register("manufacturing_plant_multiblock_recipe",
			() -> IForgeMenuType.create(ManufacturingPlantMultiblockRecipeMenu::new));
	public static final RegistryObject<MenuType<UraniumProcessingPlantMultiblockRecipeMenu>> URANIUM_PROCESSING_PLANT_MULTIBLOCK_RECIPE = REGISTRY.register("uranium_processing_plant_multiblock_recipe",
			() -> IForgeMenuType.create(UraniumProcessingPlantMultiblockRecipeMenu::new));
}
