
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.stmwr.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.stmwr.block.TrialBrickBlock;
import net.mcreator.stmwr.block.TotemFusionStationBlock;
import net.mcreator.stmwr.block.TomatoPlantBlock;
import net.mcreator.stmwr.block.StorumOreBlock;
import net.mcreator.stmwr.block.StorumBlockBlock;
import net.mcreator.stmwr.block.StorageCubeBlock;
import net.mcreator.stmwr.block.StopstoneBlock;
import net.mcreator.stmwr.block.StevumOreBlock;
import net.mcreator.stmwr.block.StevumBlockBlock;
import net.mcreator.stmwr.block.SteveCowLandPortalBlock;
import net.mcreator.stmwr.block.SpellforgeBlock;
import net.mcreator.stmwr.block.SpeedstoneBlock;
import net.mcreator.stmwr.block.SnowdirtBlock;
import net.mcreator.stmwr.block.SnapstoneBlock;
import net.mcreator.stmwr.block.PlasticBlock;
import net.mcreator.stmwr.block.PeanutPlantBlock;
import net.mcreator.stmwr.block.OrePurifierBlock;
import net.mcreator.stmwr.block.MagiciteOreBlock;
import net.mcreator.stmwr.block.MagiciteClumpBlock;
import net.mcreator.stmwr.block.MagiciteBlockBlock;
import net.mcreator.stmwr.block.MagiciansWorkbenchBlock;
import net.mcreator.stmwr.block.KitchenBlock;
import net.mcreator.stmwr.block.KeyAnvilBlock;
import net.mcreator.stmwr.block.IcicleBlock;
import net.mcreator.stmwr.block.HeartstoneOreBlock;
import net.mcreator.stmwr.block.HeartstoneBlockBlock;
import net.mcreator.stmwr.block.GodlyStorageCubeBlock;
import net.mcreator.stmwr.block.GodliumOreBlock;
import net.mcreator.stmwr.block.GodliumBlockBlock;
import net.mcreator.stmwr.block.FrozenForgeBlock;
import net.mcreator.stmwr.block.FrostyWoodBlock;
import net.mcreator.stmwr.block.FrostyStairsBlock;
import net.mcreator.stmwr.block.FrostySlabBlock;
import net.mcreator.stmwr.block.FrostySaplingBlock;
import net.mcreator.stmwr.block.FrostyPressurePlateBlock;
import net.mcreator.stmwr.block.FrostyPlanksBlock;
import net.mcreator.stmwr.block.FrostyLogBlock;
import net.mcreator.stmwr.block.FrostyLeavesBlock;
import net.mcreator.stmwr.block.FrostyFenceGateBlock;
import net.mcreator.stmwr.block.FrostyFenceBlock;
import net.mcreator.stmwr.block.FrostyButtonBlock;
import net.mcreator.stmwr.block.FrosticeBlock;
import net.mcreator.stmwr.block.ForgeBlock;
import net.mcreator.stmwr.block.FlamingStorageCubeBlock;
import net.mcreator.stmwr.block.DupestoneBlock;
import net.mcreator.stmwr.block.ConsumerBlock;
import net.mcreator.stmwr.block.CompressorBlock;
import net.mcreator.stmwr.block.ColdsteelOreBlock;
import net.mcreator.stmwr.block.ColdsteelBlockBlock;
import net.mcreator.stmwr.block.ColdGrassBlock;
import net.mcreator.stmwr.block.CobblesnowBlock;
import net.mcreator.stmwr.block.BlazingPlasticBlock;
import net.mcreator.stmwr.block.BlazedOreBlock;
import net.mcreator.stmwr.block.BlazedBlockBlock;
import net.mcreator.stmwr.block.ApplevineBlock;
import net.mcreator.stmwr.block.AlloyFuseBlock;
import net.mcreator.stmwr.StmwrMod;

public class StmwrModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, StmwrMod.MODID);
	public static final RegistryObject<Block> KITCHEN = REGISTRY.register("kitchen", () -> new KitchenBlock());
	public static final RegistryObject<Block> PEANUT_PLANT = REGISTRY.register("peanut_plant", () -> new PeanutPlantBlock());
	public static final RegistryObject<Block> TOMATO_PLANT = REGISTRY.register("tomato_plant", () -> new TomatoPlantBlock());
	public static final RegistryObject<Block> MAGICITE_ORE = REGISTRY.register("magicite_ore", () -> new MagiciteOreBlock());
	public static final RegistryObject<Block> MAGICITE_BLOCK = REGISTRY.register("magicite_block", () -> new MagiciteBlockBlock());
	public static final RegistryObject<Block> MAGICIANS_WORKBENCH = REGISTRY.register("magicians_workbench", () -> new MagiciansWorkbenchBlock());
	public static final RegistryObject<Block> STORUM_ORE = REGISTRY.register("storum_ore", () -> new StorumOreBlock());
	public static final RegistryObject<Block> STORUM_BLOCK = REGISTRY.register("storum_block", () -> new StorumBlockBlock());
	public static final RegistryObject<Block> STORAGE_CUBE = REGISTRY.register("storage_cube", () -> new StorageCubeBlock());
	public static final RegistryObject<Block> PLASTIC = REGISTRY.register("plastic", () -> new PlasticBlock());
	public static final RegistryObject<Block> FORGE = REGISTRY.register("forge", () -> new ForgeBlock());
	public static final RegistryObject<Block> SPELLFORGE = REGISTRY.register("spellforge", () -> new SpellforgeBlock());
	public static final RegistryObject<Block> BLAZED_ORE = REGISTRY.register("blazed_ore", () -> new BlazedOreBlock());
	public static final RegistryObject<Block> BLAZED_BLOCK = REGISTRY.register("blazed_block", () -> new BlazedBlockBlock());
	public static final RegistryObject<Block> BLAZING_PLASTIC = REGISTRY.register("blazing_plastic", () -> new BlazingPlasticBlock());
	public static final RegistryObject<Block> FLAMING_STORAGE_CUBE = REGISTRY.register("flaming_storage_cube", () -> new FlamingStorageCubeBlock());
	public static final RegistryObject<Block> ORE_PURIFIER = REGISTRY.register("ore_purifier", () -> new OrePurifierBlock());
	public static final RegistryObject<Block> GODLIUM_ORE = REGISTRY.register("godlium_ore", () -> new GodliumOreBlock());
	public static final RegistryObject<Block> GODLIUM_BLOCK = REGISTRY.register("godlium_block", () -> new GodliumBlockBlock());
	public static final RegistryObject<Block> STOPSTONE = REGISTRY.register("stopstone", () -> new StopstoneBlock());
	public static final RegistryObject<Block> SPEEDSTONE = REGISTRY.register("speedstone", () -> new SpeedstoneBlock());
	public static final RegistryObject<Block> DUPESTONE = REGISTRY.register("dupestone", () -> new DupestoneBlock());
	public static final RegistryObject<Block> ALLOY_FUSE = REGISTRY.register("alloy_fuse", () -> new AlloyFuseBlock());
	public static final RegistryObject<Block> TOTEM_FUSION_STATION = REGISTRY.register("totem_fusion_station", () -> new TotemFusionStationBlock());
	public static final RegistryObject<Block> CONSUMER = REGISTRY.register("consumer", () -> new ConsumerBlock());
	public static final RegistryObject<Block> COMPRESSOR = REGISTRY.register("compressor", () -> new CompressorBlock());
	public static final RegistryObject<Block> GODLY_STORAGE_CUBE = REGISTRY.register("godly_storage_cube", () -> new GodlyStorageCubeBlock());
	public static final RegistryObject<Block> TRIAL_BRICK = REGISTRY.register("trial_brick", () -> new TrialBrickBlock());
	public static final RegistryObject<Block> KEY_ANVIL = REGISTRY.register("key_anvil", () -> new KeyAnvilBlock());
	public static final RegistryObject<Block> HEARTSTONE_ORE = REGISTRY.register("heartstone_ore", () -> new HeartstoneOreBlock());
	public static final RegistryObject<Block> HEARTSTONE_BLOCK = REGISTRY.register("heartstone_block", () -> new HeartstoneBlockBlock());
	public static final RegistryObject<Block> STEVE_COW_LAND_PORTAL = REGISTRY.register("steve_cow_land_portal", () -> new SteveCowLandPortalBlock());
	public static final RegistryObject<Block> SNAPSTONE = REGISTRY.register("snapstone", () -> new SnapstoneBlock());
	public static final RegistryObject<Block> SNOWDIRT = REGISTRY.register("snowdirt", () -> new SnowdirtBlock());
	public static final RegistryObject<Block> COBBLESNOW = REGISTRY.register("cobblesnow", () -> new CobblesnowBlock());
	public static final RegistryObject<Block> FROSTICE = REGISTRY.register("frostice", () -> new FrosticeBlock());
	public static final RegistryObject<Block> COLD_GRASS = REGISTRY.register("cold_grass", () -> new ColdGrassBlock());
	public static final RegistryObject<Block> FROSTY_WOOD = REGISTRY.register("frosty_wood", () -> new FrostyWoodBlock());
	public static final RegistryObject<Block> FROSTY_LOG = REGISTRY.register("frosty_log", () -> new FrostyLogBlock());
	public static final RegistryObject<Block> FROSTY_PLANKS = REGISTRY.register("frosty_planks", () -> new FrostyPlanksBlock());
	public static final RegistryObject<Block> FROSTY_LEAVES = REGISTRY.register("frosty_leaves", () -> new FrostyLeavesBlock());
	public static final RegistryObject<Block> FROSTY_STAIRS = REGISTRY.register("frosty_stairs", () -> new FrostyStairsBlock());
	public static final RegistryObject<Block> FROSTY_SLAB = REGISTRY.register("frosty_slab", () -> new FrostySlabBlock());
	public static final RegistryObject<Block> FROSTY_FENCE = REGISTRY.register("frosty_fence", () -> new FrostyFenceBlock());
	public static final RegistryObject<Block> FROSTY_FENCE_GATE = REGISTRY.register("frosty_fence_gate", () -> new FrostyFenceGateBlock());
	public static final RegistryObject<Block> FROSTY_PRESSURE_PLATE = REGISTRY.register("frosty_pressure_plate", () -> new FrostyPressurePlateBlock());
	public static final RegistryObject<Block> FROSTY_BUTTON = REGISTRY.register("frosty_button", () -> new FrostyButtonBlock());
	public static final RegistryObject<Block> STEVUM_ORE = REGISTRY.register("stevum_ore", () -> new StevumOreBlock());
	public static final RegistryObject<Block> STEVUM_BLOCK = REGISTRY.register("stevum_block", () -> new StevumBlockBlock());
	public static final RegistryObject<Block> APPLEVINE = REGISTRY.register("applevine", () -> new ApplevineBlock());
	public static final RegistryObject<Block> FROSTY_SAPLING = REGISTRY.register("frosty_sapling", () -> new FrostySaplingBlock());
	public static final RegistryObject<Block> MAGICITE_CLUMP = REGISTRY.register("magicite_clump", () -> new MagiciteClumpBlock());
	public static final RegistryObject<Block> COLDSTEEL_ORE = REGISTRY.register("coldsteel_ore", () -> new ColdsteelOreBlock());
	public static final RegistryObject<Block> COLDSTEEL_BLOCK = REGISTRY.register("coldsteel_block", () -> new ColdsteelBlockBlock());
	public static final RegistryObject<Block> FROZEN_FORGE = REGISTRY.register("frozen_forge", () -> new FrozenForgeBlock());
	public static final RegistryObject<Block> ICICLE = REGISTRY.register("icicle", () -> new IcicleBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
