
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.stmwr.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.stmwr.item.ZoomAppleItem;
import net.mcreator.stmwr.item.WoodenKnifeItem;
import net.mcreator.stmwr.item.WoodenForgingHammerItem;
import net.mcreator.stmwr.item.WizardsSeaWandItem;
import net.mcreator.stmwr.item.WizardsSeaItem;
import net.mcreator.stmwr.item.UnspelledWandItem;
import net.mcreator.stmwr.item.UltriteItem;
import net.mcreator.stmwr.item.UglumItem;
import net.mcreator.stmwr.item.TotemOfWaterBreathingItem;
import net.mcreator.stmwr.item.TotemOfStrengthItem;
import net.mcreator.stmwr.item.TotemOfSpeedItem;
import net.mcreator.stmwr.item.TotemOfRegenerationItem;
import net.mcreator.stmwr.item.TotemOfNightVisionItem;
import net.mcreator.stmwr.item.TotemOfLevitationItem;
import net.mcreator.stmwr.item.TotemOfJumpBoostItem;
import net.mcreator.stmwr.item.TotemOfHealthBoostItem;
import net.mcreator.stmwr.item.TotemOfHasteItem;
import net.mcreator.stmwr.item.TotemOfGamblingItem;
import net.mcreator.stmwr.item.TotemOfFireResistanceItem;
import net.mcreator.stmwr.item.TotemOfDolphinsGraceItem;
import net.mcreator.stmwr.item.TotemBaseItem;
import net.mcreator.stmwr.item.TortillaItem;
import net.mcreator.stmwr.item.TomatoItem;
import net.mcreator.stmwr.item.TacoShellItem;
import net.mcreator.stmwr.item.TacoItem;
import net.mcreator.stmwr.item.StringCheeseItem;
import net.mcreator.stmwr.item.StorumItem;
import net.mcreator.stmwr.item.StorumForgingHammerItem;
import net.mcreator.stmwr.item.StoraliumItem;
import net.mcreator.stmwr.item.StoneForgingHammerItem;
import net.mcreator.stmwr.item.StevumSwordItem;
import net.mcreator.stmwr.item.StevumShovelItem;
import net.mcreator.stmwr.item.StevumPickaxeItem;
import net.mcreator.stmwr.item.StevumIngotItem;
import net.mcreator.stmwr.item.StevumHoeItem;
import net.mcreator.stmwr.item.StevumForgingHammerItem;
import net.mcreator.stmwr.item.StevumAxeItem;
import net.mcreator.stmwr.item.StevumArmorItem;
import net.mcreator.stmwr.item.SteveCowMeatItem;
import net.mcreator.stmwr.item.SteveCowLandItem;
import net.mcreator.stmwr.item.SteveCowHornItem;
import net.mcreator.stmwr.item.SlicedBreadItem;
import net.mcreator.stmwr.item.SausageItem;
import net.mcreator.stmwr.item.RawStorumItem;
import net.mcreator.stmwr.item.RawStevumItem;
import net.mcreator.stmwr.item.RawGodliumItem;
import net.mcreator.stmwr.item.RawColdsteelItem;
import net.mcreator.stmwr.item.RawBlazedChunkItem;
import net.mcreator.stmwr.item.PotatoChipsItem;
import net.mcreator.stmwr.item.PlasticChunkItem;
import net.mcreator.stmwr.item.PizzaSliceItem;
import net.mcreator.stmwr.item.PizzaItem;
import net.mcreator.stmwr.item.PepperoniItem;
import net.mcreator.stmwr.item.PeanutItem;
import net.mcreator.stmwr.item.NoobishTrialCoinItem;
import net.mcreator.stmwr.item.NetheriteForgingHammerItem;
import net.mcreator.stmwr.item.MinerAppleItem;
import net.mcreator.stmwr.item.MagiciteHandleItem;
import net.mcreator.stmwr.item.MagiciteForgingHammerItem;
import net.mcreator.stmwr.item.MagiciteDustItem;
import net.mcreator.stmwr.item.MagicCarrotItem;
import net.mcreator.stmwr.item.MagicAppleItem;
import net.mcreator.stmwr.item.IronForgingHammerItem;
import net.mcreator.stmwr.item.InfiniboingAppleItem;
import net.mcreator.stmwr.item.IceShardItem;
import net.mcreator.stmwr.item.HeartstoneItem;
import net.mcreator.stmwr.item.HealingAppleItem;
import net.mcreator.stmwr.item.HappyTrialCoinItem;
import net.mcreator.stmwr.item.HandbookOfDeathItem;
import net.mcreator.stmwr.item.GroundBeefItem;
import net.mcreator.stmwr.item.GoldForgingHammerItem;
import net.mcreator.stmwr.item.GodliumSwordItem;
import net.mcreator.stmwr.item.GodliumShovelItem;
import net.mcreator.stmwr.item.GodliumPickaxeItem;
import net.mcreator.stmwr.item.GodliumKnifeItem;
import net.mcreator.stmwr.item.GodliumKnifeBladeItem;
import net.mcreator.stmwr.item.GodliumIngotItem;
import net.mcreator.stmwr.item.GodliumHoeItem;
import net.mcreator.stmwr.item.GodliumForgingHammerItem;
import net.mcreator.stmwr.item.GodliumAxeItem;
import net.mcreator.stmwr.item.GodliumArmorItem;
import net.mcreator.stmwr.item.FrozenTrialheartItem;
import net.mcreator.stmwr.item.FrostySwordItem;
import net.mcreator.stmwr.item.FrostyShovelItem;
import net.mcreator.stmwr.item.FrostyPickaxeItem;
import net.mcreator.stmwr.item.FrostyHoeItem;
import net.mcreator.stmwr.item.FrostyForgingHammerItem;
import net.mcreator.stmwr.item.FrostyAxeItem;
import net.mcreator.stmwr.item.ForgersGuideItem;
import net.mcreator.stmwr.item.EmptyTrialKeyItem;
import net.mcreator.stmwr.item.DurableAppleItem;
import net.mcreator.stmwr.item.DoughItem;
import net.mcreator.stmwr.item.DirtNuggetItem;
import net.mcreator.stmwr.item.DiamondForgingHammerItem;
import net.mcreator.stmwr.item.CookBookItem;
import net.mcreator.stmwr.item.ColdsteelSwordItem;
import net.mcreator.stmwr.item.ColdsteelShovelItem;
import net.mcreator.stmwr.item.ColdsteelPickaxeItem;
import net.mcreator.stmwr.item.ColdsteelIngotItem;
import net.mcreator.stmwr.item.ColdsteelHoeItem;
import net.mcreator.stmwr.item.ColdsteelForgingHammerItem;
import net.mcreator.stmwr.item.ColdsteelAxeItem;
import net.mcreator.stmwr.item.ColdsteelArmorItem;
import net.mcreator.stmwr.item.CodexItem;
import net.mcreator.stmwr.item.CobblesnowedSwordItem;
import net.mcreator.stmwr.item.CobblesnowedShovelItem;
import net.mcreator.stmwr.item.CobblesnowedPickaxeItem;
import net.mcreator.stmwr.item.CobblesnowedHoeItem;
import net.mcreator.stmwr.item.CobblesnowedAxeItem;
import net.mcreator.stmwr.item.CobblesnowForgingHammerItem;
import net.mcreator.stmwr.item.ChocolateItem;
import net.mcreator.stmwr.item.ChickenNuggetItem;
import net.mcreator.stmwr.item.CheeseWheelItem;
import net.mcreator.stmwr.item.CheeseItem;
import net.mcreator.stmwr.item.BoingAppleItem;
import net.mcreator.stmwr.item.BlazedSwordItem;
import net.mcreator.stmwr.item.BlazedShovelItem;
import net.mcreator.stmwr.item.BlazedPickaxeItem;
import net.mcreator.stmwr.item.BlazedIngotItem;
import net.mcreator.stmwr.item.BlazedHoeItem;
import net.mcreator.stmwr.item.BlazedForgingHammerItem;
import net.mcreator.stmwr.item.BlazedAxeItem;
import net.mcreator.stmwr.item.BlazedArmorItem;
import net.mcreator.stmwr.item.ArtOfTotemancyItem;
import net.mcreator.stmwr.item.AlmightyTrialCoinItem;
import net.mcreator.stmwr.item.AlligatorToothItem;
import net.mcreator.stmwr.item.AlligatorScaleItem;
import net.mcreator.stmwr.item.AlligatorKnifeItem;
import net.mcreator.stmwr.StmwrMod;

public class StmwrModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, StmwrMod.MODID);
	public static final RegistryObject<Item> WOODEN_KNIFE = REGISTRY.register("wooden_knife", () -> new WoodenKnifeItem());
	public static final RegistryObject<Item> KITCHEN = block(StmwrModBlocks.KITCHEN);
	public static final RegistryObject<Item> NOOBISH_TRIAL_COIN = REGISTRY.register("noobish_trial_coin", () -> new NoobishTrialCoinItem());
	public static final RegistryObject<Item> HAPPY_TRIAL_COIN = REGISTRY.register("happy_trial_coin", () -> new HappyTrialCoinItem());
	public static final RegistryObject<Item> ALMIGHTY_TRIAL_COIN = REGISTRY.register("almighty_trial_coin", () -> new AlmightyTrialCoinItem());
	public static final RegistryObject<Item> PEANUT = REGISTRY.register("peanut", () -> new PeanutItem());
	public static final RegistryObject<Item> PEANUT_PLANT = block(StmwrModBlocks.PEANUT_PLANT);
	public static final RegistryObject<Item> TOMATO = REGISTRY.register("tomato", () -> new TomatoItem());
	public static final RegistryObject<Item> TOMATO_PLANT = doubleBlock(StmwrModBlocks.TOMATO_PLANT);
	public static final RegistryObject<Item> SLICED_BREAD = REGISTRY.register("sliced_bread", () -> new SlicedBreadItem());
	public static final RegistryObject<Item> CHEESE = REGISTRY.register("cheese", () -> new CheeseItem());
	public static final RegistryObject<Item> CHEESE_WHEEL = REGISTRY.register("cheese_wheel", () -> new CheeseWheelItem());
	public static final RegistryObject<Item> STRING_CHEESE = REGISTRY.register("string_cheese", () -> new StringCheeseItem());
	public static final RegistryObject<Item> PEPPERONI = REGISTRY.register("pepperoni", () -> new PepperoniItem());
	public static final RegistryObject<Item> PIZZA = REGISTRY.register("pizza", () -> new PizzaItem());
	public static final RegistryObject<Item> DOUGH = REGISTRY.register("dough", () -> new DoughItem());
	public static final RegistryObject<Item> TORTILLA = REGISTRY.register("tortilla", () -> new TortillaItem());
	public static final RegistryObject<Item> PIZZA_SLICE = REGISTRY.register("pizza_slice", () -> new PizzaSliceItem());
	public static final RegistryObject<Item> GROUND_BEEF = REGISTRY.register("ground_beef", () -> new GroundBeefItem());
	public static final RegistryObject<Item> SAUSAGE = REGISTRY.register("sausage", () -> new SausageItem());
	public static final RegistryObject<Item> CHOCOLATE = REGISTRY.register("chocolate", () -> new ChocolateItem());
	public static final RegistryObject<Item> TACO = REGISTRY.register("taco", () -> new TacoItem());
	public static final RegistryObject<Item> TACO_SHELL = REGISTRY.register("taco_shell", () -> new TacoShellItem());
	public static final RegistryObject<Item> POTATO_CHIPS = REGISTRY.register("potato_chips", () -> new PotatoChipsItem());
	public static final RegistryObject<Item> CHICKEN_NUGGET = REGISTRY.register("chicken_nugget", () -> new ChickenNuggetItem());
	public static final RegistryObject<Item> COOK_BOOK = REGISTRY.register("cook_book", () -> new CookBookItem());
	public static final RegistryObject<Item> MAGICITE_DUST = REGISTRY.register("magicite_dust", () -> new MagiciteDustItem());
	public static final RegistryObject<Item> MAGICITE_ORE = block(StmwrModBlocks.MAGICITE_ORE);
	public static final RegistryObject<Item> MAGICITE_BLOCK = block(StmwrModBlocks.MAGICITE_BLOCK);
	public static final RegistryObject<Item> MAGIC_CARROT = REGISTRY.register("magic_carrot", () -> new MagicCarrotItem());
	public static final RegistryObject<Item> DIRT_NUGGET = REGISTRY.register("dirt_nugget", () -> new DirtNuggetItem());
	public static final RegistryObject<Item> MAGICITE_HANDLE = REGISTRY.register("magicite_handle", () -> new MagiciteHandleItem());
	public static final RegistryObject<Item> UNSPELLED_WAND = REGISTRY.register("unspelled_wand", () -> new UnspelledWandItem());
	public static final RegistryObject<Item> MAGICIANS_WORKBENCH = block(StmwrModBlocks.MAGICIANS_WORKBENCH);
	public static final RegistryObject<Item> STORUM = REGISTRY.register("storum", () -> new StorumItem());
	public static final RegistryObject<Item> STORUM_ORE = block(StmwrModBlocks.STORUM_ORE);
	public static final RegistryObject<Item> STORUM_BLOCK = block(StmwrModBlocks.STORUM_BLOCK);
	public static final RegistryObject<Item> RAW_STORUM = REGISTRY.register("raw_storum", () -> new RawStorumItem());
	public static final RegistryObject<Item> STORAGE_CUBE = block(StmwrModBlocks.STORAGE_CUBE);
	public static final RegistryObject<Item> PLASTIC_CHUNK = REGISTRY.register("plastic_chunk", () -> new PlasticChunkItem());
	public static final RegistryObject<Item> PLASTIC = block(StmwrModBlocks.PLASTIC);
	public static final RegistryObject<Item> TOTEM_BASE = REGISTRY.register("totem_base", () -> new TotemBaseItem());
	public static final RegistryObject<Item> FORGE = block(StmwrModBlocks.FORGE);
	public static final RegistryObject<Item> FORGERS_GUIDE = REGISTRY.register("forgers_guide", () -> new ForgersGuideItem());
	public static final RegistryObject<Item> WOODEN_FORGING_HAMMER = REGISTRY.register("wooden_forging_hammer", () -> new WoodenForgingHammerItem());
	public static final RegistryObject<Item> STONE_FORGING_HAMMER = REGISTRY.register("stone_forging_hammer", () -> new StoneForgingHammerItem());
	public static final RegistryObject<Item> IRON_FORGING_HAMMER = REGISTRY.register("iron_forging_hammer", () -> new IronForgingHammerItem());
	public static final RegistryObject<Item> GOLD_FORGING_HAMMER = REGISTRY.register("gold_forging_hammer", () -> new GoldForgingHammerItem());
	public static final RegistryObject<Item> DIAMOND_FORGING_HAMMER = REGISTRY.register("diamond_forging_hammer", () -> new DiamondForgingHammerItem());
	public static final RegistryObject<Item> MAGICITE_FORGING_HAMMER = REGISTRY.register("magicite_forging_hammer", () -> new MagiciteForgingHammerItem());
	public static final RegistryObject<Item> STORUM_FORGING_HAMMER = REGISTRY.register("storum_forging_hammer", () -> new StorumForgingHammerItem());
	public static final RegistryObject<Item> ALLIGATOR_SPAWN_EGG = REGISTRY.register("alligator_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.ALLIGATOR, -16737997, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> ALLIGATOR_SCALE = REGISTRY.register("alligator_scale", () -> new AlligatorScaleItem());
	public static final RegistryObject<Item> ALLIGATOR_TOOTH = REGISTRY.register("alligator_tooth", () -> new AlligatorToothItem());
	public static final RegistryObject<Item> ALLIGATOR_KNIFE = REGISTRY.register("alligator_knife", () -> new AlligatorKnifeItem());
	public static final RegistryObject<Item> SPELLFORGE = block(StmwrModBlocks.SPELLFORGE);
	public static final RegistryObject<Item> CODEX = REGISTRY.register("codex", () -> new CodexItem());
	public static final RegistryObject<Item> WIZARDS_SEA = REGISTRY.register("wizards_sea", () -> new WizardsSeaItem());
	public static final RegistryObject<Item> WIZARDS_SEA_WAND = REGISTRY.register("wizards_sea_wand", () -> new WizardsSeaWandItem());
	public static final RegistryObject<Item> BLAZED_INGOT = REGISTRY.register("blazed_ingot", () -> new BlazedIngotItem());
	public static final RegistryObject<Item> BLAZED_ORE = block(StmwrModBlocks.BLAZED_ORE);
	public static final RegistryObject<Item> BLAZED_BLOCK = block(StmwrModBlocks.BLAZED_BLOCK);
	public static final RegistryObject<Item> RAW_BLAZED_CHUNK = REGISTRY.register("raw_blazed_chunk", () -> new RawBlazedChunkItem());
	public static final RegistryObject<Item> BLAZED_ARMOR_HELMET = REGISTRY.register("blazed_armor_helmet", () -> new BlazedArmorItem.Helmet());
	public static final RegistryObject<Item> BLAZED_ARMOR_CHESTPLATE = REGISTRY.register("blazed_armor_chestplate", () -> new BlazedArmorItem.Chestplate());
	public static final RegistryObject<Item> BLAZED_ARMOR_LEGGINGS = REGISTRY.register("blazed_armor_leggings", () -> new BlazedArmorItem.Leggings());
	public static final RegistryObject<Item> BLAZED_ARMOR_BOOTS = REGISTRY.register("blazed_armor_boots", () -> new BlazedArmorItem.Boots());
	public static final RegistryObject<Item> BLAZED_PICKAXE = REGISTRY.register("blazed_pickaxe", () -> new BlazedPickaxeItem());
	public static final RegistryObject<Item> BLAZED_AXE = REGISTRY.register("blazed_axe", () -> new BlazedAxeItem());
	public static final RegistryObject<Item> BLAZED_SWORD = REGISTRY.register("blazed_sword", () -> new BlazedSwordItem());
	public static final RegistryObject<Item> BLAZED_SHOVEL = REGISTRY.register("blazed_shovel", () -> new BlazedShovelItem());
	public static final RegistryObject<Item> BLAZED_HOE = REGISTRY.register("blazed_hoe", () -> new BlazedHoeItem());
	public static final RegistryObject<Item> BLAZED_FORGING_HAMMER = REGISTRY.register("blazed_forging_hammer", () -> new BlazedForgingHammerItem());
	public static final RegistryObject<Item> NETHERITE_FORGING_HAMMER = REGISTRY.register("netherite_forging_hammer", () -> new NetheriteForgingHammerItem());
	public static final RegistryObject<Item> BLAZING_PLASTIC = block(StmwrModBlocks.BLAZING_PLASTIC);
	public static final RegistryObject<Item> FLAMING_STORAGE_CUBE = block(StmwrModBlocks.FLAMING_STORAGE_CUBE);
	public static final RegistryObject<Item> ORE_PURIFIER = block(StmwrModBlocks.ORE_PURIFIER);
	public static final RegistryObject<Item> GODLIUM_INGOT = REGISTRY.register("godlium_ingot", () -> new GodliumIngotItem());
	public static final RegistryObject<Item> GODLIUM_ORE = block(StmwrModBlocks.GODLIUM_ORE);
	public static final RegistryObject<Item> GODLIUM_BLOCK = block(StmwrModBlocks.GODLIUM_BLOCK);
	public static final RegistryObject<Item> RAW_GODLIUM = REGISTRY.register("raw_godlium", () -> new RawGodliumItem());
	public static final RegistryObject<Item> GODLIUM_ARMOR_HELMET = REGISTRY.register("godlium_armor_helmet", () -> new GodliumArmorItem.Helmet());
	public static final RegistryObject<Item> GODLIUM_ARMOR_CHESTPLATE = REGISTRY.register("godlium_armor_chestplate", () -> new GodliumArmorItem.Chestplate());
	public static final RegistryObject<Item> GODLIUM_ARMOR_LEGGINGS = REGISTRY.register("godlium_armor_leggings", () -> new GodliumArmorItem.Leggings());
	public static final RegistryObject<Item> GODLIUM_ARMOR_BOOTS = REGISTRY.register("godlium_armor_boots", () -> new GodliumArmorItem.Boots());
	public static final RegistryObject<Item> GODLIUM_PICKAXE = REGISTRY.register("godlium_pickaxe", () -> new GodliumPickaxeItem());
	public static final RegistryObject<Item> GODLIUM_AXE = REGISTRY.register("godlium_axe", () -> new GodliumAxeItem());
	public static final RegistryObject<Item> GODLIUM_SWORD = REGISTRY.register("godlium_sword", () -> new GodliumSwordItem());
	public static final RegistryObject<Item> GODLIUM_SHOVEL = REGISTRY.register("godlium_shovel", () -> new GodliumShovelItem());
	public static final RegistryObject<Item> GODLIUM_HOE = REGISTRY.register("godlium_hoe", () -> new GodliumHoeItem());
	public static final RegistryObject<Item> GODLIUM_FORGING_HAMMER = REGISTRY.register("godlium_forging_hammer", () -> new GodliumForgingHammerItem());
	public static final RegistryObject<Item> STOPSTONE = block(StmwrModBlocks.STOPSTONE);
	public static final RegistryObject<Item> SPEEDSTONE = block(StmwrModBlocks.SPEEDSTONE);
	public static final RegistryObject<Item> DUPESTONE = block(StmwrModBlocks.DUPESTONE);
	public static final RegistryObject<Item> ALLOY_FUSE = block(StmwrModBlocks.ALLOY_FUSE);
	public static final RegistryObject<Item> ULTRITE = REGISTRY.register("ultrite", () -> new UltriteItem());
	public static final RegistryObject<Item> STORALIUM = REGISTRY.register("storalium", () -> new StoraliumItem());
	public static final RegistryObject<Item> TOTEM_FUSION_STATION = block(StmwrModBlocks.TOTEM_FUSION_STATION);
	public static final RegistryObject<Item> ART_OF_TOTEMANCY = REGISTRY.register("art_of_totemancy", () -> new ArtOfTotemancyItem());
	public static final RegistryObject<Item> TOTEM_OF_FIRE_RESISTANCE = REGISTRY.register("totem_of_fire_resistance", () -> new TotemOfFireResistanceItem());
	public static final RegistryObject<Item> TOTEM_OF_WATER_BREATHING = REGISTRY.register("totem_of_water_breathing", () -> new TotemOfWaterBreathingItem());
	public static final RegistryObject<Item> TOTEM_OF_SPEED = REGISTRY.register("totem_of_speed", () -> new TotemOfSpeedItem());
	public static final RegistryObject<Item> TOTEM_OF_HEALTH_BOOST = REGISTRY.register("totem_of_health_boost", () -> new TotemOfHealthBoostItem());
	public static final RegistryObject<Item> TOTEM_OF_JUMP_BOOST = REGISTRY.register("totem_of_jump_boost", () -> new TotemOfJumpBoostItem());
	public static final RegistryObject<Item> TOTEM_OF_NIGHT_VISION = REGISTRY.register("totem_of_night_vision", () -> new TotemOfNightVisionItem());
	public static final RegistryObject<Item> TOTEM_OF_HASTE = REGISTRY.register("totem_of_haste", () -> new TotemOfHasteItem());
	public static final RegistryObject<Item> TOTEM_OF_STRENGTH = REGISTRY.register("totem_of_strength", () -> new TotemOfStrengthItem());
	public static final RegistryObject<Item> TOTEM_OF_DOLPHINS_GRACE = REGISTRY.register("totem_of_dolphins_grace", () -> new TotemOfDolphinsGraceItem());
	public static final RegistryObject<Item> TOTEM_OF_LEVITATION = REGISTRY.register("totem_of_levitation", () -> new TotemOfLevitationItem());
	public static final RegistryObject<Item> TOTEM_OF_REGENERATION = REGISTRY.register("totem_of_regeneration", () -> new TotemOfRegenerationItem());
	public static final RegistryObject<Item> TOTEM_OF_GAMBLING = REGISTRY.register("totem_of_gambling", () -> new TotemOfGamblingItem());
	public static final RegistryObject<Item> CONSUMER = block(StmwrModBlocks.CONSUMER);
	public static final RegistryObject<Item> HANDBOOK_OF_DEATH = REGISTRY.register("handbook_of_death", () -> new HandbookOfDeathItem());
	public static final RegistryObject<Item> COMPRESSOR = block(StmwrModBlocks.COMPRESSOR);
	public static final RegistryObject<Item> GODLIUM_KNIFE = REGISTRY.register("godlium_knife", () -> new GodliumKnifeItem());
	public static final RegistryObject<Item> GODLIUM_KNIFE_BLADE = REGISTRY.register("godlium_knife_blade", () -> new GodliumKnifeBladeItem());
	public static final RegistryObject<Item> GODLY_STORAGE_CUBE = block(StmwrModBlocks.GODLY_STORAGE_CUBE);
	public static final RegistryObject<Item> TRIAL_BRICK = block(StmwrModBlocks.TRIAL_BRICK);
	public static final RegistryObject<Item> EMPTY_TRIAL_KEY = REGISTRY.register("empty_trial_key", () -> new EmptyTrialKeyItem());
	public static final RegistryObject<Item> KEY_ANVIL = block(StmwrModBlocks.KEY_ANVIL);
	public static final RegistryObject<Item> HEARTSTONE = REGISTRY.register("heartstone", () -> new HeartstoneItem());
	public static final RegistryObject<Item> HEARTSTONE_ORE = block(StmwrModBlocks.HEARTSTONE_ORE);
	public static final RegistryObject<Item> HEARTSTONE_BLOCK = block(StmwrModBlocks.HEARTSTONE_BLOCK);
	public static final RegistryObject<Item> FROZEN_TRIALHEART = REGISTRY.register("frozen_trialheart", () -> new FrozenTrialheartItem());
	public static final RegistryObject<Item> STEVE_COW_LAND = REGISTRY.register("steve_cow_land", () -> new SteveCowLandItem());
	public static final RegistryObject<Item> SNAPSTONE = block(StmwrModBlocks.SNAPSTONE);
	public static final RegistryObject<Item> SNOWDIRT = block(StmwrModBlocks.SNOWDIRT);
	public static final RegistryObject<Item> COBBLESNOW = block(StmwrModBlocks.COBBLESNOW);
	public static final RegistryObject<Item> FROSTICE = block(StmwrModBlocks.FROSTICE);
	public static final RegistryObject<Item> COLD_GRASS = block(StmwrModBlocks.COLD_GRASS);
	public static final RegistryObject<Item> FROSTY_WOOD = block(StmwrModBlocks.FROSTY_WOOD);
	public static final RegistryObject<Item> FROSTY_LOG = block(StmwrModBlocks.FROSTY_LOG);
	public static final RegistryObject<Item> FROSTY_PLANKS = block(StmwrModBlocks.FROSTY_PLANKS);
	public static final RegistryObject<Item> FROSTY_LEAVES = block(StmwrModBlocks.FROSTY_LEAVES);
	public static final RegistryObject<Item> FROSTY_STAIRS = block(StmwrModBlocks.FROSTY_STAIRS);
	public static final RegistryObject<Item> FROSTY_SLAB = block(StmwrModBlocks.FROSTY_SLAB);
	public static final RegistryObject<Item> FROSTY_FENCE = block(StmwrModBlocks.FROSTY_FENCE);
	public static final RegistryObject<Item> FROSTY_FENCE_GATE = block(StmwrModBlocks.FROSTY_FENCE_GATE);
	public static final RegistryObject<Item> FROSTY_PRESSURE_PLATE = block(StmwrModBlocks.FROSTY_PRESSURE_PLATE);
	public static final RegistryObject<Item> FROSTY_BUTTON = block(StmwrModBlocks.FROSTY_BUTTON);
	public static final RegistryObject<Item> STEVUM_INGOT = REGISTRY.register("stevum_ingot", () -> new StevumIngotItem());
	public static final RegistryObject<Item> STEVUM_ORE = block(StmwrModBlocks.STEVUM_ORE);
	public static final RegistryObject<Item> STEVUM_BLOCK = block(StmwrModBlocks.STEVUM_BLOCK);
	public static final RegistryObject<Item> STEVUM_PICKAXE = REGISTRY.register("stevum_pickaxe", () -> new StevumPickaxeItem());
	public static final RegistryObject<Item> STEVUM_AXE = REGISTRY.register("stevum_axe", () -> new StevumAxeItem());
	public static final RegistryObject<Item> STEVUM_SWORD = REGISTRY.register("stevum_sword", () -> new StevumSwordItem());
	public static final RegistryObject<Item> STEVUM_SHOVEL = REGISTRY.register("stevum_shovel", () -> new StevumShovelItem());
	public static final RegistryObject<Item> STEVUM_HOE = REGISTRY.register("stevum_hoe", () -> new StevumHoeItem());
	public static final RegistryObject<Item> STEVUM_ARMOR_HELMET = REGISTRY.register("stevum_armor_helmet", () -> new StevumArmorItem.Helmet());
	public static final RegistryObject<Item> STEVUM_ARMOR_CHESTPLATE = REGISTRY.register("stevum_armor_chestplate", () -> new StevumArmorItem.Chestplate());
	public static final RegistryObject<Item> STEVUM_ARMOR_LEGGINGS = REGISTRY.register("stevum_armor_leggings", () -> new StevumArmorItem.Leggings());
	public static final RegistryObject<Item> STEVUM_ARMOR_BOOTS = REGISTRY.register("stevum_armor_boots", () -> new StevumArmorItem.Boots());
	public static final RegistryObject<Item> RAW_STEVUM = REGISTRY.register("raw_stevum", () -> new RawStevumItem());
	public static final RegistryObject<Item> FROSTY_PICKAXE = REGISTRY.register("frosty_pickaxe", () -> new FrostyPickaxeItem());
	public static final RegistryObject<Item> FROSTY_AXE = REGISTRY.register("frosty_axe", () -> new FrostyAxeItem());
	public static final RegistryObject<Item> FROSTY_SWORD = REGISTRY.register("frosty_sword", () -> new FrostySwordItem());
	public static final RegistryObject<Item> FROSTY_SHOVEL = REGISTRY.register("frosty_shovel", () -> new FrostyShovelItem());
	public static final RegistryObject<Item> FROSTY_HOE = REGISTRY.register("frosty_hoe", () -> new FrostyHoeItem());
	public static final RegistryObject<Item> MAGIC_APPLE = REGISTRY.register("magic_apple", () -> new MagicAppleItem());
	public static final RegistryObject<Item> APPLEVINE = block(StmwrModBlocks.APPLEVINE);
	public static final RegistryObject<Item> FROSTY_SAPLING = block(StmwrModBlocks.FROSTY_SAPLING);
	public static final RegistryObject<Item> COBBLESNOWED_PICKAXE = REGISTRY.register("cobblesnowed_pickaxe", () -> new CobblesnowedPickaxeItem());
	public static final RegistryObject<Item> COBBLESNOWED_AXE = REGISTRY.register("cobblesnowed_axe", () -> new CobblesnowedAxeItem());
	public static final RegistryObject<Item> COBBLESNOWED_SWORD = REGISTRY.register("cobblesnowed_sword", () -> new CobblesnowedSwordItem());
	public static final RegistryObject<Item> COBBLESNOWED_SHOVEL = REGISTRY.register("cobblesnowed_shovel", () -> new CobblesnowedShovelItem());
	public static final RegistryObject<Item> COBBLESNOWED_HOE = REGISTRY.register("cobblesnowed_hoe", () -> new CobblesnowedHoeItem());
	public static final RegistryObject<Item> ZOOM_APPLE = REGISTRY.register("zoom_apple", () -> new ZoomAppleItem());
	public static final RegistryObject<Item> BOING_APPLE = REGISTRY.register("boing_apple", () -> new BoingAppleItem());
	public static final RegistryObject<Item> INFINIBOING_APPLE = REGISTRY.register("infiniboing_apple", () -> new InfiniboingAppleItem());
	public static final RegistryObject<Item> HEALING_APPLE = REGISTRY.register("healing_apple", () -> new HealingAppleItem());
	public static final RegistryObject<Item> DURABLE_APPLE = REGISTRY.register("durable_apple", () -> new DurableAppleItem());
	public static final RegistryObject<Item> MINER_APPLE = REGISTRY.register("miner_apple", () -> new MinerAppleItem());
	public static final RegistryObject<Item> MAGICITE_CLUMP = block(StmwrModBlocks.MAGICITE_CLUMP);
	public static final RegistryObject<Item> COLDSTEEL_INGOT = REGISTRY.register("coldsteel_ingot", () -> new ColdsteelIngotItem());
	public static final RegistryObject<Item> COLDSTEEL_ORE = block(StmwrModBlocks.COLDSTEEL_ORE);
	public static final RegistryObject<Item> COLDSTEEL_BLOCK = block(StmwrModBlocks.COLDSTEEL_BLOCK);
	public static final RegistryObject<Item> COLDSTEEL_PICKAXE = REGISTRY.register("coldsteel_pickaxe", () -> new ColdsteelPickaxeItem());
	public static final RegistryObject<Item> COLDSTEEL_AXE = REGISTRY.register("coldsteel_axe", () -> new ColdsteelAxeItem());
	public static final RegistryObject<Item> COLDSTEEL_SWORD = REGISTRY.register("coldsteel_sword", () -> new ColdsteelSwordItem());
	public static final RegistryObject<Item> COLDSTEEL_SHOVEL = REGISTRY.register("coldsteel_shovel", () -> new ColdsteelShovelItem());
	public static final RegistryObject<Item> COLDSTEEL_HOE = REGISTRY.register("coldsteel_hoe", () -> new ColdsteelHoeItem());
	public static final RegistryObject<Item> COLDSTEEL_ARMOR_HELMET = REGISTRY.register("coldsteel_armor_helmet", () -> new ColdsteelArmorItem.Helmet());
	public static final RegistryObject<Item> COLDSTEEL_ARMOR_CHESTPLATE = REGISTRY.register("coldsteel_armor_chestplate", () -> new ColdsteelArmorItem.Chestplate());
	public static final RegistryObject<Item> COLDSTEEL_ARMOR_LEGGINGS = REGISTRY.register("coldsteel_armor_leggings", () -> new ColdsteelArmorItem.Leggings());
	public static final RegistryObject<Item> COLDSTEEL_ARMOR_BOOTS = REGISTRY.register("coldsteel_armor_boots", () -> new ColdsteelArmorItem.Boots());
	public static final RegistryObject<Item> RAW_COLDSTEEL = REGISTRY.register("raw_coldsteel", () -> new RawColdsteelItem());
	public static final RegistryObject<Item> STEVE_COW_HORN = REGISTRY.register("steve_cow_horn", () -> new SteveCowHornItem());
	public static final RegistryObject<Item> STEVE_COW_SPAWN_EGG = REGISTRY.register("steve_cow_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.STEVE_COW, -16724788, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> STEVUM_FORGING_HAMMER = REGISTRY.register("stevum_forging_hammer", () -> new StevumForgingHammerItem());
	public static final RegistryObject<Item> COBBLESNOW_FORGING_HAMMER = REGISTRY.register("cobblesnow_forging_hammer", () -> new CobblesnowForgingHammerItem());
	public static final RegistryObject<Item> FROSTY_FORGING_HAMMER = REGISTRY.register("frosty_forging_hammer", () -> new FrostyForgingHammerItem());
	public static final RegistryObject<Item> COLDSTEEL_FORGING_HAMMER = REGISTRY.register("coldsteel_forging_hammer", () -> new ColdsteelForgingHammerItem());
	public static final RegistryObject<Item> FROZEN_FORGE = block(StmwrModBlocks.FROZEN_FORGE);
	public static final RegistryObject<Item> STEVE_COW_MEAT = REGISTRY.register("steve_cow_meat", () -> new SteveCowMeatItem());
	public static final RegistryObject<Item> PIKACHU_SPAWN_EGG = REGISTRY.register("pikachu_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.PIKACHU, -205, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> UGLUM = REGISTRY.register("uglum", () -> new UglumItem());
	public static final RegistryObject<Item> FROMBIE_SPAWN_EGG = REGISTRY.register("frombie_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.FROMBIE, -16777063, -16751002, new Item.Properties()));
	public static final RegistryObject<Item> ICE_SHARD = REGISTRY.register("ice_shard", () -> new IceShardItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
