
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.stmwr.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.stmwr.item.ZoomAppleItem;
import net.mcreator.stmwr.item.WoodenKnifeItem;
import net.mcreator.stmwr.item.WoodenForgingHammerItem;
import net.mcreator.stmwr.item.WizardsSeaWandItem;
import net.mcreator.stmwr.item.WizardsSeaItem;
import net.mcreator.stmwr.item.UraniumFuelRodItem;
import net.mcreator.stmwr.item.UraniumDustItem;
import net.mcreator.stmwr.item.UnspelledWandItem;
import net.mcreator.stmwr.item.UndeadSwordItem;
import net.mcreator.stmwr.item.UndeadShovelItem;
import net.mcreator.stmwr.item.UndeadPickaxeItem;
import net.mcreator.stmwr.item.UndeadHoeItem;
import net.mcreator.stmwr.item.UndeadAxeItem;
import net.mcreator.stmwr.item.UnclearCompoundMaterialItem;
import net.mcreator.stmwr.item.UltriteItem;
import net.mcreator.stmwr.item.UglumItem;
import net.mcreator.stmwr.item.UCMPlasticItem;
import net.mcreator.stmwr.item.TotemOfWaterBreathingItem;
import net.mcreator.stmwr.item.TotemOfTheCowItem;
import net.mcreator.stmwr.item.TotemOfStrengthItem;
import net.mcreator.stmwr.item.TotemOfStrengthIIItem;
import net.mcreator.stmwr.item.TotemOfSpeedItem;
import net.mcreator.stmwr.item.TotemOfSpeedIIItem;
import net.mcreator.stmwr.item.TotemOfRegenerationItem;
import net.mcreator.stmwr.item.TotemOfRegenerationIIItem;
import net.mcreator.stmwr.item.TotemOfNightVisionItem;
import net.mcreator.stmwr.item.TotemOfLevitationItem;
import net.mcreator.stmwr.item.TotemOfJumpBoostItem;
import net.mcreator.stmwr.item.TotemOfJumpBoostIIItem;
import net.mcreator.stmwr.item.TotemOfHealthBoostItem;
import net.mcreator.stmwr.item.TotemOfHealthBoostIIItem;
import net.mcreator.stmwr.item.TotemOfHasteItem;
import net.mcreator.stmwr.item.TotemOfHasteIIItem;
import net.mcreator.stmwr.item.TotemOfGamblingItem;
import net.mcreator.stmwr.item.TotemOfFireResistanceItem;
import net.mcreator.stmwr.item.TotemOfDolphinsGraceItem;
import net.mcreator.stmwr.item.TotemBaseItem;
import net.mcreator.stmwr.item.TortillaItem;
import net.mcreator.stmwr.item.TomatoItem;
import net.mcreator.stmwr.item.TinyUnclearCompoundMaterialItem;
import net.mcreator.stmwr.item.TimeCrystalItem;
import net.mcreator.stmwr.item.TacoShellItem;
import net.mcreator.stmwr.item.TacoItem;
import net.mcreator.stmwr.item.StringCheeseItem;
import net.mcreator.stmwr.item.StorumSpringItem;
import net.mcreator.stmwr.item.StorumRodItem;
import net.mcreator.stmwr.item.StorumPlateItem;
import net.mcreator.stmwr.item.StorumNailItem;
import net.mcreator.stmwr.item.StorumItem;
import net.mcreator.stmwr.item.StorumForgingHammerItem;
import net.mcreator.stmwr.item.StorumCogItem;
import net.mcreator.stmwr.item.StoraliumItem;
import net.mcreator.stmwr.item.StoneForgingHammerItem;
import net.mcreator.stmwr.item.StevumSwordItem;
import net.mcreator.stmwr.item.StevumSpringItem;
import net.mcreator.stmwr.item.StevumShovelItem;
import net.mcreator.stmwr.item.StevumRodItem;
import net.mcreator.stmwr.item.StevumPlateItem;
import net.mcreator.stmwr.item.StevumPickaxeItem;
import net.mcreator.stmwr.item.StevumNailItem;
import net.mcreator.stmwr.item.StevumIngotItem;
import net.mcreator.stmwr.item.StevumHoeItem;
import net.mcreator.stmwr.item.StevumForgingHammerItem;
import net.mcreator.stmwr.item.StevumCogItem;
import net.mcreator.stmwr.item.StevumAxeItem;
import net.mcreator.stmwr.item.StevumArmorItem;
import net.mcreator.stmwr.item.SteveCowMeatItem;
import net.mcreator.stmwr.item.SteveCowLandItem;
import net.mcreator.stmwr.item.SteveCowHornItem;
import net.mcreator.stmwr.item.StaffOfPikachuItem;
import net.mcreator.stmwr.item.SoullessTotemOfStrengthIIItem;
import net.mcreator.stmwr.item.SoullessTotemOfSpeedIIItem;
import net.mcreator.stmwr.item.SoullessTotemOfRegenerationIIItem;
import net.mcreator.stmwr.item.SoullessTotemOfJumpBoostIIItem;
import net.mcreator.stmwr.item.SoullessTotemOfHealthBoostIIItem;
import net.mcreator.stmwr.item.SoullessTotemOfHasteIIItem;
import net.mcreator.stmwr.item.SoulShardItem;
import net.mcreator.stmwr.item.SnowyShrapnelWandItem;
import net.mcreator.stmwr.item.SnowyShrapnelItem;
import net.mcreator.stmwr.item.SnowshotItem;
import net.mcreator.stmwr.item.SnowShardItem;
import net.mcreator.stmwr.item.SmallStoragePackItem;
import net.mcreator.stmwr.item.SlicedBreadItem;
import net.mcreator.stmwr.item.ShardOfThePresentItem;
import net.mcreator.stmwr.item.ShardOfThePastItem;
import net.mcreator.stmwr.item.ShardOfTheFutureItem;
import net.mcreator.stmwr.item.ScrapItem;
import net.mcreator.stmwr.item.SausageItem;
import net.mcreator.stmwr.item.ResearchCellItem;
import net.mcreator.stmwr.item.RawStorumItem;
import net.mcreator.stmwr.item.RawStevumItem;
import net.mcreator.stmwr.item.RawGodliumItem;
import net.mcreator.stmwr.item.RawDeadironItem;
import net.mcreator.stmwr.item.RawColdsteelItem;
import net.mcreator.stmwr.item.RawBlazedChunkItem;
import net.mcreator.stmwr.item.PureSoulShardItem;
import net.mcreator.stmwr.item.PotatoChipsItem;
import net.mcreator.stmwr.item.PoisonDartItem;
import net.mcreator.stmwr.item.PlasticChunkItem;
import net.mcreator.stmwr.item.PizzaSliceItem;
import net.mcreator.stmwr.item.PizzaItem;
import net.mcreator.stmwr.item.PepperoniItem;
import net.mcreator.stmwr.item.PeanutItem;
import net.mcreator.stmwr.item.NoobishTrialCoinItem;
import net.mcreator.stmwr.item.NetheriteForgingHammerItem;
import net.mcreator.stmwr.item.MinerAppleItem;
import net.mcreator.stmwr.item.MilitariaItem;
import net.mcreator.stmwr.item.ManupediaItem;
import net.mcreator.stmwr.item.MagiciteHandleItem;
import net.mcreator.stmwr.item.MagiciteForgingHammerItem;
import net.mcreator.stmwr.item.MagiciteDustItem;
import net.mcreator.stmwr.item.MagiciansSoulItem;
import net.mcreator.stmwr.item.MagicCarrotItem;
import net.mcreator.stmwr.item.MagicAppleItem;
import net.mcreator.stmwr.item.MREItem;
import net.mcreator.stmwr.item.LightningStaffItem;
import net.mcreator.stmwr.item.LightningInABottleItem;
import net.mcreator.stmwr.item.LightningFragmentItem;
import net.mcreator.stmwr.item.LightningBlastItem;
import net.mcreator.stmwr.item.LesserMagiciansSoulItem;
import net.mcreator.stmwr.item.IrradiatedWaterItem;
import net.mcreator.stmwr.item.IrradiatedSwordItem;
import net.mcreator.stmwr.item.IrradiatedShovelItem;
import net.mcreator.stmwr.item.IrradiatedPorkItem;
import net.mcreator.stmwr.item.IrradiatedPickaxeItem;
import net.mcreator.stmwr.item.IrradiatedPaperItem;
import net.mcreator.stmwr.item.IrradiatedMilkItem;
import net.mcreator.stmwr.item.IrradiatedLeatherItem;
import net.mcreator.stmwr.item.IrradiatedHoeItem;
import net.mcreator.stmwr.item.IrradiatedFeatherItem;
import net.mcreator.stmwr.item.IrradiatedEggItem;
import net.mcreator.stmwr.item.IrradiatedChickenItem;
import net.mcreator.stmwr.item.IrradiatedBeefItem;
import net.mcreator.stmwr.item.IrradiatedAxeItem;
import net.mcreator.stmwr.item.IronSpringItem;
import net.mcreator.stmwr.item.IronSpikeItem;
import net.mcreator.stmwr.item.IronRodItem;
import net.mcreator.stmwr.item.IronPlateItem;
import net.mcreator.stmwr.item.IronNailItem;
import net.mcreator.stmwr.item.IronForgingHammerItem;
import net.mcreator.stmwr.item.IronCogItem;
import net.mcreator.stmwr.item.InfiniboingAppleItem;
import net.mcreator.stmwr.item.InfectedArmorItem;
import net.mcreator.stmwr.item.ImpureCopperChunkItem;
import net.mcreator.stmwr.item.IceShardItem;
import net.mcreator.stmwr.item.IceKnifeItem;
import net.mcreator.stmwr.item.HeartstoneItem;
import net.mcreator.stmwr.item.HeartOfTheSteveCowItem;
import net.mcreator.stmwr.item.HealingAppleItem;
import net.mcreator.stmwr.item.HappyTrialCoinItem;
import net.mcreator.stmwr.item.HandgunRoundItem;
import net.mcreator.stmwr.item.HandgunItem;
import net.mcreator.stmwr.item.HandbookOfDeathItem;
import net.mcreator.stmwr.item.GroundBeefItem;
import net.mcreator.stmwr.item.GoopItem;
import net.mcreator.stmwr.item.GoldSpringItem;
import net.mcreator.stmwr.item.GoldRodItem;
import net.mcreator.stmwr.item.GoldPlateItem;
import net.mcreator.stmwr.item.GoldNailItem;
import net.mcreator.stmwr.item.GoldForgingHammerItem;
import net.mcreator.stmwr.item.GoldCogItem;
import net.mcreator.stmwr.item.GodliumSwordItem;
import net.mcreator.stmwr.item.GodliumShovelItem;
import net.mcreator.stmwr.item.GodliumPickaxeItem;
import net.mcreator.stmwr.item.GodliumKnifeItem;
import net.mcreator.stmwr.item.GodliumKnifeBladeItem;
import net.mcreator.stmwr.item.GodliumIngotItem;
import net.mcreator.stmwr.item.GodliumHoeItem;
import net.mcreator.stmwr.item.GodliumForgingHammerItem;
import net.mcreator.stmwr.item.GodliumAxeItem;
import net.mcreator.stmwr.item.GodliumArmorItem;
import net.mcreator.stmwr.item.FrozenTrialheartItem;
import net.mcreator.stmwr.item.FrostySwordItem;
import net.mcreator.stmwr.item.FrostyShovelItem;
import net.mcreator.stmwr.item.FrostyPickaxeItem;
import net.mcreator.stmwr.item.FrostyHoeItem;
import net.mcreator.stmwr.item.FrostyForgingHammerItem;
import net.mcreator.stmwr.item.FrostyAxeItem;
import net.mcreator.stmwr.item.FrostwatchItem;
import net.mcreator.stmwr.item.ForgersGuideItem;
import net.mcreator.stmwr.item.FangPickaxeItem;
import net.mcreator.stmwr.item.EnergyBoosterItem;
import net.mcreator.stmwr.item.EmptyTrialKeyItem;
import net.mcreator.stmwr.item.EmptyBlueprintItem;
import net.mcreator.stmwr.item.EmergencyEscapeKitItem;
import net.mcreator.stmwr.item.EmeraldForgingHammerItem;
import net.mcreator.stmwr.item.EmbroideredSwordItem;
import net.mcreator.stmwr.item.EmbroideredShovelItem;
import net.mcreator.stmwr.item.EmbroideredPickaxeItem;
import net.mcreator.stmwr.item.EmbroideredHoeItem;
import net.mcreator.stmwr.item.EmbroideredAxeItem;
import net.mcreator.stmwr.item.EmbroideredArmorItem;
import net.mcreator.stmwr.item.DurableAppleItem;
import net.mcreator.stmwr.item.DoughItem;
import net.mcreator.stmwr.item.DirtNuggetItem;
import net.mcreator.stmwr.item.DiamondForgingHammerItem;
import net.mcreator.stmwr.item.DeadironSwordItem;
import net.mcreator.stmwr.item.DeadironSpringItem;
import net.mcreator.stmwr.item.DeadironShovelItem;
import net.mcreator.stmwr.item.DeadironRodItem;
import net.mcreator.stmwr.item.DeadironPlateItem;
import net.mcreator.stmwr.item.DeadironPickaxeItem;
import net.mcreator.stmwr.item.DeadironNailItem;
import net.mcreator.stmwr.item.DeadironIngotItem;
import net.mcreator.stmwr.item.DeadironHoeItem;
import net.mcreator.stmwr.item.DeadironCogItem;
import net.mcreator.stmwr.item.DeadironAxeItem;
import net.mcreator.stmwr.item.DeadironArmorItem;
import net.mcreator.stmwr.item.DataCardItem;
import net.mcreator.stmwr.item.CrusherFangItem;
import net.mcreator.stmwr.item.CreationOrbItem;
import net.mcreator.stmwr.item.CopperSpringItem;
import net.mcreator.stmwr.item.CopperRodItem;
import net.mcreator.stmwr.item.CopperPlateItem;
import net.mcreator.stmwr.item.CopperNailItem;
import net.mcreator.stmwr.item.CopperCogItem;
import net.mcreator.stmwr.item.CookedIrradiatedPorkItem;
import net.mcreator.stmwr.item.CookedIrradiatedChickenItem;
import net.mcreator.stmwr.item.CookedIrradiatedBeefItem;
import net.mcreator.stmwr.item.CookBookItem;
import net.mcreator.stmwr.item.ColdsteelSwordItem;
import net.mcreator.stmwr.item.ColdsteelSpringItem;
import net.mcreator.stmwr.item.ColdsteelShovelItem;
import net.mcreator.stmwr.item.ColdsteelRodItem;
import net.mcreator.stmwr.item.ColdsteelPlateItem;
import net.mcreator.stmwr.item.ColdsteelPickaxeItem;
import net.mcreator.stmwr.item.ColdsteelNailItem;
import net.mcreator.stmwr.item.ColdsteelIngotItem;
import net.mcreator.stmwr.item.ColdsteelHoeItem;
import net.mcreator.stmwr.item.ColdsteelForgingHammerItem;
import net.mcreator.stmwr.item.ColdsteelCogItem;
import net.mcreator.stmwr.item.ColdsteelAxeItem;
import net.mcreator.stmwr.item.ColdsteelArmorItem;
import net.mcreator.stmwr.item.CodexItem;
import net.mcreator.stmwr.item.CobblesnowedSwordItem;
import net.mcreator.stmwr.item.CobblesnowedShovelItem;
import net.mcreator.stmwr.item.CobblesnowedPickaxeItem;
import net.mcreator.stmwr.item.CobblesnowedHoeItem;
import net.mcreator.stmwr.item.CobblesnowedAxeItem;
import net.mcreator.stmwr.item.CobblesnowForgingHammerItem;
import net.mcreator.stmwr.item.ChocolateItem;
import net.mcreator.stmwr.item.ChickenNuggetItem;
import net.mcreator.stmwr.item.ChickenGunItem;
import net.mcreator.stmwr.item.CheeseWheelItem;
import net.mcreator.stmwr.item.CheeseItem;
import net.mcreator.stmwr.item.CallOfTheCowItem;
import net.mcreator.stmwr.item.BubbleWandItem;
import net.mcreator.stmwr.item.BubbleItem;
import net.mcreator.stmwr.item.BookOfLabubuItem;
import net.mcreator.stmwr.item.BoingAppleItem;
import net.mcreator.stmwr.item.BlueprintVortexManipulationItem;
import net.mcreator.stmwr.item.BlueprintUraniumHydroponicsItem;
import net.mcreator.stmwr.item.BlueprintRepairPlantItem;
import net.mcreator.stmwr.item.BlueprintPowercellItem;
import net.mcreator.stmwr.item.BlueprintPowerToolsItem;
import net.mcreator.stmwr.item.BlueprintPortableCrucibleOvenItem;
import net.mcreator.stmwr.item.BlueprintModularArmorUpgradesItem;
import net.mcreator.stmwr.item.BlueprintModularArmorItem;
import net.mcreator.stmwr.item.BlueprintGunsItem;
import net.mcreator.stmwr.item.BlueprintConcreteMixerItem;
import net.mcreator.stmwr.item.BlueprintBookItem;
import net.mcreator.stmwr.item.BlazedSwordItem;
import net.mcreator.stmwr.item.BlazedShovelItem;
import net.mcreator.stmwr.item.BlazedPickaxeItem;
import net.mcreator.stmwr.item.BlazedIngotItem;
import net.mcreator.stmwr.item.BlazedHoeItem;
import net.mcreator.stmwr.item.BlazedForgingHammerItem;
import net.mcreator.stmwr.item.BlazedAxeItem;
import net.mcreator.stmwr.item.BlazedArmorItem;
import net.mcreator.stmwr.item.BioharvesterItem;
import net.mcreator.stmwr.item.BiobladeItem;
import net.mcreator.stmwr.item.AshenTrialheartItem;
import net.mcreator.stmwr.item.ArtOfTotemancyItem;
import net.mcreator.stmwr.item.AncientStaffItem;
import net.mcreator.stmwr.item.AlmightyTrialCoinItem;
import net.mcreator.stmwr.item.AlligatorToothItem;
import net.mcreator.stmwr.item.AlligatorScaleItem;
import net.mcreator.stmwr.item.AlligatorKnifeItem;
import net.mcreator.stmwr.item.AdvancedTotemBaseItem;
import net.mcreator.stmwr.StmwrMod;

public class StmwrModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, StmwrMod.MODID);
	public static final RegistryObject<Item> WOODEN_KNIFE = REGISTRY.register("wooden_knife", () -> new WoodenKnifeItem());
	public static final RegistryObject<Item> KITCHEN = block(StmwrModBlocks.KITCHEN);
	public static final RegistryObject<Item> NOOBISH_TRIAL_COIN = REGISTRY.register("noobish_trial_coin", () -> new NoobishTrialCoinItem());
	public static final RegistryObject<Item> HAPPY_TRIAL_COIN = REGISTRY.register("happy_trial_coin", () -> new HappyTrialCoinItem());
	public static final RegistryObject<Item> ALMIGHTY_TRIAL_COIN = REGISTRY.register("almighty_trial_coin", () -> new AlmightyTrialCoinItem());
	public static final RegistryObject<Item> PEANUT = REGISTRY.register("peanut", () -> new PeanutItem());
	public static final RegistryObject<Item> PEANUT_PLANT = block(StmwrModBlocks.PEANUT_PLANT);
	public static final RegistryObject<Item> TOMATO = REGISTRY.register("tomato", () -> new TomatoItem());
	public static final RegistryObject<Item> TOMATO_PLANT = doubleBlock(StmwrModBlocks.TOMATO_PLANT);
	public static final RegistryObject<Item> SLICED_BREAD = REGISTRY.register("sliced_bread", () -> new SlicedBreadItem());
	public static final RegistryObject<Item> CHEESE = REGISTRY.register("cheese", () -> new CheeseItem());
	public static final RegistryObject<Item> CHEESE_WHEEL = REGISTRY.register("cheese_wheel", () -> new CheeseWheelItem());
	public static final RegistryObject<Item> STRING_CHEESE = REGISTRY.register("string_cheese", () -> new StringCheeseItem());
	public static final RegistryObject<Item> PEPPERONI = REGISTRY.register("pepperoni", () -> new PepperoniItem());
	public static final RegistryObject<Item> PIZZA = REGISTRY.register("pizza", () -> new PizzaItem());
	public static final RegistryObject<Item> DOUGH = REGISTRY.register("dough", () -> new DoughItem());
	public static final RegistryObject<Item> TORTILLA = REGISTRY.register("tortilla", () -> new TortillaItem());
	public static final RegistryObject<Item> PIZZA_SLICE = REGISTRY.register("pizza_slice", () -> new PizzaSliceItem());
	public static final RegistryObject<Item> GROUND_BEEF = REGISTRY.register("ground_beef", () -> new GroundBeefItem());
	public static final RegistryObject<Item> SAUSAGE = REGISTRY.register("sausage", () -> new SausageItem());
	public static final RegistryObject<Item> CHOCOLATE = REGISTRY.register("chocolate", () -> new ChocolateItem());
	public static final RegistryObject<Item> TACO = REGISTRY.register("taco", () -> new TacoItem());
	public static final RegistryObject<Item> TACO_SHELL = REGISTRY.register("taco_shell", () -> new TacoShellItem());
	public static final RegistryObject<Item> POTATO_CHIPS = REGISTRY.register("potato_chips", () -> new PotatoChipsItem());
	public static final RegistryObject<Item> CHICKEN_NUGGET = REGISTRY.register("chicken_nugget", () -> new ChickenNuggetItem());
	public static final RegistryObject<Item> COOK_BOOK = REGISTRY.register("cook_book", () -> new CookBookItem());
	public static final RegistryObject<Item> MAGICITE_DUST = REGISTRY.register("magicite_dust", () -> new MagiciteDustItem());
	public static final RegistryObject<Item> MAGICITE_ORE = block(StmwrModBlocks.MAGICITE_ORE);
	public static final RegistryObject<Item> MAGICITE_BLOCK = block(StmwrModBlocks.MAGICITE_BLOCK);
	public static final RegistryObject<Item> MAGIC_CARROT = REGISTRY.register("magic_carrot", () -> new MagicCarrotItem());
	public static final RegistryObject<Item> DIRT_NUGGET = REGISTRY.register("dirt_nugget", () -> new DirtNuggetItem());
	public static final RegistryObject<Item> MAGICITE_HANDLE = REGISTRY.register("magicite_handle", () -> new MagiciteHandleItem());
	public static final RegistryObject<Item> UNSPELLED_WAND = REGISTRY.register("unspelled_wand", () -> new UnspelledWandItem());
	public static final RegistryObject<Item> MAGICIANS_WORKBENCH = block(StmwrModBlocks.MAGICIANS_WORKBENCH);
	public static final RegistryObject<Item> STORUM = REGISTRY.register("storum", () -> new StorumItem());
	public static final RegistryObject<Item> STORUM_ORE = block(StmwrModBlocks.STORUM_ORE);
	public static final RegistryObject<Item> STORUM_BLOCK = block(StmwrModBlocks.STORUM_BLOCK);
	public static final RegistryObject<Item> RAW_STORUM = REGISTRY.register("raw_storum", () -> new RawStorumItem());
	public static final RegistryObject<Item> STORAGE_CUBE = block(StmwrModBlocks.STORAGE_CUBE);
	public static final RegistryObject<Item> PLASTIC_CHUNK = REGISTRY.register("plastic_chunk", () -> new PlasticChunkItem());
	public static final RegistryObject<Item> PLASTIC = block(StmwrModBlocks.PLASTIC);
	public static final RegistryObject<Item> TOTEM_BASE = REGISTRY.register("totem_base", () -> new TotemBaseItem());
	public static final RegistryObject<Item> FORGE = block(StmwrModBlocks.FORGE);
	public static final RegistryObject<Item> FORGERS_GUIDE = REGISTRY.register("forgers_guide", () -> new ForgersGuideItem());
	public static final RegistryObject<Item> WOODEN_FORGING_HAMMER = REGISTRY.register("wooden_forging_hammer", () -> new WoodenForgingHammerItem());
	public static final RegistryObject<Item> STONE_FORGING_HAMMER = REGISTRY.register("stone_forging_hammer", () -> new StoneForgingHammerItem());
	public static final RegistryObject<Item> IRON_FORGING_HAMMER = REGISTRY.register("iron_forging_hammer", () -> new IronForgingHammerItem());
	public static final RegistryObject<Item> GOLD_FORGING_HAMMER = REGISTRY.register("gold_forging_hammer", () -> new GoldForgingHammerItem());
	public static final RegistryObject<Item> DIAMOND_FORGING_HAMMER = REGISTRY.register("diamond_forging_hammer", () -> new DiamondForgingHammerItem());
	public static final RegistryObject<Item> MAGICITE_FORGING_HAMMER = REGISTRY.register("magicite_forging_hammer", () -> new MagiciteForgingHammerItem());
	public static final RegistryObject<Item> STORUM_FORGING_HAMMER = REGISTRY.register("storum_forging_hammer", () -> new StorumForgingHammerItem());
	public static final RegistryObject<Item> ALLIGATOR_SPAWN_EGG = REGISTRY.register("alligator_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.ALLIGATOR, -16737997, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> ALLIGATOR_SCALE = REGISTRY.register("alligator_scale", () -> new AlligatorScaleItem());
	public static final RegistryObject<Item> ALLIGATOR_TOOTH = REGISTRY.register("alligator_tooth", () -> new AlligatorToothItem());
	public static final RegistryObject<Item> ALLIGATOR_KNIFE = REGISTRY.register("alligator_knife", () -> new AlligatorKnifeItem());
	public static final RegistryObject<Item> SPELLFORGE = block(StmwrModBlocks.SPELLFORGE);
	public static final RegistryObject<Item> CODEX = REGISTRY.register("codex", () -> new CodexItem());
	public static final RegistryObject<Item> WIZARDS_SEA = REGISTRY.register("wizards_sea", () -> new WizardsSeaItem());
	public static final RegistryObject<Item> WIZARDS_SEA_WAND = REGISTRY.register("wizards_sea_wand", () -> new WizardsSeaWandItem());
	public static final RegistryObject<Item> BLAZED_INGOT = REGISTRY.register("blazed_ingot", () -> new BlazedIngotItem());
	public static final RegistryObject<Item> BLAZED_ORE = block(StmwrModBlocks.BLAZED_ORE);
	public static final RegistryObject<Item> BLAZED_BLOCK = block(StmwrModBlocks.BLAZED_BLOCK);
	public static final RegistryObject<Item> RAW_BLAZED_CHUNK = REGISTRY.register("raw_blazed_chunk", () -> new RawBlazedChunkItem());
	public static final RegistryObject<Item> BLAZED_ARMOR_HELMET = REGISTRY.register("blazed_armor_helmet", () -> new BlazedArmorItem.Helmet());
	public static final RegistryObject<Item> BLAZED_ARMOR_CHESTPLATE = REGISTRY.register("blazed_armor_chestplate", () -> new BlazedArmorItem.Chestplate());
	public static final RegistryObject<Item> BLAZED_ARMOR_LEGGINGS = REGISTRY.register("blazed_armor_leggings", () -> new BlazedArmorItem.Leggings());
	public static final RegistryObject<Item> BLAZED_ARMOR_BOOTS = REGISTRY.register("blazed_armor_boots", () -> new BlazedArmorItem.Boots());
	public static final RegistryObject<Item> BLAZED_PICKAXE = REGISTRY.register("blazed_pickaxe", () -> new BlazedPickaxeItem());
	public static final RegistryObject<Item> BLAZED_AXE = REGISTRY.register("blazed_axe", () -> new BlazedAxeItem());
	public static final RegistryObject<Item> BLAZED_SWORD = REGISTRY.register("blazed_sword", () -> new BlazedSwordItem());
	public static final RegistryObject<Item> BLAZED_SHOVEL = REGISTRY.register("blazed_shovel", () -> new BlazedShovelItem());
	public static final RegistryObject<Item> BLAZED_HOE = REGISTRY.register("blazed_hoe", () -> new BlazedHoeItem());
	public static final RegistryObject<Item> BLAZED_FORGING_HAMMER = REGISTRY.register("blazed_forging_hammer", () -> new BlazedForgingHammerItem());
	public static final RegistryObject<Item> NETHERITE_FORGING_HAMMER = REGISTRY.register("netherite_forging_hammer", () -> new NetheriteForgingHammerItem());
	public static final RegistryObject<Item> BLAZING_PLASTIC = block(StmwrModBlocks.BLAZING_PLASTIC);
	public static final RegistryObject<Item> FLAMING_STORAGE_CUBE = block(StmwrModBlocks.FLAMING_STORAGE_CUBE);
	public static final RegistryObject<Item> ORE_PURIFIER = block(StmwrModBlocks.ORE_PURIFIER);
	public static final RegistryObject<Item> GODLIUM_INGOT = REGISTRY.register("godlium_ingot", () -> new GodliumIngotItem());
	public static final RegistryObject<Item> GODLIUM_ORE = block(StmwrModBlocks.GODLIUM_ORE);
	public static final RegistryObject<Item> GODLIUM_BLOCK = block(StmwrModBlocks.GODLIUM_BLOCK);
	public static final RegistryObject<Item> RAW_GODLIUM = REGISTRY.register("raw_godlium", () -> new RawGodliumItem());
	public static final RegistryObject<Item> GODLIUM_ARMOR_HELMET = REGISTRY.register("godlium_armor_helmet", () -> new GodliumArmorItem.Helmet());
	public static final RegistryObject<Item> GODLIUM_ARMOR_CHESTPLATE = REGISTRY.register("godlium_armor_chestplate", () -> new GodliumArmorItem.Chestplate());
	public static final RegistryObject<Item> GODLIUM_ARMOR_LEGGINGS = REGISTRY.register("godlium_armor_leggings", () -> new GodliumArmorItem.Leggings());
	public static final RegistryObject<Item> GODLIUM_ARMOR_BOOTS = REGISTRY.register("godlium_armor_boots", () -> new GodliumArmorItem.Boots());
	public static final RegistryObject<Item> GODLIUM_PICKAXE = REGISTRY.register("godlium_pickaxe", () -> new GodliumPickaxeItem());
	public static final RegistryObject<Item> GODLIUM_AXE = REGISTRY.register("godlium_axe", () -> new GodliumAxeItem());
	public static final RegistryObject<Item> GODLIUM_SWORD = REGISTRY.register("godlium_sword", () -> new GodliumSwordItem());
	public static final RegistryObject<Item> GODLIUM_SHOVEL = REGISTRY.register("godlium_shovel", () -> new GodliumShovelItem());
	public static final RegistryObject<Item> GODLIUM_HOE = REGISTRY.register("godlium_hoe", () -> new GodliumHoeItem());
	public static final RegistryObject<Item> GODLIUM_FORGING_HAMMER = REGISTRY.register("godlium_forging_hammer", () -> new GodliumForgingHammerItem());
	public static final RegistryObject<Item> STOPSTONE = block(StmwrModBlocks.STOPSTONE);
	public static final RegistryObject<Item> SPEEDSTONE = block(StmwrModBlocks.SPEEDSTONE);
	public static final RegistryObject<Item> DUPESTONE = block(StmwrModBlocks.DUPESTONE);
	public static final RegistryObject<Item> ALLOY_FUSE = block(StmwrModBlocks.ALLOY_FUSE);
	public static final RegistryObject<Item> ULTRITE = REGISTRY.register("ultrite", () -> new UltriteItem());
	public static final RegistryObject<Item> STORALIUM = REGISTRY.register("storalium", () -> new StoraliumItem());
	public static final RegistryObject<Item> TOTEM_FUSION_STATION = block(StmwrModBlocks.TOTEM_FUSION_STATION);
	public static final RegistryObject<Item> ART_OF_TOTEMANCY = REGISTRY.register("art_of_totemancy", () -> new ArtOfTotemancyItem());
	public static final RegistryObject<Item> TOTEM_OF_FIRE_RESISTANCE = REGISTRY.register("totem_of_fire_resistance", () -> new TotemOfFireResistanceItem());
	public static final RegistryObject<Item> TOTEM_OF_WATER_BREATHING = REGISTRY.register("totem_of_water_breathing", () -> new TotemOfWaterBreathingItem());
	public static final RegistryObject<Item> TOTEM_OF_SPEED = REGISTRY.register("totem_of_speed", () -> new TotemOfSpeedItem());
	public static final RegistryObject<Item> TOTEM_OF_HEALTH_BOOST = REGISTRY.register("totem_of_health_boost", () -> new TotemOfHealthBoostItem());
	public static final RegistryObject<Item> TOTEM_OF_JUMP_BOOST = REGISTRY.register("totem_of_jump_boost", () -> new TotemOfJumpBoostItem());
	public static final RegistryObject<Item> TOTEM_OF_NIGHT_VISION = REGISTRY.register("totem_of_night_vision", () -> new TotemOfNightVisionItem());
	public static final RegistryObject<Item> TOTEM_OF_HASTE = REGISTRY.register("totem_of_haste", () -> new TotemOfHasteItem());
	public static final RegistryObject<Item> TOTEM_OF_STRENGTH = REGISTRY.register("totem_of_strength", () -> new TotemOfStrengthItem());
	public static final RegistryObject<Item> TOTEM_OF_DOLPHINS_GRACE = REGISTRY.register("totem_of_dolphins_grace", () -> new TotemOfDolphinsGraceItem());
	public static final RegistryObject<Item> TOTEM_OF_LEVITATION = REGISTRY.register("totem_of_levitation", () -> new TotemOfLevitationItem());
	public static final RegistryObject<Item> TOTEM_OF_REGENERATION = REGISTRY.register("totem_of_regeneration", () -> new TotemOfRegenerationItem());
	public static final RegistryObject<Item> TOTEM_OF_GAMBLING = REGISTRY.register("totem_of_gambling", () -> new TotemOfGamblingItem());
	public static final RegistryObject<Item> CONSUMER = block(StmwrModBlocks.CONSUMER);
	public static final RegistryObject<Item> HANDBOOK_OF_DEATH = REGISTRY.register("handbook_of_death", () -> new HandbookOfDeathItem());
	public static final RegistryObject<Item> COMPRESSOR = block(StmwrModBlocks.COMPRESSOR);
	public static final RegistryObject<Item> GODLIUM_KNIFE = REGISTRY.register("godlium_knife", () -> new GodliumKnifeItem());
	public static final RegistryObject<Item> GODLIUM_KNIFE_BLADE = REGISTRY.register("godlium_knife_blade", () -> new GodliumKnifeBladeItem());
	public static final RegistryObject<Item> GODLY_STORAGE_CUBE = block(StmwrModBlocks.GODLY_STORAGE_CUBE);
	public static final RegistryObject<Item> TRIAL_BRICK = block(StmwrModBlocks.TRIAL_BRICK);
	public static final RegistryObject<Item> EMPTY_TRIAL_KEY = REGISTRY.register("empty_trial_key", () -> new EmptyTrialKeyItem());
	public static final RegistryObject<Item> KEY_ANVIL = block(StmwrModBlocks.KEY_ANVIL);
	public static final RegistryObject<Item> HEARTSTONE = REGISTRY.register("heartstone", () -> new HeartstoneItem());
	public static final RegistryObject<Item> HEARTSTONE_ORE = block(StmwrModBlocks.HEARTSTONE_ORE);
	public static final RegistryObject<Item> HEARTSTONE_BLOCK = block(StmwrModBlocks.HEARTSTONE_BLOCK);
	public static final RegistryObject<Item> FROZEN_TRIALHEART = REGISTRY.register("frozen_trialheart", () -> new FrozenTrialheartItem());
	public static final RegistryObject<Item> STEVE_COW_LAND = REGISTRY.register("steve_cow_land", () -> new SteveCowLandItem());
	public static final RegistryObject<Item> SNAPSTONE = block(StmwrModBlocks.SNAPSTONE);
	public static final RegistryObject<Item> SNOWDIRT = block(StmwrModBlocks.SNOWDIRT);
	public static final RegistryObject<Item> COBBLESNOW = block(StmwrModBlocks.COBBLESNOW);
	public static final RegistryObject<Item> FROSTICE = block(StmwrModBlocks.FROSTICE);
	public static final RegistryObject<Item> COLD_GRASS = block(StmwrModBlocks.COLD_GRASS);
	public static final RegistryObject<Item> FROSTY_WOOD = block(StmwrModBlocks.FROSTY_WOOD);
	public static final RegistryObject<Item> FROSTY_LOG = block(StmwrModBlocks.FROSTY_LOG);
	public static final RegistryObject<Item> FROSTY_PLANKS = block(StmwrModBlocks.FROSTY_PLANKS);
	public static final RegistryObject<Item> FROSTY_LEAVES = block(StmwrModBlocks.FROSTY_LEAVES);
	public static final RegistryObject<Item> FROSTY_STAIRS = block(StmwrModBlocks.FROSTY_STAIRS);
	public static final RegistryObject<Item> FROSTY_SLAB = block(StmwrModBlocks.FROSTY_SLAB);
	public static final RegistryObject<Item> FROSTY_FENCE = block(StmwrModBlocks.FROSTY_FENCE);
	public static final RegistryObject<Item> FROSTY_FENCE_GATE = block(StmwrModBlocks.FROSTY_FENCE_GATE);
	public static final RegistryObject<Item> FROSTY_PRESSURE_PLATE = block(StmwrModBlocks.FROSTY_PRESSURE_PLATE);
	public static final RegistryObject<Item> FROSTY_BUTTON = block(StmwrModBlocks.FROSTY_BUTTON);
	public static final RegistryObject<Item> STEVUM_INGOT = REGISTRY.register("stevum_ingot", () -> new StevumIngotItem());
	public static final RegistryObject<Item> STEVUM_ORE = block(StmwrModBlocks.STEVUM_ORE);
	public static final RegistryObject<Item> STEVUM_BLOCK = block(StmwrModBlocks.STEVUM_BLOCK);
	public static final RegistryObject<Item> STEVUM_PICKAXE = REGISTRY.register("stevum_pickaxe", () -> new StevumPickaxeItem());
	public static final RegistryObject<Item> STEVUM_AXE = REGISTRY.register("stevum_axe", () -> new StevumAxeItem());
	public static final RegistryObject<Item> STEVUM_SWORD = REGISTRY.register("stevum_sword", () -> new StevumSwordItem());
	public static final RegistryObject<Item> STEVUM_SHOVEL = REGISTRY.register("stevum_shovel", () -> new StevumShovelItem());
	public static final RegistryObject<Item> STEVUM_HOE = REGISTRY.register("stevum_hoe", () -> new StevumHoeItem());
	public static final RegistryObject<Item> STEVUM_ARMOR_HELMET = REGISTRY.register("stevum_armor_helmet", () -> new StevumArmorItem.Helmet());
	public static final RegistryObject<Item> STEVUM_ARMOR_CHESTPLATE = REGISTRY.register("stevum_armor_chestplate", () -> new StevumArmorItem.Chestplate());
	public static final RegistryObject<Item> STEVUM_ARMOR_LEGGINGS = REGISTRY.register("stevum_armor_leggings", () -> new StevumArmorItem.Leggings());
	public static final RegistryObject<Item> STEVUM_ARMOR_BOOTS = REGISTRY.register("stevum_armor_boots", () -> new StevumArmorItem.Boots());
	public static final RegistryObject<Item> RAW_STEVUM = REGISTRY.register("raw_stevum", () -> new RawStevumItem());
	public static final RegistryObject<Item> FROSTY_PICKAXE = REGISTRY.register("frosty_pickaxe", () -> new FrostyPickaxeItem());
	public static final RegistryObject<Item> FROSTY_AXE = REGISTRY.register("frosty_axe", () -> new FrostyAxeItem());
	public static final RegistryObject<Item> FROSTY_SWORD = REGISTRY.register("frosty_sword", () -> new FrostySwordItem());
	public static final RegistryObject<Item> FROSTY_SHOVEL = REGISTRY.register("frosty_shovel", () -> new FrostyShovelItem());
	public static final RegistryObject<Item> FROSTY_HOE = REGISTRY.register("frosty_hoe", () -> new FrostyHoeItem());
	public static final RegistryObject<Item> MAGIC_APPLE = REGISTRY.register("magic_apple", () -> new MagicAppleItem());
	public static final RegistryObject<Item> APPLEVINE = block(StmwrModBlocks.APPLEVINE);
	public static final RegistryObject<Item> FROSTY_SAPLING = block(StmwrModBlocks.FROSTY_SAPLING);
	public static final RegistryObject<Item> COBBLESNOWED_PICKAXE = REGISTRY.register("cobblesnowed_pickaxe", () -> new CobblesnowedPickaxeItem());
	public static final RegistryObject<Item> COBBLESNOWED_AXE = REGISTRY.register("cobblesnowed_axe", () -> new CobblesnowedAxeItem());
	public static final RegistryObject<Item> COBBLESNOWED_SWORD = REGISTRY.register("cobblesnowed_sword", () -> new CobblesnowedSwordItem());
	public static final RegistryObject<Item> COBBLESNOWED_SHOVEL = REGISTRY.register("cobblesnowed_shovel", () -> new CobblesnowedShovelItem());
	public static final RegistryObject<Item> COBBLESNOWED_HOE = REGISTRY.register("cobblesnowed_hoe", () -> new CobblesnowedHoeItem());
	public static final RegistryObject<Item> ZOOM_APPLE = REGISTRY.register("zoom_apple", () -> new ZoomAppleItem());
	public static final RegistryObject<Item> BOING_APPLE = REGISTRY.register("boing_apple", () -> new BoingAppleItem());
	public static final RegistryObject<Item> INFINIBOING_APPLE = REGISTRY.register("infiniboing_apple", () -> new InfiniboingAppleItem());
	public static final RegistryObject<Item> HEALING_APPLE = REGISTRY.register("healing_apple", () -> new HealingAppleItem());
	public static final RegistryObject<Item> DURABLE_APPLE = REGISTRY.register("durable_apple", () -> new DurableAppleItem());
	public static final RegistryObject<Item> MINER_APPLE = REGISTRY.register("miner_apple", () -> new MinerAppleItem());
	public static final RegistryObject<Item> MAGICITE_CLUMP = block(StmwrModBlocks.MAGICITE_CLUMP);
	public static final RegistryObject<Item> COLDSTEEL_INGOT = REGISTRY.register("coldsteel_ingot", () -> new ColdsteelIngotItem());
	public static final RegistryObject<Item> COLDSTEEL_ORE = block(StmwrModBlocks.COLDSTEEL_ORE);
	public static final RegistryObject<Item> COLDSTEEL_BLOCK = block(StmwrModBlocks.COLDSTEEL_BLOCK);
	public static final RegistryObject<Item> COLDSTEEL_PICKAXE = REGISTRY.register("coldsteel_pickaxe", () -> new ColdsteelPickaxeItem());
	public static final RegistryObject<Item> COLDSTEEL_AXE = REGISTRY.register("coldsteel_axe", () -> new ColdsteelAxeItem());
	public static final RegistryObject<Item> COLDSTEEL_SWORD = REGISTRY.register("coldsteel_sword", () -> new ColdsteelSwordItem());
	public static final RegistryObject<Item> COLDSTEEL_SHOVEL = REGISTRY.register("coldsteel_shovel", () -> new ColdsteelShovelItem());
	public static final RegistryObject<Item> COLDSTEEL_HOE = REGISTRY.register("coldsteel_hoe", () -> new ColdsteelHoeItem());
	public static final RegistryObject<Item> COLDSTEEL_ARMOR_HELMET = REGISTRY.register("coldsteel_armor_helmet", () -> new ColdsteelArmorItem.Helmet());
	public static final RegistryObject<Item> COLDSTEEL_ARMOR_CHESTPLATE = REGISTRY.register("coldsteel_armor_chestplate", () -> new ColdsteelArmorItem.Chestplate());
	public static final RegistryObject<Item> COLDSTEEL_ARMOR_LEGGINGS = REGISTRY.register("coldsteel_armor_leggings", () -> new ColdsteelArmorItem.Leggings());
	public static final RegistryObject<Item> COLDSTEEL_ARMOR_BOOTS = REGISTRY.register("coldsteel_armor_boots", () -> new ColdsteelArmorItem.Boots());
	public static final RegistryObject<Item> RAW_COLDSTEEL = REGISTRY.register("raw_coldsteel", () -> new RawColdsteelItem());
	public static final RegistryObject<Item> STEVE_COW_HORN = REGISTRY.register("steve_cow_horn", () -> new SteveCowHornItem());
	public static final RegistryObject<Item> STEVE_COW_SPAWN_EGG = REGISTRY.register("steve_cow_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.STEVE_COW, -16724788, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> STEVUM_FORGING_HAMMER = REGISTRY.register("stevum_forging_hammer", () -> new StevumForgingHammerItem());
	public static final RegistryObject<Item> COBBLESNOW_FORGING_HAMMER = REGISTRY.register("cobblesnow_forging_hammer", () -> new CobblesnowForgingHammerItem());
	public static final RegistryObject<Item> FROSTY_FORGING_HAMMER = REGISTRY.register("frosty_forging_hammer", () -> new FrostyForgingHammerItem());
	public static final RegistryObject<Item> COLDSTEEL_FORGING_HAMMER = REGISTRY.register("coldsteel_forging_hammer", () -> new ColdsteelForgingHammerItem());
	public static final RegistryObject<Item> FROZEN_FORGE = block(StmwrModBlocks.FROZEN_FORGE);
	public static final RegistryObject<Item> STEVE_COW_MEAT = REGISTRY.register("steve_cow_meat", () -> new SteveCowMeatItem());
	public static final RegistryObject<Item> PIKACHU_SPAWN_EGG = REGISTRY.register("pikachu_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.PIKACHU, -205, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> UGLUM = REGISTRY.register("uglum", () -> new UglumItem());
	public static final RegistryObject<Item> FROMBIE_SPAWN_EGG = REGISTRY.register("frombie_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.FROMBIE, -16777063, -16751002, new Item.Properties()));
	public static final RegistryObject<Item> ICE_SHARD = REGISTRY.register("ice_shard", () -> new IceShardItem());
	public static final RegistryObject<Item> CRUSHER_FANG = REGISTRY.register("crusher_fang", () -> new CrusherFangItem());
	public static final RegistryObject<Item> CRUSHER_SPAWN_EGG = REGISTRY.register("crusher_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.CRUSHER, -10066330, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> HORDEBEAST_SPAWN_EGG = REGISTRY.register("hordebeast_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.HORDEBEAST, -10066177, -16737895, new Item.Properties()));
	public static final RegistryObject<Item> FANG_PICKAXE = REGISTRY.register("fang_pickaxe", () -> new FangPickaxeItem());
	public static final RegistryObject<Item> ICE_KNIFE = REGISTRY.register("ice_knife", () -> new IceKnifeItem());
	public static final RegistryObject<Item> ICICLE = block(StmwrModBlocks.ICICLE);
	public static final RegistryObject<Item> LESSER_MAGICIANS_SOUL = REGISTRY.register("lesser_magicians_soul", () -> new LesserMagiciansSoulItem());
	public static final RegistryObject<Item> LESSER_WIZARD_SPAWN_EGG = REGISTRY.register("lesser_wizard_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.LESSER_WIZARD, -16724788, -6710887, new Item.Properties()));
	public static final RegistryObject<Item> SOUL_SHARD = REGISTRY.register("soul_shard", () -> new SoulShardItem());
	public static final RegistryObject<Item> SNOWSHOT = REGISTRY.register("snowshot", () -> new SnowshotItem());
	public static final RegistryObject<Item> FROSTWATCH = REGISTRY.register("frostwatch", () -> new FrostwatchItem());
	public static final RegistryObject<Item> SNOWY_SHRAPNEL = REGISTRY.register("snowy_shrapnel", () -> new SnowyShrapnelItem());
	public static final RegistryObject<Item> SNOWY_SHRAPNEL_WAND = REGISTRY.register("snowy_shrapnel_wand", () -> new SnowyShrapnelWandItem());
	public static final RegistryObject<Item> SNOW_SHARD = REGISTRY.register("snow_shard", () -> new SnowShardItem());
	public static final RegistryObject<Item> LIGHTNING_FRAGMENT = REGISTRY.register("lightning_fragment", () -> new LightningFragmentItem());
	public static final RegistryObject<Item> LIGHTNING_CULTIST_SPAWN_EGG = REGISTRY.register("lightning_cultist_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.LIGHTNING_CULTIST, -3342592, -1, new Item.Properties()));
	public static final RegistryObject<Item> LIGHTNING_IN_A_BOTTLE = REGISTRY.register("lightning_in_a_bottle", () -> new LightningInABottleItem());
	public static final RegistryObject<Item> LIGHTNING_WIZARD_SPAWN_EGG = REGISTRY.register("lightning_wizard_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.LIGHTNING_WIZARD, -205, -6711040, new Item.Properties()));
	public static final RegistryObject<Item> LIGHTNING_BLAST = REGISTRY.register("lightning_blast", () -> new LightningBlastItem());
	public static final RegistryObject<Item> ENERGY_BOOSTER = REGISTRY.register("energy_booster", () -> new EnergyBoosterItem());
	public static final RegistryObject<Item> LIGHTNING_STAFF = REGISTRY.register("lightning_staff", () -> new LightningStaffItem());
	public static final RegistryObject<Item> SMALL_STORAGE_PACK = REGISTRY.register("small_storage_pack", () -> new SmallStoragePackItem());
	public static final RegistryObject<Item> CAMPER_SPAWN_EGG = REGISTRY.register("camper_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.CAMPER, -10066432, -16751002, new Item.Properties()));
	public static final RegistryObject<Item> CALL_OF_THE_COW = REGISTRY.register("call_of_the_cow", () -> new CallOfTheCowItem());
	public static final RegistryObject<Item> HEART_OF_THE_STEVE_COW = REGISTRY.register("heart_of_the_steve_cow", () -> new HeartOfTheSteveCowItem());
	public static final RegistryObject<Item> GIANT_STEVE_COW_SPAWN_EGG = REGISTRY.register("giant_steve_cow_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.GIANT_STEVE_COW, -16777012, -6750055, new Item.Properties()));
	public static final RegistryObject<Item> STAFF_OF_PIKACHU = REGISTRY.register("staff_of_pikachu", () -> new StaffOfPikachuItem());
	public static final RegistryObject<Item> TOTEM_OF_THE_COW = REGISTRY.register("totem_of_the_cow", () -> new TotemOfTheCowItem());
	public static final RegistryObject<Item> IRON_SPIKE = REGISTRY.register("iron_spike", () -> new IronSpikeItem());
	public static final RegistryObject<Item> SMOOTH_SNAPSTONE = block(StmwrModBlocks.SMOOTH_SNAPSTONE);
	public static final RegistryObject<Item> SNAPSTONE_SLAB = block(StmwrModBlocks.SNAPSTONE_SLAB);
	public static final RegistryObject<Item> EMBROIDERED_ARMOR_HELMET = REGISTRY.register("embroidered_armor_helmet", () -> new EmbroideredArmorItem.Helmet());
	public static final RegistryObject<Item> EMBROIDERED_ARMOR_CHESTPLATE = REGISTRY.register("embroidered_armor_chestplate", () -> new EmbroideredArmorItem.Chestplate());
	public static final RegistryObject<Item> EMBROIDERED_ARMOR_LEGGINGS = REGISTRY.register("embroidered_armor_leggings", () -> new EmbroideredArmorItem.Leggings());
	public static final RegistryObject<Item> EMBROIDERED_ARMOR_BOOTS = REGISTRY.register("embroidered_armor_boots", () -> new EmbroideredArmorItem.Boots());
	public static final RegistryObject<Item> EMBROIDERED_PICKAXE = REGISTRY.register("embroidered_pickaxe", () -> new EmbroideredPickaxeItem());
	public static final RegistryObject<Item> EMBROIDERED_AXE = REGISTRY.register("embroidered_axe", () -> new EmbroideredAxeItem());
	public static final RegistryObject<Item> EMBROIDERED_SWORD = REGISTRY.register("embroidered_sword", () -> new EmbroideredSwordItem());
	public static final RegistryObject<Item> EMBROIDERED_SHOVEL = REGISTRY.register("embroidered_shovel", () -> new EmbroideredShovelItem());
	public static final RegistryObject<Item> EMBROIDERED_HOE = REGISTRY.register("embroidered_hoe", () -> new EmbroideredHoeItem());
	public static final RegistryObject<Item> EMERALD_FORGING_HAMMER = REGISTRY.register("emerald_forging_hammer", () -> new EmeraldForgingHammerItem());
	public static final RegistryObject<Item> ASHEN_TRIALHEART = REGISTRY.register("ashen_trialheart", () -> new AshenTrialheartItem());
	public static final RegistryObject<Item> UNTOUCHED_SOIL = block(StmwrModBlocks.UNTOUCHED_SOIL);
	public static final RegistryObject<Item> DEAD_GRASS = block(StmwrModBlocks.DEAD_GRASS);
	public static final RegistryObject<Item> IRRADIATED_COBBLESTONE = block(StmwrModBlocks.IRRADIATED_COBBLESTONE);
	public static final RegistryObject<Item> IRRADIATED_STONE = block(StmwrModBlocks.IRRADIATED_STONE);
	public static final RegistryObject<Item> IRRADIATED_PICKAXE = REGISTRY.register("irradiated_pickaxe", () -> new IrradiatedPickaxeItem());
	public static final RegistryObject<Item> IRRADIATED_AXE = REGISTRY.register("irradiated_axe", () -> new IrradiatedAxeItem());
	public static final RegistryObject<Item> IRRADIATED_SWORD = REGISTRY.register("irradiated_sword", () -> new IrradiatedSwordItem());
	public static final RegistryObject<Item> IRRADIATED_SHOVEL = REGISTRY.register("irradiated_shovel", () -> new IrradiatedShovelItem());
	public static final RegistryObject<Item> IRRADIATED_HOE = REGISTRY.register("irradiated_hoe", () -> new IrradiatedHoeItem());
	public static final RegistryObject<Item> DEADIRON_INGOT = REGISTRY.register("deadiron_ingot", () -> new DeadironIngotItem());
	public static final RegistryObject<Item> DEADIRON_ORE = block(StmwrModBlocks.DEADIRON_ORE);
	public static final RegistryObject<Item> DEADIRON_BLOCK = block(StmwrModBlocks.DEADIRON_BLOCK);
	public static final RegistryObject<Item> DEADIRON_PICKAXE = REGISTRY.register("deadiron_pickaxe", () -> new DeadironPickaxeItem());
	public static final RegistryObject<Item> DEADIRON_AXE = REGISTRY.register("deadiron_axe", () -> new DeadironAxeItem());
	public static final RegistryObject<Item> DEADIRON_SWORD = REGISTRY.register("deadiron_sword", () -> new DeadironSwordItem());
	public static final RegistryObject<Item> DEADIRON_SHOVEL = REGISTRY.register("deadiron_shovel", () -> new DeadironShovelItem());
	public static final RegistryObject<Item> DEADIRON_HOE = REGISTRY.register("deadiron_hoe", () -> new DeadironHoeItem());
	public static final RegistryObject<Item> DEADIRON_ARMOR_HELMET = REGISTRY.register("deadiron_armor_helmet", () -> new DeadironArmorItem.Helmet());
	public static final RegistryObject<Item> DEADIRON_ARMOR_CHESTPLATE = REGISTRY.register("deadiron_armor_chestplate", () -> new DeadironArmorItem.Chestplate());
	public static final RegistryObject<Item> DEADIRON_ARMOR_LEGGINGS = REGISTRY.register("deadiron_armor_leggings", () -> new DeadironArmorItem.Leggings());
	public static final RegistryObject<Item> DEADIRON_ARMOR_BOOTS = REGISTRY.register("deadiron_armor_boots", () -> new DeadironArmorItem.Boots());
	public static final RegistryObject<Item> RAW_DEADIRON = REGISTRY.register("raw_deadiron", () -> new RawDeadironItem());
	public static final RegistryObject<Item> IRRADIATED_STONE_SLAB = block(StmwrModBlocks.IRRADIATED_STONE_SLAB);
	public static final RegistryObject<Item> DEAD_WOOD = block(StmwrModBlocks.DEAD_WOOD);
	public static final RegistryObject<Item> DEAD_LOG = block(StmwrModBlocks.DEAD_LOG);
	public static final RegistryObject<Item> DEAD_PLANKS = block(StmwrModBlocks.DEAD_PLANKS);
	public static final RegistryObject<Item> DEAD_STAIRS = block(StmwrModBlocks.DEAD_STAIRS);
	public static final RegistryObject<Item> DEAD_SLAB = block(StmwrModBlocks.DEAD_SLAB);
	public static final RegistryObject<Item> DEAD_FENCE = block(StmwrModBlocks.DEAD_FENCE);
	public static final RegistryObject<Item> DEAD_FENCE_GATE = block(StmwrModBlocks.DEAD_FENCE_GATE);
	public static final RegistryObject<Item> DEAD_PRESSURE_PLATE = block(StmwrModBlocks.DEAD_PRESSURE_PLATE);
	public static final RegistryObject<Item> DEAD_BUTTON = block(StmwrModBlocks.DEAD_BUTTON);
	public static final RegistryObject<Item> UNDEAD_PICKAXE = REGISTRY.register("undead_pickaxe", () -> new UndeadPickaxeItem());
	public static final RegistryObject<Item> UNDEAD_AXE = REGISTRY.register("undead_axe", () -> new UndeadAxeItem());
	public static final RegistryObject<Item> UNDEAD_SWORD = REGISTRY.register("undead_sword", () -> new UndeadSwordItem());
	public static final RegistryObject<Item> UNDEAD_SHOVEL = REGISTRY.register("undead_shovel", () -> new UndeadShovelItem());
	public static final RegistryObject<Item> UNDEAD_HOE = REGISTRY.register("undead_hoe", () -> new UndeadHoeItem());
	public static final RegistryObject<Item> SMOOTH_IRRADIATED_STONE = block(StmwrModBlocks.SMOOTH_IRRADIATED_STONE);
	public static final RegistryObject<Item> DOOMSAND = block(StmwrModBlocks.DOOMSAND);
	public static final RegistryObject<Item> DOOMGLASS = block(StmwrModBlocks.DOOMGLASS);
	public static final RegistryObject<Item> IRRADIATED_WATER_BUCKET = REGISTRY.register("irradiated_water_bucket", () -> new IrradiatedWaterItem());
	public static final RegistryObject<Item> ASH = block(StmwrModBlocks.ASH);
	public static final RegistryObject<Item> MILITARIA = REGISTRY.register("militaria", () -> new MilitariaItem());
	public static final RegistryObject<Item> URANIUM_DUST = REGISTRY.register("uranium_dust", () -> new UraniumDustItem());
	public static final RegistryObject<Item> URANIUM_ORE = block(StmwrModBlocks.URANIUM_ORE);
	public static final RegistryObject<Item> URANIUM_BLOCK = block(StmwrModBlocks.URANIUM_BLOCK);
	public static final RegistryObject<Item> GOLD_ROCKS = block(StmwrModBlocks.GOLD_ROCKS);
	public static final RegistryObject<Item> IMPURE_COPPER = block(StmwrModBlocks.IMPURE_COPPER);
	public static final RegistryObject<Item> IMPURE_COPPER_CHUNK = REGISTRY.register("impure_copper_chunk", () -> new ImpureCopperChunkItem());
	public static final RegistryObject<Item> IRRADIATED_PORK = REGISTRY.register("irradiated_pork", () -> new IrradiatedPorkItem());
	public static final RegistryObject<Item> INFECTED_PIG_SPAWN_EGG = REGISTRY.register("infected_pig_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.INFECTED_PIG, -3407668, -39169, new Item.Properties()));
	public static final RegistryObject<Item> COOKED_IRRADIATED_PORK = REGISTRY.register("cooked_irradiated_pork", () -> new CookedIrradiatedPorkItem());
	public static final RegistryObject<Item> INFECTED_COW_SPAWN_EGG = REGISTRY.register("infected_cow_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.INFECTED_COW, -16777216, -16724992, new Item.Properties()));
	public static final RegistryObject<Item> IRRADIATED_LEATHER = REGISTRY.register("irradiated_leather", () -> new IrradiatedLeatherItem());
	public static final RegistryObject<Item> IRRADIATED_MILK = REGISTRY.register("irradiated_milk", () -> new IrradiatedMilkItem());
	public static final RegistryObject<Item> IRRADIATED_BEEF = REGISTRY.register("irradiated_beef", () -> new IrradiatedBeefItem());
	public static final RegistryObject<Item> COOKED_IRRADIATED_BEEF = REGISTRY.register("cooked_irradiated_beef", () -> new CookedIrradiatedBeefItem());
	public static final RegistryObject<Item> INFECTED_ARMOR_HELMET = REGISTRY.register("infected_armor_helmet", () -> new InfectedArmorItem.Helmet());
	public static final RegistryObject<Item> INFECTED_ARMOR_CHESTPLATE = REGISTRY.register("infected_armor_chestplate", () -> new InfectedArmorItem.Chestplate());
	public static final RegistryObject<Item> INFECTED_ARMOR_LEGGINGS = REGISTRY.register("infected_armor_leggings", () -> new InfectedArmorItem.Leggings());
	public static final RegistryObject<Item> INFECTED_ARMOR_BOOTS = REGISTRY.register("infected_armor_boots", () -> new InfectedArmorItem.Boots());
	public static final RegistryObject<Item> INFECTED_CHICKEN_SPAWN_EGG = REGISTRY.register("infected_chicken_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.INFECTED_CHICKEN, -16711936, -256, new Item.Properties()));
	public static final RegistryObject<Item> IRRADIATED_EGG = REGISTRY.register("irradiated_egg", () -> new IrradiatedEggItem());
	public static final RegistryObject<Item> IRRADIATED_FEATHER = REGISTRY.register("irradiated_feather", () -> new IrradiatedFeatherItem());
	public static final RegistryObject<Item> COOKED_IRRADIATED_CHICKEN = REGISTRY.register("cooked_irradiated_chicken", () -> new CookedIrradiatedChickenItem());
	public static final RegistryObject<Item> IRRADIATED_CHICKEN = REGISTRY.register("irradiated_chicken", () -> new IrradiatedChickenItem());
	public static final RegistryObject<Item> GOOP = REGISTRY.register("goop", () -> new GoopItem());
	public static final RegistryObject<Item> GOOLING_SPAWN_EGG = REGISTRY.register("gooling_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.GOOLING, -16777216, -1, new Item.Properties()));
	public static final RegistryObject<Item> IRRADIATED_PAPER = REGISTRY.register("irradiated_paper", () -> new IrradiatedPaperItem());
	public static final RegistryObject<Item> SURVIVOR_SPAWN_EGG = REGISTRY.register("survivor_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.SURVIVOR, -10066432, -256, new Item.Properties()));
	public static final RegistryObject<Item> SOLDIER_SPAWN_EGG = REGISTRY.register("soldier_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.SOLDIER, -13421824, -16751053, new Item.Properties()));
	public static final RegistryObject<Item> HANDGUN_ROUND = REGISTRY.register("handgun_round", () -> new HandgunRoundItem());
	public static final RegistryObject<Item> HANDGUN = REGISTRY.register("handgun", () -> new HandgunItem());
	public static final RegistryObject<Item> MRE = REGISTRY.register("mre", () -> new MREItem());
	public static final RegistryObject<Item> SCRAP = REGISTRY.register("scrap", () -> new ScrapItem());
	public static final RegistryObject<Item> BLOCK_OF_SCRAP = block(StmwrModBlocks.BLOCK_OF_SCRAP);
	public static final RegistryObject<Item> UNCLEAR_COMPOUND_MATERIAL = REGISTRY.register("unclear_compound_material", () -> new UnclearCompoundMaterialItem());
	public static final RegistryObject<Item> TINY_UNCLEAR_COMPOUND_MATERIAL = REGISTRY.register("tiny_unclear_compound_material", () -> new TinyUnclearCompoundMaterialItem());
	public static final RegistryObject<Item> DEADIRON_CASING = block(StmwrModBlocks.DEADIRON_CASING);
	public static final RegistryObject<Item> PURIFIER_MK_2 = block(StmwrModBlocks.PURIFIER_MK_2);
	public static final RegistryObject<Item> DOOMFORGE_ACCESS_POINT = block(StmwrModBlocks.DOOMFORGE_ACCESS_POINT);
	public static final RegistryObject<Item> URANIUM_FUEL_ROD = REGISTRY.register("uranium_fuel_rod", () -> new UraniumFuelRodItem());
	public static final RegistryObject<Item> RADIATION_REMOVAL_PLANT_ACCESS_POINT = block(StmwrModBlocks.RADIATION_REMOVAL_PLANT_ACCESS_POINT);
	public static final RegistryObject<Item> EMERGENCY_ESCAPE_KIT = REGISTRY.register("emergency_escape_kit", () -> new EmergencyEscapeKitItem());
	public static final RegistryObject<Item> BUBBLE = REGISTRY.register("bubble", () -> new BubbleItem());
	public static final RegistryObject<Item> BUBBLE_WAND = REGISTRY.register("bubble_wand", () -> new BubbleWandItem());
	public static final RegistryObject<Item> SURVIVORS_MARKET = block(StmwrModBlocks.SURVIVORS_MARKET);
	public static final RegistryObject<Item> MANUFACTURING_PLANT_ACCESS_POINT = block(StmwrModBlocks.MANUFACTURING_PLANT_ACCESS_POINT);
	public static final RegistryObject<Item> MANUPEDIA = REGISTRY.register("manupedia", () -> new ManupediaItem());
	public static final RegistryObject<Item> COPPER_NAIL = REGISTRY.register("copper_nail", () -> new CopperNailItem());
	public static final RegistryObject<Item> GOLD_NAIL = REGISTRY.register("gold_nail", () -> new GoldNailItem());
	public static final RegistryObject<Item> IRON_NAIL = REGISTRY.register("iron_nail", () -> new IronNailItem());
	public static final RegistryObject<Item> STEVUM_NAIL = REGISTRY.register("stevum_nail", () -> new StevumNailItem());
	public static final RegistryObject<Item> COLDSTEEL_NAIL = REGISTRY.register("coldsteel_nail", () -> new ColdsteelNailItem());
	public static final RegistryObject<Item> DEADIRON_NAIL = REGISTRY.register("deadiron_nail", () -> new DeadironNailItem());
	public static final RegistryObject<Item> COPPER_ROD = REGISTRY.register("copper_rod", () -> new CopperRodItem());
	public static final RegistryObject<Item> GOLD_ROD = REGISTRY.register("gold_rod", () -> new GoldRodItem());
	public static final RegistryObject<Item> IRON_ROD = REGISTRY.register("iron_rod", () -> new IronRodItem());
	public static final RegistryObject<Item> STEVUM_ROD = REGISTRY.register("stevum_rod", () -> new StevumRodItem());
	public static final RegistryObject<Item> COLDSTEEL_ROD = REGISTRY.register("coldsteel_rod", () -> new ColdsteelRodItem());
	public static final RegistryObject<Item> DEADIRON_ROD = REGISTRY.register("deadiron_rod", () -> new DeadironRodItem());
	public static final RegistryObject<Item> COPPER_PLATE = REGISTRY.register("copper_plate", () -> new CopperPlateItem());
	public static final RegistryObject<Item> GOLD_PLATE = REGISTRY.register("gold_plate", () -> new GoldPlateItem());
	public static final RegistryObject<Item> IRON_PLATE = REGISTRY.register("iron_plate", () -> new IronPlateItem());
	public static final RegistryObject<Item> STEVUM_PLATE = REGISTRY.register("stevum_plate", () -> new StevumPlateItem());
	public static final RegistryObject<Item> COLDSTEEL_PLATE = REGISTRY.register("coldsteel_plate", () -> new ColdsteelPlateItem());
	public static final RegistryObject<Item> DEADIRON_PLATE = REGISTRY.register("deadiron_plate", () -> new DeadironPlateItem());
	public static final RegistryObject<Item> COPPER_COG = REGISTRY.register("copper_cog", () -> new CopperCogItem());
	public static final RegistryObject<Item> GOLD_COG = REGISTRY.register("gold_cog", () -> new GoldCogItem());
	public static final RegistryObject<Item> IRON_COG = REGISTRY.register("iron_cog", () -> new IronCogItem());
	public static final RegistryObject<Item> STEVUM_COG = REGISTRY.register("stevum_cog", () -> new StevumCogItem());
	public static final RegistryObject<Item> COLDSTEEL_COG = REGISTRY.register("coldsteel_cog", () -> new ColdsteelCogItem());
	public static final RegistryObject<Item> DEADIRON_COG = REGISTRY.register("deadiron_cog", () -> new DeadironCogItem());
	public static final RegistryObject<Item> COPPER_SPRING = REGISTRY.register("copper_spring", () -> new CopperSpringItem());
	public static final RegistryObject<Item> GOLD_SPRING = REGISTRY.register("gold_spring", () -> new GoldSpringItem());
	public static final RegistryObject<Item> IRON_SPRING = REGISTRY.register("iron_spring", () -> new IronSpringItem());
	public static final RegistryObject<Item> STEVUM_SPRING = REGISTRY.register("stevum_spring", () -> new StevumSpringItem());
	public static final RegistryObject<Item> COLDSTEEL_SPRING = REGISTRY.register("coldsteel_spring", () -> new ColdsteelSpringItem());
	public static final RegistryObject<Item> DEADIRON_SPRING = REGISTRY.register("deadiron_spring", () -> new DeadironSpringItem());
	public static final RegistryObject<Item> STORUM_NAIL = REGISTRY.register("storum_nail", () -> new StorumNailItem());
	public static final RegistryObject<Item> STORUM_ROD = REGISTRY.register("storum_rod", () -> new StorumRodItem());
	public static final RegistryObject<Item> STORUM_PLATE = REGISTRY.register("storum_plate", () -> new StorumPlateItem());
	public static final RegistryObject<Item> STORUM_COG = REGISTRY.register("storum_cog", () -> new StorumCogItem());
	public static final RegistryObject<Item> STORUM_SPRING = REGISTRY.register("storum_spring", () -> new StorumSpringItem());
	public static final RegistryObject<Item> CHICKEN_GUN = REGISTRY.register("chicken_gun", () -> new ChickenGunItem());
	public static final RegistryObject<Item> SHARD_OF_THE_PAST = REGISTRY.register("shard_of_the_past", () -> new ShardOfThePastItem());
	public static final RegistryObject<Item> SHARD_OF_THE_PRESENT = REGISTRY.register("shard_of_the_present", () -> new ShardOfThePresentItem());
	public static final RegistryObject<Item> SHARD_OF_THE_FUTURE = REGISTRY.register("shard_of_the_future", () -> new ShardOfTheFutureItem());
	public static final RegistryObject<Item> TIME_CRYSTAL = REGISTRY.register("time_crystal", () -> new TimeCrystalItem());
	public static final RegistryObject<Item> UNDEAD_SOUL_SPAWN_EGG = REGISTRY.register("undead_soul_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.UNDEAD_SOUL, -16777216, -10066330, new Item.Properties()));
	public static final RegistryObject<Item> CORPSEPUPPET_SPAWN_EGG = REGISTRY.register("corpsepuppet_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.CORPSEPUPPET, -6750208, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> ANCIENT_WIZARD_SPAWN_EGG = REGISTRY.register("ancient_wizard_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.ANCIENT_WIZARD, -10092544, -10092442, new Item.Properties()));
	public static final RegistryObject<Item> MAGICIANS_SOUL = REGISTRY.register("magicians_soul", () -> new MagiciansSoulItem());
	public static final RegistryObject<Item> ANCIENT_STAFF = REGISTRY.register("ancient_staff", () -> new AncientStaffItem());
	public static final RegistryObject<Item> POISON_DART = REGISTRY.register("poison_dart", () -> new PoisonDartItem());
	public static final RegistryObject<Item> COFFIN = block(StmwrModBlocks.COFFIN);
	public static final RegistryObject<Item> MAGICAL_CASING = block(StmwrModBlocks.MAGICAL_CASING);
	public static final RegistryObject<Item> SOUL_MANIPULATOR_ACCESS_POINT = block(StmwrModBlocks.SOUL_MANIPULATOR_ACCESS_POINT);
	public static final RegistryObject<Item> PURE_SOUL_SHARD = REGISTRY.register("pure_soul_shard", () -> new PureSoulShardItem());
	public static final RegistryObject<Item> UCM_PLASTIC = REGISTRY.register("ucm_plastic", () -> new UCMPlasticItem());
	public static final RegistryObject<Item> ADVANCED_TOTEM_BASE = REGISTRY.register("advanced_totem_base", () -> new AdvancedTotemBaseItem());
	public static final RegistryObject<Item> SOULLESS_TOTEM_OF_SPEED_II = REGISTRY.register("soulless_totem_of_speed_ii", () -> new SoullessTotemOfSpeedIIItem());
	public static final RegistryObject<Item> SOULLESS_TOTEM_OF_HEALTH_BOOST_II = REGISTRY.register("soulless_totem_of_health_boost_ii", () -> new SoullessTotemOfHealthBoostIIItem());
	public static final RegistryObject<Item> SOULLESS_TOTEM_OF_JUMP_BOOST_II = REGISTRY.register("soulless_totem_of_jump_boost_ii", () -> new SoullessTotemOfJumpBoostIIItem());
	public static final RegistryObject<Item> SOULLESS_TOTEM_OF_HASTE_II = REGISTRY.register("soulless_totem_of_haste_ii", () -> new SoullessTotemOfHasteIIItem());
	public static final RegistryObject<Item> SOULLESS_TOTEM_OF_STRENGTH_II = REGISTRY.register("soulless_totem_of_strength_ii", () -> new SoullessTotemOfStrengthIIItem());
	public static final RegistryObject<Item> SOULLESS_TOTEM_OF_REGENERATION_II = REGISTRY.register("soulless_totem_of_regeneration_ii", () -> new SoullessTotemOfRegenerationIIItem());
	public static final RegistryObject<Item> RITUAL_STONE = block(StmwrModBlocks.RITUAL_STONE);
	public static final RegistryObject<Item> BOOK_OF_LABUBU = REGISTRY.register("book_of_labubu", () -> new BookOfLabubuItem());
	public static final RegistryObject<Item> TOTEM_OF_SPEED_II = REGISTRY.register("totem_of_speed_ii", () -> new TotemOfSpeedIIItem());
	public static final RegistryObject<Item> TOTEM_OF_HEALTH_BOOST_II = REGISTRY.register("totem_of_health_boost_ii", () -> new TotemOfHealthBoostIIItem());
	public static final RegistryObject<Item> TOTEM_OF_JUMP_BOOST_II = REGISTRY.register("totem_of_jump_boost_ii", () -> new TotemOfJumpBoostIIItem());
	public static final RegistryObject<Item> TOTEM_OF_HASTE_II = REGISTRY.register("totem_of_haste_ii", () -> new TotemOfHasteIIItem());
	public static final RegistryObject<Item> TOTEM_OF_STRENGTH_II = REGISTRY.register("totem_of_strength_ii", () -> new TotemOfStrengthIIItem());
	public static final RegistryObject<Item> TOTEM_OF_REGENERATION_II = REGISTRY.register("totem_of_regeneration_ii", () -> new TotemOfRegenerationIIItem());
	public static final RegistryObject<Item> CREATION_ORB = REGISTRY.register("creation_orb", () -> new CreationOrbItem());
	public static final RegistryObject<Item> DESIGNER_ACCESS_POINT = block(StmwrModBlocks.DESIGNER_ACCESS_POINT);
	public static final RegistryObject<Item> EMPTY_BLUEPRINT = REGISTRY.register("empty_blueprint", () -> new EmptyBlueprintItem());
	public static final RegistryObject<Item> ITEM_RESEACHER_ACCESS_POINT = block(StmwrModBlocks.ITEM_RESEACHER_ACCESS_POINT);
	public static final RegistryObject<Item> RESEARCH_CELL = REGISTRY.register("research_cell", () -> new ResearchCellItem());
	public static final RegistryObject<Item> DATA_CARD = REGISTRY.register("data_card", () -> new DataCardItem());
	public static final RegistryObject<Item> BIOHARVESTER = REGISTRY.register("bioharvester", () -> new BioharvesterItem());
	public static final RegistryObject<Item> BIOBLADE = REGISTRY.register("bioblade", () -> new BiobladeItem());
	public static final RegistryObject<Item> BLUEPRINT_BOOK = REGISTRY.register("blueprint_book", () -> new BlueprintBookItem());
	public static final RegistryObject<Item> BLUEPRINT_CONCRETE_MIXER = REGISTRY.register("blueprint_concrete_mixer", () -> new BlueprintConcreteMixerItem());
	public static final RegistryObject<Item> BLUEPRINT_GUNS = REGISTRY.register("blueprint_guns", () -> new BlueprintGunsItem());
	public static final RegistryObject<Item> BLUEPRINT_URANIUM_HYDROPONICS = REGISTRY.register("blueprint_uranium_hydroponics", () -> new BlueprintUraniumHydroponicsItem());
	public static final RegistryObject<Item> BLUEPRINT_POWERCELL = REGISTRY.register("blueprint_powercell", () -> new BlueprintPowercellItem());
	public static final RegistryObject<Item> BLUEPRINT_MODULAR_ARMOR = REGISTRY.register("blueprint_modular_armor", () -> new BlueprintModularArmorItem());
	public static final RegistryObject<Item> BLUEPRINT_MODULAR_ARMOR_UPGRADES = REGISTRY.register("blueprint_modular_armor_upgrades", () -> new BlueprintModularArmorUpgradesItem());
	public static final RegistryObject<Item> BLUEPRINT_POWER_TOOLS = REGISTRY.register("blueprint_power_tools", () -> new BlueprintPowerToolsItem());
	public static final RegistryObject<Item> BLUEPRINT_REPAIR_PLANT = REGISTRY.register("blueprint_repair_plant", () -> new BlueprintRepairPlantItem());
	public static final RegistryObject<Item> BLUEPRINT_VORTEX_MANIPULATION = REGISTRY.register("blueprint_vortex_manipulation", () -> new BlueprintVortexManipulationItem());
	public static final RegistryObject<Item> BLUEPRINT_PORTABLE_CRUCIBLE_OVEN = REGISTRY.register("blueprint_portable_crucible_oven", () -> new BlueprintPortableCrucibleOvenItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
