
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.stmwr.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.extensions.IForgeMenuType;

import net.minecraft.world.inventory.MenuType;

import net.mcreator.stmwr.world.inventory.WizardsSeaRecipeMenu;
import net.mcreator.stmwr.world.inventory.TrialBricksRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfWaterBreathingRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfStrengthRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfSpeedRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfRegenerationRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfNightVisionRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfLevitationRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfJumpBoostRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfHealthBoostRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfHasteRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfGamblingRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfFireResistanceRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemOfDolphinsGraceRecipeMenu;
import net.mcreator.stmwr.world.inventory.TotemFusionStationGUIMenu;
import net.mcreator.stmwr.world.inventory.TortillaRecipeMenu;
import net.mcreator.stmwr.world.inventory.ToolsAndArmorMenu;
import net.mcreator.stmwr.world.inventory.TacoShellRecipeMenu;
import net.mcreator.stmwr.world.inventory.TacoRecipeMenu;
import net.mcreator.stmwr.world.inventory.StorageCubeGUIMenu;
import net.mcreator.stmwr.world.inventory.StopstoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.SpellsP1Menu;
import net.mcreator.stmwr.world.inventory.SpellforgeGUIMenu;
import net.mcreator.stmwr.world.inventory.SpeedstoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.SausageRecipeMenu;
import net.mcreator.stmwr.world.inventory.PotatoChipsRecipeMenu;
import net.mcreator.stmwr.world.inventory.PizzaSliceRecipeMenu;
import net.mcreator.stmwr.world.inventory.PizzaRecipeMenu;
import net.mcreator.stmwr.world.inventory.PepperoniRecipeMenu;
import net.mcreator.stmwr.world.inventory.OrePurifierGUIMenu;
import net.mcreator.stmwr.world.inventory.MagiciansWorkbenchGUIMenu;
import net.mcreator.stmwr.world.inventory.KitchenGUIMenu;
import net.mcreator.stmwr.world.inventory.KeyAnvilGUIMenu;
import net.mcreator.stmwr.world.inventory.HomePageMenu;
import net.mcreator.stmwr.world.inventory.HODTheWitherMenu;
import net.mcreator.stmwr.world.inventory.HODOverworldMenu;
import net.mcreator.stmwr.world.inventory.HODHomePageMenu;
import net.mcreator.stmwr.world.inventory.HODCategoriesMenu;
import net.mcreator.stmwr.world.inventory.GroundBeefRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodlyStorageCubeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodlyStorageCubeGUIMenu;
import net.mcreator.stmwr.world.inventory.GodliumSwordRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumShovelRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumPickaxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumKnifeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumHoeRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumHelmetRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumGearRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumChestplateRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.GodliumAxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.FrozenForgeGUIMenu;
import net.mcreator.stmwr.world.inventory.ForgeGUIMenu;
import net.mcreator.stmwr.world.inventory.FlamingStorageCubeRecipeMenu;
import net.mcreator.stmwr.world.inventory.FlamingStorageCubeGUIMenu;
import net.mcreator.stmwr.world.inventory.DupestoneRecipeMenu;
import net.mcreator.stmwr.world.inventory.CookBookHomePageMenu;
import net.mcreator.stmwr.world.inventory.ConsumerGUIMenu;
import net.mcreator.stmwr.world.inventory.CompressorGUIMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelSwordRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelShovelRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelPickaxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelHoeRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelHelmetRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelGearRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelChestplateRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.ColdsteelAxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.CodexHomePageMenu;
import net.mcreator.stmwr.world.inventory.ChocolateRecipeMenu;
import net.mcreator.stmwr.world.inventory.ChickenNuggetRecipeMenu;
import net.mcreator.stmwr.world.inventory.CheeseStickRecipeMenu;
import net.mcreator.stmwr.world.inventory.CategoriesMenu;
import net.mcreator.stmwr.world.inventory.BlocksPageMenu;
import net.mcreator.stmwr.world.inventory.BlazingPlasticRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedSwordRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedShovelRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedPickaxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedLeggingsRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedHoeRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedHelmetRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedGearRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedChestplateRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedBootsRecipeMenu;
import net.mcreator.stmwr.world.inventory.BlazedAxeRecipeMenu;
import net.mcreator.stmwr.world.inventory.AlloyFuseGUIMenu;
import net.mcreator.stmwr.world.inventory.AlligatorKnifeRecipeMenu;
import net.mcreator.stmwr.world.inventory.AOTTotemsP1Menu;
import net.mcreator.stmwr.world.inventory.AOTHomePageMenu;
import net.mcreator.stmwr.StmwrMod;

public class StmwrModMenus {
	public static final DeferredRegister<MenuType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.MENU_TYPES, StmwrMod.MODID);
	public static final RegistryObject<MenuType<KitchenGUIMenu>> KITCHEN_GUI = REGISTRY.register("kitchen_gui", () -> IForgeMenuType.create(KitchenGUIMenu::new));
	public static final RegistryObject<MenuType<CookBookHomePageMenu>> COOK_BOOK_HOME_PAGE = REGISTRY.register("cook_book_home_page", () -> IForgeMenuType.create(CookBookHomePageMenu::new));
	public static final RegistryObject<MenuType<ChickenNuggetRecipeMenu>> CHICKEN_NUGGET_RECIPE = REGISTRY.register("chicken_nugget_recipe", () -> IForgeMenuType.create(ChickenNuggetRecipeMenu::new));
	public static final RegistryObject<MenuType<PotatoChipsRecipeMenu>> POTATO_CHIPS_RECIPE = REGISTRY.register("potato_chips_recipe", () -> IForgeMenuType.create(PotatoChipsRecipeMenu::new));
	public static final RegistryObject<MenuType<TacoRecipeMenu>> TACO_RECIPE = REGISTRY.register("taco_recipe", () -> IForgeMenuType.create(TacoRecipeMenu::new));
	public static final RegistryObject<MenuType<TacoShellRecipeMenu>> TACO_SHELL_RECIPE = REGISTRY.register("taco_shell_recipe", () -> IForgeMenuType.create(TacoShellRecipeMenu::new));
	public static final RegistryObject<MenuType<ChocolateRecipeMenu>> CHOCOLATE_RECIPE = REGISTRY.register("chocolate_recipe", () -> IForgeMenuType.create(ChocolateRecipeMenu::new));
	public static final RegistryObject<MenuType<SausageRecipeMenu>> SAUSAGE_RECIPE = REGISTRY.register("sausage_recipe", () -> IForgeMenuType.create(SausageRecipeMenu::new));
	public static final RegistryObject<MenuType<GroundBeefRecipeMenu>> GROUND_BEEF_RECIPE = REGISTRY.register("ground_beef_recipe", () -> IForgeMenuType.create(GroundBeefRecipeMenu::new));
	public static final RegistryObject<MenuType<PizzaSliceRecipeMenu>> PIZZA_SLICE_RECIPE = REGISTRY.register("pizza_slice_recipe", () -> IForgeMenuType.create(PizzaSliceRecipeMenu::new));
	public static final RegistryObject<MenuType<TortillaRecipeMenu>> TORTILLA_RECIPE = REGISTRY.register("tortilla_recipe", () -> IForgeMenuType.create(TortillaRecipeMenu::new));
	public static final RegistryObject<MenuType<PizzaRecipeMenu>> PIZZA_RECIPE = REGISTRY.register("pizza_recipe", () -> IForgeMenuType.create(PizzaRecipeMenu::new));
	public static final RegistryObject<MenuType<PepperoniRecipeMenu>> PEPPERONI_RECIPE = REGISTRY.register("pepperoni_recipe", () -> IForgeMenuType.create(PepperoniRecipeMenu::new));
	public static final RegistryObject<MenuType<CheeseStickRecipeMenu>> CHEESE_STICK_RECIPE = REGISTRY.register("cheese_stick_recipe", () -> IForgeMenuType.create(CheeseStickRecipeMenu::new));
	public static final RegistryObject<MenuType<MagiciansWorkbenchGUIMenu>> MAGICIANS_WORKBENCH_GUI = REGISTRY.register("magicians_workbench_gui", () -> IForgeMenuType.create(MagiciansWorkbenchGUIMenu::new));
	public static final RegistryObject<MenuType<StorageCubeGUIMenu>> STORAGE_CUBE_GUI = REGISTRY.register("storage_cube_gui", () -> IForgeMenuType.create(StorageCubeGUIMenu::new));
	public static final RegistryObject<MenuType<ForgeGUIMenu>> FORGE_GUI = REGISTRY.register("forge_gui", () -> IForgeMenuType.create(ForgeGUIMenu::new));
	public static final RegistryObject<MenuType<HomePageMenu>> HOME_PAGE = REGISTRY.register("home_page", () -> IForgeMenuType.create(HomePageMenu::new));
	public static final RegistryObject<MenuType<CategoriesMenu>> CATEGORIES = REGISTRY.register("categories", () -> IForgeMenuType.create(CategoriesMenu::new));
	public static final RegistryObject<MenuType<ToolsAndArmorMenu>> TOOLS_AND_ARMOR = REGISTRY.register("tools_and_armor", () -> IForgeMenuType.create(ToolsAndArmorMenu::new));
	public static final RegistryObject<MenuType<BlocksPageMenu>> BLOCKS_PAGE = REGISTRY.register("blocks_page", () -> IForgeMenuType.create(BlocksPageMenu::new));
	public static final RegistryObject<MenuType<AlligatorKnifeRecipeMenu>> ALLIGATOR_KNIFE_RECIPE = REGISTRY.register("alligator_knife_recipe", () -> IForgeMenuType.create(AlligatorKnifeRecipeMenu::new));
	public static final RegistryObject<MenuType<SpellforgeGUIMenu>> SPELLFORGE_GUI = REGISTRY.register("spellforge_gui", () -> IForgeMenuType.create(SpellforgeGUIMenu::new));
	public static final RegistryObject<MenuType<CodexHomePageMenu>> CODEX_HOME_PAGE = REGISTRY.register("codex_home_page", () -> IForgeMenuType.create(CodexHomePageMenu::new));
	public static final RegistryObject<MenuType<SpellsP1Menu>> SPELLS_P_1 = REGISTRY.register("spells_p_1", () -> IForgeMenuType.create(SpellsP1Menu::new));
	public static final RegistryObject<MenuType<WizardsSeaRecipeMenu>> WIZARDS_SEA_RECIPE = REGISTRY.register("wizards_sea_recipe", () -> IForgeMenuType.create(WizardsSeaRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedGearRecipeMenu>> BLAZED_GEAR_RECIPE = REGISTRY.register("blazed_gear_recipe", () -> IForgeMenuType.create(BlazedGearRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedHelmetRecipeMenu>> BLAZED_HELMET_RECIPE = REGISTRY.register("blazed_helmet_recipe", () -> IForgeMenuType.create(BlazedHelmetRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedChestplateRecipeMenu>> BLAZED_CHESTPLATE_RECIPE = REGISTRY.register("blazed_chestplate_recipe", () -> IForgeMenuType.create(BlazedChestplateRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedLeggingsRecipeMenu>> BLAZED_LEGGINGS_RECIPE = REGISTRY.register("blazed_leggings_recipe", () -> IForgeMenuType.create(BlazedLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedBootsRecipeMenu>> BLAZED_BOOTS_RECIPE = REGISTRY.register("blazed_boots_recipe", () -> IForgeMenuType.create(BlazedBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedSwordRecipeMenu>> BLAZED_SWORD_RECIPE = REGISTRY.register("blazed_sword_recipe", () -> IForgeMenuType.create(BlazedSwordRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedAxeRecipeMenu>> BLAZED_AXE_RECIPE = REGISTRY.register("blazed_axe_recipe", () -> IForgeMenuType.create(BlazedAxeRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedPickaxeRecipeMenu>> BLAZED_PICKAXE_RECIPE = REGISTRY.register("blazed_pickaxe_recipe", () -> IForgeMenuType.create(BlazedPickaxeRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedShovelRecipeMenu>> BLAZED_SHOVEL_RECIPE = REGISTRY.register("blazed_shovel_recipe", () -> IForgeMenuType.create(BlazedShovelRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazedHoeRecipeMenu>> BLAZED_HOE_RECIPE = REGISTRY.register("blazed_hoe_recipe", () -> IForgeMenuType.create(BlazedHoeRecipeMenu::new));
	public static final RegistryObject<MenuType<BlazingPlasticRecipeMenu>> BLAZING_PLASTIC_RECIPE = REGISTRY.register("blazing_plastic_recipe", () -> IForgeMenuType.create(BlazingPlasticRecipeMenu::new));
	public static final RegistryObject<MenuType<FlamingStorageCubeGUIMenu>> FLAMING_STORAGE_CUBE_GUI = REGISTRY.register("flaming_storage_cube_gui", () -> IForgeMenuType.create(FlamingStorageCubeGUIMenu::new));
	public static final RegistryObject<MenuType<FlamingStorageCubeRecipeMenu>> FLAMING_STORAGE_CUBE_RECIPE = REGISTRY.register("flaming_storage_cube_recipe", () -> IForgeMenuType.create(FlamingStorageCubeRecipeMenu::new));
	public static final RegistryObject<MenuType<OrePurifierGUIMenu>> ORE_PURIFIER_GUI = REGISTRY.register("ore_purifier_gui", () -> IForgeMenuType.create(OrePurifierGUIMenu::new));
	public static final RegistryObject<MenuType<GodliumGearRecipeMenu>> GODLIUM_GEAR_RECIPE = REGISTRY.register("godlium_gear_recipe", () -> IForgeMenuType.create(GodliumGearRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumHelmetRecipeMenu>> GODLIUM_HELMET_RECIPE = REGISTRY.register("godlium_helmet_recipe", () -> IForgeMenuType.create(GodliumHelmetRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumChestplateRecipeMenu>> GODLIUM_CHESTPLATE_RECIPE = REGISTRY.register("godlium_chestplate_recipe", () -> IForgeMenuType.create(GodliumChestplateRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumLeggingsRecipeMenu>> GODLIUM_LEGGINGS_RECIPE = REGISTRY.register("godlium_leggings_recipe", () -> IForgeMenuType.create(GodliumLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumBootsRecipeMenu>> GODLIUM_BOOTS_RECIPE = REGISTRY.register("godlium_boots_recipe", () -> IForgeMenuType.create(GodliumBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumSwordRecipeMenu>> GODLIUM_SWORD_RECIPE = REGISTRY.register("godlium_sword_recipe", () -> IForgeMenuType.create(GodliumSwordRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumPickaxeRecipeMenu>> GODLIUM_PICKAXE_RECIPE = REGISTRY.register("godlium_pickaxe_recipe", () -> IForgeMenuType.create(GodliumPickaxeRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumAxeRecipeMenu>> GODLIUM_AXE_RECIPE = REGISTRY.register("godlium_axe_recipe", () -> IForgeMenuType.create(GodliumAxeRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumShovelRecipeMenu>> GODLIUM_SHOVEL_RECIPE = REGISTRY.register("godlium_shovel_recipe", () -> IForgeMenuType.create(GodliumShovelRecipeMenu::new));
	public static final RegistryObject<MenuType<GodliumHoeRecipeMenu>> GODLIUM_HOE_RECIPE = REGISTRY.register("godlium_hoe_recipe", () -> IForgeMenuType.create(GodliumHoeRecipeMenu::new));
	public static final RegistryObject<MenuType<StopstoneRecipeMenu>> STOPSTONE_RECIPE = REGISTRY.register("stopstone_recipe", () -> IForgeMenuType.create(StopstoneRecipeMenu::new));
	public static final RegistryObject<MenuType<SpeedstoneRecipeMenu>> SPEEDSTONE_RECIPE = REGISTRY.register("speedstone_recipe", () -> IForgeMenuType.create(SpeedstoneRecipeMenu::new));
	public static final RegistryObject<MenuType<DupestoneRecipeMenu>> DUPESTONE_RECIPE = REGISTRY.register("dupestone_recipe", () -> IForgeMenuType.create(DupestoneRecipeMenu::new));
	public static final RegistryObject<MenuType<AlloyFuseGUIMenu>> ALLOY_FUSE_GUI = REGISTRY.register("alloy_fuse_gui", () -> IForgeMenuType.create(AlloyFuseGUIMenu::new));
	public static final RegistryObject<MenuType<TotemFusionStationGUIMenu>> TOTEM_FUSION_STATION_GUI = REGISTRY.register("totem_fusion_station_gui", () -> IForgeMenuType.create(TotemFusionStationGUIMenu::new));
	public static final RegistryObject<MenuType<AOTHomePageMenu>> AOT_HOME_PAGE = REGISTRY.register("aot_home_page", () -> IForgeMenuType.create(AOTHomePageMenu::new));
	public static final RegistryObject<MenuType<AOTTotemsP1Menu>> AOT_TOTEMS_P_1 = REGISTRY.register("aot_totems_p_1", () -> IForgeMenuType.create(AOTTotemsP1Menu::new));
	public static final RegistryObject<MenuType<TotemOfFireResistanceRecipeMenu>> TOTEM_OF_FIRE_RESISTANCE_RECIPE = REGISTRY.register("totem_of_fire_resistance_recipe", () -> IForgeMenuType.create(TotemOfFireResistanceRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfSpeedRecipeMenu>> TOTEM_OF_SPEED_RECIPE = REGISTRY.register("totem_of_speed_recipe", () -> IForgeMenuType.create(TotemOfSpeedRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfWaterBreathingRecipeMenu>> TOTEM_OF_WATER_BREATHING_RECIPE = REGISTRY.register("totem_of_water_breathing_recipe", () -> IForgeMenuType.create(TotemOfWaterBreathingRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfHasteRecipeMenu>> TOTEM_OF_HASTE_RECIPE = REGISTRY.register("totem_of_haste_recipe", () -> IForgeMenuType.create(TotemOfHasteRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfHealthBoostRecipeMenu>> TOTEM_OF_HEALTH_BOOST_RECIPE = REGISTRY.register("totem_of_health_boost_recipe", () -> IForgeMenuType.create(TotemOfHealthBoostRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfJumpBoostRecipeMenu>> TOTEM_OF_JUMP_BOOST_RECIPE = REGISTRY.register("totem_of_jump_boost_recipe", () -> IForgeMenuType.create(TotemOfJumpBoostRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfNightVisionRecipeMenu>> TOTEM_OF_NIGHT_VISION_RECIPE = REGISTRY.register("totem_of_night_vision_recipe", () -> IForgeMenuType.create(TotemOfNightVisionRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfStrengthRecipeMenu>> TOTEM_OF_STRENGTH_RECIPE = REGISTRY.register("totem_of_strength_recipe", () -> IForgeMenuType.create(TotemOfStrengthRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfDolphinsGraceRecipeMenu>> TOTEM_OF_DOLPHINS_GRACE_RECIPE = REGISTRY.register("totem_of_dolphins_grace_recipe", () -> IForgeMenuType.create(TotemOfDolphinsGraceRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfLevitationRecipeMenu>> TOTEM_OF_LEVITATION_RECIPE = REGISTRY.register("totem_of_levitation_recipe", () -> IForgeMenuType.create(TotemOfLevitationRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfRegenerationRecipeMenu>> TOTEM_OF_REGENERATION_RECIPE = REGISTRY.register("totem_of_regeneration_recipe", () -> IForgeMenuType.create(TotemOfRegenerationRecipeMenu::new));
	public static final RegistryObject<MenuType<TotemOfGamblingRecipeMenu>> TOTEM_OF_GAMBLING_RECIPE = REGISTRY.register("totem_of_gambling_recipe", () -> IForgeMenuType.create(TotemOfGamblingRecipeMenu::new));
	public static final RegistryObject<MenuType<ConsumerGUIMenu>> CONSUMER_GUI = REGISTRY.register("consumer_gui", () -> IForgeMenuType.create(ConsumerGUIMenu::new));
	public static final RegistryObject<MenuType<HODHomePageMenu>> HOD_HOME_PAGE = REGISTRY.register("hod_home_page", () -> IForgeMenuType.create(HODHomePageMenu::new));
	public static final RegistryObject<MenuType<HODCategoriesMenu>> HOD_CATEGORIES = REGISTRY.register("hod_categories", () -> IForgeMenuType.create(HODCategoriesMenu::new));
	public static final RegistryObject<MenuType<HODOverworldMenu>> HOD_OVERWORLD = REGISTRY.register("hod_overworld", () -> IForgeMenuType.create(HODOverworldMenu::new));
	public static final RegistryObject<MenuType<HODTheWitherMenu>> HOD_THE_WITHER = REGISTRY.register("hod_the_wither", () -> IForgeMenuType.create(HODTheWitherMenu::new));
	public static final RegistryObject<MenuType<CompressorGUIMenu>> COMPRESSOR_GUI = REGISTRY.register("compressor_gui", () -> IForgeMenuType.create(CompressorGUIMenu::new));
	public static final RegistryObject<MenuType<GodliumKnifeRecipeMenu>> GODLIUM_KNIFE_RECIPE = REGISTRY.register("godlium_knife_recipe", () -> IForgeMenuType.create(GodliumKnifeRecipeMenu::new));
	public static final RegistryObject<MenuType<GodlyStorageCubeGUIMenu>> GODLY_STORAGE_CUBE_GUI = REGISTRY.register("godly_storage_cube_gui", () -> IForgeMenuType.create(GodlyStorageCubeGUIMenu::new));
	public static final RegistryObject<MenuType<GodlyStorageCubeRecipeMenu>> GODLY_STORAGE_CUBE_RECIPE = REGISTRY.register("godly_storage_cube_recipe", () -> IForgeMenuType.create(GodlyStorageCubeRecipeMenu::new));
	public static final RegistryObject<MenuType<TrialBricksRecipeMenu>> TRIAL_BRICKS_RECIPE = REGISTRY.register("trial_bricks_recipe", () -> IForgeMenuType.create(TrialBricksRecipeMenu::new));
	public static final RegistryObject<MenuType<KeyAnvilGUIMenu>> KEY_ANVIL_GUI = REGISTRY.register("key_anvil_gui", () -> IForgeMenuType.create(KeyAnvilGUIMenu::new));
	public static final RegistryObject<MenuType<ColdsteelGearRecipeMenu>> COLDSTEEL_GEAR_RECIPE = REGISTRY.register("coldsteel_gear_recipe", () -> IForgeMenuType.create(ColdsteelGearRecipeMenu::new));
	public static final RegistryObject<MenuType<FrozenForgeGUIMenu>> FROZEN_FORGE_GUI = REGISTRY.register("frozen_forge_gui", () -> IForgeMenuType.create(FrozenForgeGUIMenu::new));
	public static final RegistryObject<MenuType<ColdsteelHelmetRecipeMenu>> COLDSTEEL_HELMET_RECIPE = REGISTRY.register("coldsteel_helmet_recipe", () -> IForgeMenuType.create(ColdsteelHelmetRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelChestplateRecipeMenu>> COLDSTEEL_CHESTPLATE_RECIPE = REGISTRY.register("coldsteel_chestplate_recipe", () -> IForgeMenuType.create(ColdsteelChestplateRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelLeggingsRecipeMenu>> COLDSTEEL_LEGGINGS_RECIPE = REGISTRY.register("coldsteel_leggings_recipe", () -> IForgeMenuType.create(ColdsteelLeggingsRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelBootsRecipeMenu>> COLDSTEEL_BOOTS_RECIPE = REGISTRY.register("coldsteel_boots_recipe", () -> IForgeMenuType.create(ColdsteelBootsRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelSwordRecipeMenu>> COLDSTEEL_SWORD_RECIPE = REGISTRY.register("coldsteel_sword_recipe", () -> IForgeMenuType.create(ColdsteelSwordRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelPickaxeRecipeMenu>> COLDSTEEL_PICKAXE_RECIPE = REGISTRY.register("coldsteel_pickaxe_recipe", () -> IForgeMenuType.create(ColdsteelPickaxeRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelAxeRecipeMenu>> COLDSTEEL_AXE_RECIPE = REGISTRY.register("coldsteel_axe_recipe", () -> IForgeMenuType.create(ColdsteelAxeRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelShovelRecipeMenu>> COLDSTEEL_SHOVEL_RECIPE = REGISTRY.register("coldsteel_shovel_recipe", () -> IForgeMenuType.create(ColdsteelShovelRecipeMenu::new));
	public static final RegistryObject<MenuType<ColdsteelHoeRecipeMenu>> COLDSTEEL_HOE_RECIPE = REGISTRY.register("coldsteel_hoe_recipe", () -> IForgeMenuType.create(ColdsteelHoeRecipeMenu::new));
}
